#ifndef _ACT_PARAMS_H_
#define _ACT_PARAMS_H_
#include "ActDefines.h"
#define C_IC_UV_LEVEL 3U
#define C_IC_OV_LEVEL 0U
#define C_HALL_LATCHES 0U
#define C_BUSTIMEOUT_SLEEP 0U
#define C_AUTO_RECALIBRATE 0U
#define C_LIN_UV 2U
#define C_CURRTHRSHLD_TEMP_HYS 2
#define C_MOTOR_MICROSTEPS 3U
#define CONFIGURATION_ID (uint16_t)((('U' - '@') << 10) | (('H' - '@') << 5) | ('L' - '@'))
#define _SUPPORT_APP_TYPE C_APP_POSITIONING_ACT
#define C_MOTOR_FAMILY MF_STEPPER
#define _SUPPORT_BIPOLAR_MODE BIPOLAR_MODE_UW_VT
#define PWM_FREQ 19067U
#define C_MOTOR_COILS 2U
#define C_MOTOR_PHASES 4U
#define C_MOTOR_POLE_PAIRS 5U
#define C_MOTOR_STEP_PER_PHASE 2U
#define C_MOTOR_GEAR_BOX_RATIO 143U
#define C_SHAFT_STEPS_PER_ROTATION 6400U
#define C_TACHO_MODE 0U
#define C_MOVAVG_SSZ 4U
#define C_COIL_R 5000U
#define C_COIL_L 40000U
#define C_DETECTOR_DELAY 128U
#define C_STALL_A_DET 1U
#define C_STALL_O_DET 0U
#define C_STALL_S_DET 0U
#define C_STALL_A_THRESHOLD ((uint8_t)(((20.0 * 128) + 50) / 100))
#define C_STALL_A_WIDTH 3U
#define C_STALL_O_THRESHOLD ((uint8_t)((0 * 128) / 100))
#define C_STALL_O_WIDTH (1U - 1U)
#define C_STALL_S_THRESHOLD ((uint8_t)((0 * 128U) / 100U))
#define C_STALL_S_WIDTH 0U
#define C_STALL_SPEED_DEPENDED 0U
#define C_RESTALL_POR 0U
#define C_MOTOR_CONST_10MV_PER_RPS 17U
#define C_MOTOR_CONST_MV_PER_RPS 170U
#define C_TOT_COILS_R C_COIL_R
#define C_TOT_COILS_L C_COIL_L
#define C_PID_HOLDING_CURR_LEVEL 25U
#define C_PID_RUNNING_CURR_LEVEL 100U
#define C_PID_BOOST_CURR_LEVEL 0U
#define C_NV_CURR_DIV 0U
#define C_REWIND_STEPS 8U
#define C_PID_RUNNING_CURR_MIN 10U
#define C_PID_RUNNING_CURR_MAX 100U
#define C_PID_STARTING_CURR_MAX 100U
#define C_SPEED_ALIGNMENT 60U
#define C_SPEED_MIN 143U
#define C_SPEED_0 286U
#define C_SPEED_1 572U
#define C_SPEED_2 1000U
#define C_SPEED_3 1430U
#define C_SPEED_TORQUE_BOOST 0U
#define C_ACCELERATION_CONST 10000U
#define C_ACCELERATION_STEPS C_MOTOR_MICROSTEPS
#define C_DECELERATION_STEPS C_MOTOR_MICROSTEPS
#define C_AUTOSPEED_TEMP_1 -40
#define C_AUTOSPEED_TEMP_2 -15
#define C_AUTOSPEED_TEMP_3 +60
#define C_AUTOSPEED_TEMPZONE_1 0U
#define C_AUTOSPEED_TEMPZONE_2 1U
#define C_AUTOSPEED_TEMPZONE_3 3U
#define C_AUTOSPEED_TEMPZONE_4 1U
#define C_AUTOSPEED_VOLT_1 ((uint16_t)(10.5 * 8))
#define C_AUTOSPEED_VOLT_2 ((uint16_t)(11.75 * 8))
#define C_AUTOSPEED_VOLT_3 0xFFU
#define C_AUTOSPEED_VOLTZONE_1 0U
#define C_AUTOSPEED_VOLTZONE_2 1U
#define C_AUTOSPEED_VOLTZONE_3 3U
#define C_AUTOSPEED_VOLTZONE_4 0U
#define C_TARGET_LA 0U
#define C_PID_LA_COEF_P 192U
#define C_PID_LA_COEF_I 2U
#define C_PID_LA_COEF_D 0U
#define C_LA_OPEN_TO_CLOSE_AMPL 6U
#define C_STALL_LA_SPEED_OFFSET C_SPEED_MIN
#define C_STALL_SPEED_THRESHOLD 24U
#define C_CURRTHRSHLD_TEMP_1 -34
#define C_CURRTHRSHLD_TEMP_2 +8
#define C_CURRTHRSHLD_TEMP_3 +38
#define C_CURRTHRSHLD_TEMP_4 +62
#define C_CURRTHRSHLD_TEMP_HYS 2
#define C_CURRTHRSHLD_RATIO_1 ((uint16_t)(1.02 * 128))
#define C_CURRTHRSHLD_RATIO_2 ((uint16_t)(1.00 * 128))
#define C_CURRTHRSHLD_RATIO_3 ((uint16_t)(1.00 * 128))
#define C_CURRTHRSHLD_RATIO_4 ((uint16_t)(1.12 * 128))
#define C_CURRTHRSHLD_AREA_1 1U
#define C_CURRTHRSHLD_AREA_2 3U
#define C_CURRTHRSHLD_AREA_3 1U
#define C_CURRTHRSHLD_AREA_4 3U
#define C_CURRTHRSHLD_AREA_5 1U
#define C_APP_OT_LEVEL 105
#define C_APP_UV_LEVEL ((uint8_t)(8.0 * 8))
#define C_APP_OV_LEVEL ((uint8_t)(17.5 * 8))
#define C_PID_RUNNINGCTRL_PERIOD 1U
#define C_PID_RUNNINGCTRL_PERIOD_UNIT C_PID_PERIOD_UNIT_TIME
#define C_PID_HOLDINGCTRL_PERIOD 125U
#define C_PID_COEF_P 32U
#define C_PID_COEF_I 32U
#define C_PID_COEF_D 0U
#define C_PID_THRSHLDCTRL_PERIOD 16U
#define C_LOADDUMP_VOLT 100U
#define C_VSUP_REF ((uint8_t)(13.5 * 8))
#define C_MIN_HOLDCORR_RATIO ((uint8_t)(2.5 * 256 / 100))
#define C_MIN_CORR_RATIO ((uint8_t)(8 * 256 / 100))
#define C_MAX_CORR_RATIO ((uint8_t)((98.4 * 256 / 100) - 1))
#define C_PID_RAMP_DOWN 0U
#define C_PID_RAMP_UP 0U
#define C_LEAD_ANGLE 0U
#define C_STARTUP_CORR_RATIO 0U
#define C_STALL_LA_THRESHOLD_FOC 3U
#define C_STALL_LA_THRESHOLD_OL 12U
#define C_STALL_LA_WIDTH_FOC 8U
#define C_STALL_LA_WIDTH_OL 3U
#define C_DEFAULT_TRAVEL (uint16_t)(((120UL * (C_SHAFT_STEPS_PER_ROTATION / 20U)) + 9U) / 18U)
#define C_TRAVEL_OFFSET (uint16_t)(((15UL * (C_SHAFT_STEPS_PER_ROTATION / 20U)) + 9U) / 18U)
#define C_ROUNDING_OFFSET (uint16_t)(((1UL * (C_SHAFT_STEPS_PER_ROTATION / 20U)) + 9U) / 18U)
#define C_TRAVEL_TOLERANCE_LO (uint8_t)(((10UL * (C_SHAFT_STEPS_PER_ROTATION / 20U)) + 9U) / 18U)
#define C_TRAVEL_TOLERANCE_UP (uint8_t)(((10UL * (C_SHAFT_STEPS_PER_ROTATION / 20U)) + 9U) / 18U)
#define C_ENDSTOP_TIME 100U
#endif
