#ifndef _APP_BUILD_H_
#define _APP_BUILD_H_
#include <stdint.h>
#include <syslib.h>
#if defined (__MLX81160__)
#include "../camculib/ioports_MLX81160.h"
#include "../camculib/mem_map_MLX81160.h"
#elif defined (__MLX81330__)
#include "../camculib/ioports_MLX81330.h"
#include "../camculib/mem_map_MLX81330.h"
#elif defined (__MLX81332__)
#include "../camculib/ioports_MLX81332.h"
#include "../camculib/mem_map_MLX81332.h"
#elif defined (__MLX81334__)
#include "../camculib/ioports_MLX81334.h"
#include "../camculib/mem_map_MLX81334.h"
#elif defined (__MLX81339__)
#include "camculib/ioports_MLX81339.h"
#include "camculib/mem_map_MLX81339.h"
#elif defined (__MLX81340__)
#include "../camculib/ioports_MLX81340.h"
#include "../camculib/mem_map_MLX81340.h"
#elif defined (__MLX81344__)
#include "../camculib/ioports_MLX81344.h"
#include "../camculib/mem_map_MLX81344.h"
#elif defined (__MLX81346__)
#include "../camculib/ioports_MLX81346.h"
#include "../camculib/mem_map_MLX81346.h"
#elif defined (__MLX81350__)
#include "../camculib/ioports_MLX81350.h"
#include "../camculib/mem_map_MLX81350.h"
#else
#error "ERROR: ioports-file not found"
#endif
#include "AppDefines.h"
#include "AppSwitches.h"
#define _CHIP_PACKAGE QFN24
#if (_APP_ZWICKAU != FALSE) || (_SUPPORT_TRIAXIS_MLX90363 != FALSE) || (_SUPPORT_DUAL_HALL_LATCH_MLX92251 != FALSE) || \
(_SUPPORT_DUAL_HALL_LATCH_MLX92255 != FALSE) || (CAN_COMM != FALSE) || (UART_COMM != FALSE)
#define _DEBUG_IO FALSE
#else
#define _DEBUG_IO FALSE
#endif
#define _DEBUG_ACTUATOR_MODE FALSE
#define _DEBUG_ALIVE FALSE
#define _DEBUG_BEMF_SENSE FALSE
#define _DEBUG_CAN FALSE
#define _DEBUG_CAN_TCAN4550 FALSE
#define _DEBUG_COMMUT_ISR FALSE
#define _DEBUG_CPU_CLOCK FALSE
#define _DEBUG_CPU_HALT FALSE
#define _DEBUG_CPU_LOAD FALSE
#define _DEBUG_DEBUGGER_SUPPORT FALSE
#define _DEBUG_DIAG FALSE
#define _DEBUG_DIAG_OC FALSE
#define _DEBUG_DIAG_OT FALSE
#define _DEBUG_DIAG_OV_UV FALSE
#define _DEBUG_DIAG_PROT FALSE
#define _DEBUG_DIAG_UV_VDDA FALSE
#define _DEBUG_DIAG_VDS FALSE
#define _DEBUG_DIAG_VDDD_UV FALSE
#define _DEBUG_DIAG_VDDAF_UV FALSE
#define _DEBUG_EMC_BCI_TEST FALSE
#define _DEBUG_FATAL FALSE
#define _DEBUG_FLASH_BIST FALSE
#define _DEBUG_FLPD_ERASE FALSE
#define _DEBUG_FLPD_WRITE FALSE
#define _DEBUG_FOC_IB_IQ FALSE
#define _DEBUG_FOC_PERF FALSE
#define _DEBUG_HALL_LATCH_ISR FALSE
#define _DEBUG_I2C FALSE
#define _DEBUG_I2C_MASTER FALSE
#define _DEBUG_INDUCTIVE_POS_SENSOR FALSE
#define _DEBUG_IO_ADC FALSE
#define _DEBUG_IO_CPU_PERF FALSE
#define _DEBUG_LIN_BUS_TO FALSE
#define _DEBUG_LIN_ISR FALSE
#define _DEBUG_LINAA FALSE
#define _DEBUG_MOTION FALSE
#define _DEBUG_MOTOR_START FALSE
#define _DEBUG_MOTOR_STOP FALSE
#define _DEBUG_NV_EMERGENCY_STORE FALSE
#define _DEBUG_NV_WRITE FALSE
#define _DEBUG_NV_WRITE_BACKGROUND FALSE
#define _DEBUG_OSD FALSE
#define _DEBUG_PID_CONTROL FALSE
#define _DEBUG_PRESSURE FALSE
#define _DEBUG_PWM_COMM FALSE
#define _DEBUG_PWM_POL FALSE
#define _DEBUG_PWM_TO_DRV_DELAY FALSE
#define _DEBUG_PWM_VARIABLE_PWM FALSE
#define _DEBUG_RELAY_SOLENOID FALSE
#define _DEBUG_RESOLVER FALSE
#define _DEBUG_RSTAT FALSE
#define _DEBUG_S2R FALSE
#define _DEBUG_SELFTEST FALSE
#define _DEBUG_SPI FALSE
#define _DEBUG_SPIKE_DETECTED FALSE
#define _DEBUG_SRP FALSE
#define _DEBUG_STALL_A FALSE
#define _DEBUG_STALL_O FALSE
#define _DEBUG_STIMER_ISR FALSE
#define _DEBUG_SUPPLY_ROBUSTNESS FALSE
#define _DEBUG_SYSERR FALSE
#define _DEBUG_TRIAXIS FALSE
#define _DEBUG_UART FALSE
#define _DEBUG_UART_ACTUATOR FALSE
#define _DEBUG_UART_QUAD_CAR FALSE
#define _DEBUG_UART_SCOPE FALSE
#define _DEBUG_UDS_WRITE FALSE
#define _DEBUG_WDACK FALSE
#define _DEBUG_WIND_MILL FALSE
#define _SUPPORT_CHIP_TEST FALSE
#define _DEBUG_ADC FALSE
#define _DEBUG_ADC_HV_IO FALSE
#define _DEBUG_ADC_LV_IOx FALSE
#define _DEBUG_ADC_VDDA_VDDD FALSE
#define _DEBUG_ADC_VDDAF FALSE
#define _DEBUG_ADC_VAUX FALSE
#define _DEBUG_ADC_VBGD FALSE
#define _DEBUG_ADC_VPHx FALSE
#define _DEBUG_ADC_VS FALSE
#define _DEBUG_ADC_VSM FALSE
#define _DEBUG_ADC_VSMF FALSE
#define _DEBUG_ADC_LIN FALSE
#define _DEBUG_ADC_LINAA_CM FALSE
#define _DEBUG_ADC_LINAA_DM FALSE
#define _DEBUG_ADC_MCUR FALSE
#define _DEBUG_ADC_MCURF FALSE
#define _DEBUG_ADC_SAMPLEnHOLD FALSE
#define _DEBUG_AWD FALSE
#define _DEBUG_IWD FALSE
#define _DEBUG_CPU_CLOCK FALSE
#define _DEBUG_IO_CPU_PERF FALSE
#define _DEBUG_DELAY FALSE
#define _DEBUG_RESET FALSE
#define _DEBUG_STIMER FALSE
#define _DEBUG_IO_3_0 FALSE
#define _DEBUG_IO_7_0 FALSE
#define _DEBUG_IO_8_11 FALSE
#define _DEBUG_IO_ISR FALSE
#define _DEBUG_IO_EDGE FALSE
#define _DEBUG_IO_0 FALSE
#define _DEBUG_IO_1 FALSE
#define _DEBUG_IO_2 FALSE
#define _DEBUG_IO_3 FALSE
#define _DEBUG_IO_4 FALSE
#define _DEBUG_IO_5 FALSE
#define _DEBUG_IO_6 FALSE
#define _DEBUG_IO_7 FALSE
#define _DEBUG_PWM_TO_IO FALSE
#define _DEBUG_PWM_MASTER1_TO_PHASE FALSE
#define _DEBUG_NV FALSE
#define _DEBUG_MOTOR_CURRENT_FLT FALSE
#define _DEBUG_MCUR_CYCLIC FALSE
#define _DEBUG_MCUR_SUB_SAMPLED FALSE
#define C_SUB_SAMPLE_MASK 0x0003U
#define _DEBUG_MCUR_FOC FALSE
#define _DEBUG_MCUR_FOC_PID FALSE
#define _DEBUG_MCUR_SENSE FALSE
#define _DEBUG_MCUR_STALL FALSE
#define _DEBUG_MCUR_WINDMILL FALSE
#define _DEBUG_MLX90377 FALSE
#define _DEBUG_MLX90381 FALSE
#define _DEBUG_IV_STALL FALSE
#define _DEBUG_LA_STALL FALSE
#define _DEBUG_HALL_LATCH FALSE
#define _DEBUG_BEMF_SENSE_STALL FALSE
#if (_DEBUG_IO != FALSE)
static inline void DEBUG_IO_INIT(void)
{
#if (_DEBUG_CPU_CLOCK != FALSE)
IO_CTIMER1_TREGB = 4U;
IO_CTIMER1_TREGA = 2U;
IO_CTIMER1_CTRL = (C_CTIMER1_DIV_CPU | C_CTIMER1_MODE_PWM | B_CTIMER1_ENCMP);
IO_CTIMER1_CTRL = B_CTIMER1_START;
IO_PORT_IO_CFG0 = (C_PORT_IO_CFG0_IO0_OUT_SEL_CTIMER1
#if (_CHIP_PACKAGE == QFN24) || (_CHIP_PACKAGE == QFN32)
| C_PORT_IO_CFG0_IO1_OUT_SEL_SOFT
| C_PORT_IO_CFG0_IO2_OUT_SEL_SOFT
| C_PORT_IO_CFG0_IO3_OUT_SEL_SOFT
#endif
);
#if !defined (__MLX81330__) && !defined (__MLX81350__)
IO_PORT_IO_CFG1 = (C_PORT_IO_CFG1_IO4_OUT_SEL_SOFT |
C_PORT_IO_CFG1_IO5_OUT_SEL_SOFT);
#endif
#else
#if (_CHIP_PACKAGE == QFN24) || (_CHIP_PACKAGE == QFN32)
IO_PORT_IO_CFG0 = (0
#if ((_SUPPORT_IO_DUT_SELECT_HVIO == FALSE) || (HVIO_DUT_SELECT != PIN_FUNC_IO_0)) && \
((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_0) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_0))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_0) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_0) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_0) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_0))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_0) && (C_PWM_COMM_OUT != PIN_FUNC_IO_0))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_0) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_0)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_0) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_0))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_0) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_0) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_0))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_0) && (_SUPPORT_HLB_IO != PIN_FUNC_IO_0) && (_SUPPORT_HLC_IO != PIN_FUNC_IO_0))) && \
(((_SUPPORT_TRIAXIS_MLX90377 == FALSE) && (_SUPPORT_TRIAXIS_MLX90422 == FALSE)) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_0)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_0) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_0)))
| C_PORT_IO_CFG0_IO0_OUT_SEL_SOFT
#endif
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_1) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_1))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_1) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_1) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_1) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_1))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_1) && (C_PWM_COMM_OUT != PIN_FUNC_IO_1))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_1) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_1)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_1) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_1))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_1) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_1) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_1))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_1) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_1)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_1)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_1)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_1) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_1)))
| C_PORT_IO_CFG0_IO1_OUT_SEL_SOFT
#endif
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_2) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_2))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_2) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_2) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_2) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_2))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_2) && (C_PWM_COMM_OUT != PIN_FUNC_IO_2))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_2) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_2)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_2) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_2))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_2) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_2) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_2))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_2) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_2)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_2)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_2)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_2) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_2)))
| C_PORT_IO_CFG0_IO2_OUT_SEL_SOFT
#endif
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_3) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_3))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_3) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_3) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_3) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_3))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_3) && (C_PWM_COMM_OUT != PIN_FUNC_IO_3))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_3) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_3)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_3) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_3))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_3) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_3) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_3))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_3) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_3)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_3)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_3)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_3) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_3)))
| C_PORT_IO_CFG0_IO3_OUT_SEL_SOFT
#endif
);
#if !defined (__MLX81330__) && !defined (__MLX81350__)
IO_PORT_IO_CFG1 = (0
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_4) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_4))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_4) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_4) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_4) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_4))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_4) && (C_PWM_COMM_OUT != PIN_FUNC_IO_4))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_4) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_4)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_4) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_4))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_4) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_4) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_4))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_4) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_4)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_4)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_4)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_4) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_4)))
| C_PORT_IO_CFG1_IO4_OUT_SEL_SOFT
#endif
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_5) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_5))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_5) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_5) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_5) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_5))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_5) && (C_PWM_COMM_OUT != PIN_FUNC_IO_5))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_5) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_5)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_5) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_5))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_5) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_5) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_5))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_5) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_5)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_5)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_5)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_5) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_5)))
| C_PORT_IO_CFG1_IO5_OUT_SEL_SOFT
#endif
);
#endif
#else
IO_PORT_IO_CFG0 = C_PORT_IO_CFG0_IO0_OUT_SEL_SOFT;
#endif
#endif
#if ((_SUPPORT_IO_DUT_SELECT_HVIO == FALSE) || (HVIO_DUT_SELECT != PIN_FUNC_IO_0)) && \
((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_0) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_0))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_0) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_0) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_0) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_0))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_0) && (C_PWM_COMM_OUT != PIN_FUNC_IO_0))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_0) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_0)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_0) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_0))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_0) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_0) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_0))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_0) && (_SUPPORT_HLB_IO != PIN_FUNC_IO_0) && (_SUPPORT_HLC_IO != PIN_FUNC_IO_0))) && \
(((_SUPPORT_TRIAXIS_MLX90377 == FALSE) && (_SUPPORT_TRIAXIS_MLX90422 == FALSE)) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_0)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_0) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_0)))
IO_PORT_IO_OUT_EN |= B_PORT_IO_OUT_EN_IO0_LV_ENABLE;
#endif
#if (_CHIP_PACKAGE == QFN24) || (_CHIP_PACKAGE == QFN32)
IO_PORT_IO_ENABLE = (0
#if ((_SUPPORT_IO_DUT_SELECT_HVIO == FALSE) || (HVIO_DUT_SELECT != PIN_FUNC_IO_0)) && \
((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_0) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_0))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_0) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_0) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_0) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_0))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_0) && (C_PWM_COMM_OUT != PIN_FUNC_IO_0))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_0) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_0)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_0) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_0))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_0) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_0) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_0))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_0) && (_SUPPORT_HLB_IO != PIN_FUNC_IO_0) && (_SUPPORT_HLC_IO != PIN_FUNC_IO_0))) && \
(((_SUPPORT_TRIAXIS_MLX90377 == FALSE) && (_SUPPORT_TRIAXIS_MLX90422 == FALSE)) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_0)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_0) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_0)))
| B_PORT_IO_ENABLE_IO_ENABLE_0
#endif
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_1) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_1))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_1) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_1) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_1) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_1))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_1) && (C_PWM_COMM_OUT != PIN_FUNC_IO_1))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_1) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_1)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_1) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_1))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_1) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_1) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_1))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_1) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_1)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_1)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_1)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_1) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_1)))
| B_PORT_IO_ENABLE_IO_ENABLE_1
#endif
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_2) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_2))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_2) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_2) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_2) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_2))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_2) && (C_PWM_COMM_OUT != PIN_FUNC_IO_2))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_2) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_2)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_2) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_2))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_2) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_2) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_2))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_2) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_2)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_2)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_2)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_2) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_2)))
| B_PORT_IO_ENABLE_IO_ENABLE_2
#endif
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_3) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_3))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_3) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_3) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_3) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_3))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_3) && (C_PWM_COMM_OUT != PIN_FUNC_IO_3))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_3) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_3)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_3) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_3))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_3) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_3) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_3))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_3) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_3)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_3)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_3)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_3) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_3)))
| B_PORT_IO_ENABLE_IO_ENABLE_3
#endif
#if !defined (__MLX81330__) && !defined (__MLX81350__)
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_4) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_4))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_4) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_4) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_4) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_4))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_4) && (C_PWM_COMM_OUT != PIN_FUNC_IO_4))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_4) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_4)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_4) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_4))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_4) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_4) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_4))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_4) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_4)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_4)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_4)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_4) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_4)))
| B_PORT_IO_ENABLE_IO_ENABLE_4
#endif
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_5) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_5))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_5) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_5) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_5) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_5))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_5) && (C_PWM_COMM_OUT != PIN_FUNC_IO_5))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_5) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_5)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_5) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_5))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_5) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_5) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_5))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_5) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_5)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_5)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_5)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_5) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_5)))
| B_PORT_IO_ENABLE_IO_ENABLE_5
#endif
#endif
);
#endif
}
#if (_CHIP_PACKAGE == QFN24) || (_CHIP_PACKAGE == QFN32)
#if ((_SUPPORT_IO_DUT_SELECT_HVIO == FALSE) || (HVIO_DUT_SELECT != PIN_FUNC_IO_0)) && \
((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_0) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_0))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_0) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_0) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_0) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_0))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_0) && (C_PWM_COMM_OUT != PIN_FUNC_IO_0))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_0) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_0)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_0) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_0))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_0) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_0) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_0))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_0) && (_SUPPORT_HLB_IO != PIN_FUNC_IO_0) && (_SUPPORT_HLC_IO != PIN_FUNC_IO_0))) && \
(((_SUPPORT_TRIAXIS_MLX90377 == FALSE) && (_SUPPORT_TRIAXIS_MLX90422 == FALSE)) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_0)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_0) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_0)))
#define DEBUG_CLR_IO_E() {IO_PORT_IO_OUT_SOFT &= ~C_PORT_IO_OUT_SOFT_IO0_OUT; }
#define DEBUG_SET_IO_E() {IO_PORT_IO_OUT_SOFT |= C_PORT_IO_OUT_SOFT_IO0_OUT; }
#define DEBUG_TOG_IO_E() {IO_PORT_IO_OUT_SOFT ^= C_PORT_IO_OUT_SOFT_IO0_OUT; }
#endif
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_1) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_1))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_1) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_1) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_1) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_1))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_1) && (C_PWM_COMM_OUT != PIN_FUNC_IO_1))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_1) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_1)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_1) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_1))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_1) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_1) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_1))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_1) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_1)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_1)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_1)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_1) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_1)))
#define DEBUG_CLR_IO_A() {IO_PORT_IO_OUT_SOFT &= ~C_PORT_IO_OUT_SOFT_IO1_OUT; }
#define DEBUG_SET_IO_A() {IO_PORT_IO_OUT_SOFT |= C_PORT_IO_OUT_SOFT_IO1_OUT; }
#define DEBUG_TOG_IO_A() {IO_PORT_IO_OUT_SOFT ^= C_PORT_IO_OUT_SOFT_IO1_OUT; }
#endif
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_2) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_2))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_2) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_2) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_2) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_2))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_2) && (C_PWM_COMM_OUT != PIN_FUNC_IO_2))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_2) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_2)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_2) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_2))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_2) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_2) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_2))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_2) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_2)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_2)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_2)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_2) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_2)))
#define DEBUG_CLR_IO_B() {IO_PORT_IO_OUT_SOFT &= ~C_PORT_IO_OUT_SOFT_IO2_OUT; }
#define DEBUG_SET_IO_B() {IO_PORT_IO_OUT_SOFT |= C_PORT_IO_OUT_SOFT_IO2_OUT; }
#define DEBUG_TOG_IO_B() {IO_PORT_IO_OUT_SOFT ^= C_PORT_IO_OUT_SOFT_IO2_OUT; }
#endif
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_3) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_3))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_3) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_3) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_3) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_3))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_3) && (C_PWM_COMM_OUT != PIN_FUNC_IO_3))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_3) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_3)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_3) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_3))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_3) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_3) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_3))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_3) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_3)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_3)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_3)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_3) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_3)))
#define DEBUG_CLR_IO_C() {IO_PORT_IO_OUT_SOFT &= ~C_PORT_IO_OUT_SOFT_IO3_OUT; }
#define DEBUG_SET_IO_C() {IO_PORT_IO_OUT_SOFT |= C_PORT_IO_OUT_SOFT_IO3_OUT; }
#define DEBUG_TOG_IO_C() {IO_PORT_IO_OUT_SOFT ^= C_PORT_IO_OUT_SOFT_IO3_OUT; }
#endif
#if !defined (__MLX81330__) && !defined (__MLX81350__)
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_4) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_4))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_4) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_4) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_4) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_4))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_4) && (C_PWM_COMM_OUT != PIN_FUNC_IO_4))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_4) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_4)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_4) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_4))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_4) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_4) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_4))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_4) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_4)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_4)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_4)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_4) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_4)))
#define DEBUG_CLR_IO_D() {IO_PORT_IO_OUT_SOFT &= ~C_PORT_IO_OUT_SOFT_IO4_OUT; }
#define DEBUG_SET_IO_D() {IO_PORT_IO_OUT_SOFT |= C_PORT_IO_OUT_SOFT_IO4_OUT; }
#define DEBUG_TOG_IO_D() {IO_PORT_IO_OUT_SOFT ^= C_PORT_IO_OUT_SOFT_IO4_OUT; }
#endif
#if ((_SUPPORT_UART == FALSE) || ((_SUPPORT_UART_RX_IO != PIN_FUNC_IO_5) && (_SUPPORT_UART_TX_IO != PIN_FUNC_IO_5))) && \
((_SUPPORT_SPI == FALSE) || ((_SUPPORT_SPI_MOSI_IO != PIN_FUNC_IO_5) && (_SUPPORT_SPI_MISO_IO != PIN_FUNC_IO_5) && (_SUPPORT_SPI_CLK != PIN_FUNC_IO_5) && (_SUPPORT_SPI_SS != PIN_FUNC_IO_5))) && \
((PWM_COMM == FALSE) || ((C_PWM_COMM_IN != PIN_FUNC_IO_5) && (C_PWM_COMM_OUT != PIN_FUNC_IO_5))) && \
((_SUPPORT_I2C == FALSE) || ((((_SUPPORT_I2C_MASTER != FALSE) && (C_I2C_MASTER_SCK_IO != PIN_FUNC_IO_5) && (C_I2C_MASTER_SDA_IO != PIN_FUNC_IO_5)) || \
((_SUPPORT_I2C_SLAVE != FALSE) && (C_I2C_SLAVE_SCK_IO != PIN_FUNC_IO_5) && (C_I2C_SLAVE_SDA_IO != PIN_FUNC_IO_5))))) && \
((CAN_COMM == FALSE) || ((_SUPPORT_CAN_IRQ_IO != PIN_FUNC_IO_5) && (_SUPPORT_CAN_STDBY_IO != PIN_FUNC_IO_5) && (_SUPPORT_CAN_RST_IO != PIN_FUNC_IO_5))) && \
((_SUPPORT_HALL_LATCH == FALSE) || ((_SUPPORT_HLA_IO != PIN_FUNC_IO_5) && ((_SUPPORT_NR_OF_HL < 2) || (_SUPPORT_HLB_IO != PIN_FUNC_IO_5)) && ((_SUPPORT_NR_OF_HL < 3) || (_SUPPORT_HLC_IO != PIN_FUNC_IO_5)))) && \
((_SUPPORT_TRIAXIS_MLX90377 == FALSE) || (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_5)) && \
((_SUPPORT_TRIAXIS_MLX9038x == FALSE) || ((_SUPPORT_RESOLVER_X_IO != PIN_FUNC_IO_5) && (_SUPPORT_RESOLVER_Y_IO != PIN_FUNC_IO_5)))
#define DEBUG_CLR_IO_E() {IO_PORT_IO_OUT_SOFT &= ~C_PORT_IO_OUT_SOFT_IO5_OUT; }
#define DEBUG_SET_IO_E() {IO_PORT_IO_OUT_SOFT |= C_PORT_IO_OUT_SOFT_IO5_OUT; }
#define DEBUG_TOG_IO_E() {IO_PORT_IO_OUT_SOFT ^= C_PORT_IO_OUT_SOFT_IO5_OUT; }
#endif
#endif
#else
#define DEBUG_CLR_IO_A() {IO_PORT_IO_OUT_SOFT &= ~C_PORT_IO_OUT_SOFT_IO0_OUT; }
#define DEBUG_SET_IO_A() {IO_PORT_IO_OUT_SOFT |= C_PORT_IO_OUT_SOFT_IO0_OUT; }
#define DEBUG_TOG_IO_A() {IO_PORT_IO_OUT_SOFT ^= C_PORT_IO_OUT_SOFT_IO0_OUT; }
#endif
#endif
#endif