#ifndef _APP_SWITCHES_H_
#define _APP_SWITCHES_H_
#include "ActDefines.h"
#include "AppDefines.h"
#define _APP_BURN_IN FALSE
#define _APP_SUPPLY_RANGE C_APP_SUPPLY_RANGE_12V
#define MOTOR_TYPE MT_ITW_EVENT
#define _SUPPORT_FULLSTEP FALSE
#define _SUPPORT_HALFSTEP FALSE
#if (_SUPPORT_FULLSTEP != FALSE)
#define C_MICROSTEP_PER_FULLSTEP 1U
#elif (_SUPPORT_HALFSTEP != FALSE)
#define C_MICROSTEP_PER_FULLSTEP 2U
#else
#define C_MICROSTEP_PER_FULLSTEP 8U
#endif
#include "ActParams.h"
#define _SUPPORT_CPUSPEED4 TRUE
#define _SUPPORT_CPUSPEED5 FALSE
#define _SUPPORT_CPUSPEED_29M5 FALSE
#define _SUPPORT_CPUSPEED_40M FALSE
#if (_SUPPORT_CPUSPEED_29M5 != FALSE)
#undef FPLL
#define FPLL 29500U
#elif (_SUPPORT_CPUSPEED_40M != FALSE)
#undef FPLL
#define FPLL 40000U
#endif
#define PLL_FREQ (1000UL * FPLL)
#define _SUPPORT_COPRO FALSE
#define _SUPPORT_RAM_FUNC FALSE
#define _SUPPORT_OPTIMIZE_FOR_SPEED FALSE
#define _SUPPORT_ROM_TABLE FALSE
#define _SUPPORT_BUGFIX_DCC_1293 TRUE
#define _SUPPORT_BUGFIX_AMALTHEA_1428 FALSE
#define _APP_BENCHMARK_COREMARK FALSE
#define _APP_DMA_STRESS_TEST FALSE
#define _APP_ZWICKAU FALSE
#define ANA_COMM FALSE
#define CAN_COMM FALSE
#define GPIO_COMM FALSE
#define I2C_COMM FALSE
#define LIN_COMM TRUE
#define PWM_COMM FALSE
#define SPI_COMM FALSE
#if !defined (__MLX81330__)
#define UART_COMM FALSE
#else
#define UART_COMM FALSE
#endif
#if (I2C_COMM == FALSE)
#if defined (__MLX81332_w90381__) || defined (__MLX81340_w90381__)
#define I2C_MASTER_PROT I2C_MASTER_PROT_TRIAXIS_90381
#else
#define I2C_MASTER_PROT I2C_MASTER_PROT_NONE
#endif
#define I2C_SLAVE_PROT I2C_SLAVE_PROT_NONE
#else
#define I2C_MASTER_PROT I2C_MASTER_PROT_NONE
#define I2C_SLAVE_PROT I2C_SLAVE_PROT_MLX_ACT
#endif
#if (LIN_COMM != FALSE)
#define LINPROT LIN2X_HVAC49
#define _SUPPORT_AUTO_BAUDRATE TRUE
#define _SUPPORT_BUSTIMEOUT TRUE
#define _SUPPORT_BUSTIMEOUT_SLEEP FALSE
#define _SUPPORT_LIN_BUS_ACTIVITY_CHECK TRUE
#define _SUPPORT_LIN_SLEEP TRUE
#define _SUPPORT_LIN_UV FALSE
#define _SUPPORT_LINNETWORK_LOADER FALSE
#if (LIN_COMM != FALSE)
#if (LINPROT == LIN2X_HVAC52)
#define _SUPPORT_HVAC_GROUP_ADDRESS TRUE
#define _SUPPORT_LINAA_ESHUNT TRUE
#define _SUPPORT_LINAA_VS_COMPENSATION TRUE
#else
#define _SUPPORT_HVAC_GROUP_ADDRESS FALSE
#define _SUPPORT_LINAA_ESHUNT FALSE
#define _SUPPORT_LINAA_VS_COMPENSATION FALSE
#endif
#endif
#if defined (__MLX81160__) || defined (__MLX81344__) || defined (__MLX81346__)
#define _SUPPORT_LIN_AA FALSE
#elif ((LINPROT == LIN2X_HVAC49) || (LINPROT == LIN2X_HVAC52) || (LINPROT == LIN2X_AIRVENT12)) && \
(PROJECT_ID == 0x0503) || (PROJECT_ID == 0x050B) || \
(PROJECT_ID == 0x050F) || (PROJECT_ID == 0x0510) || (PROJECT_ID == 0x0511) || \
(PROJECT_ID == 0x0514) || (PROJECT_ID == 0x0515) || (PROJECT_ID == 0x0516) || \
(PROJECT_ID == 0x0701) || (PROJECT_ID == 0x0705) || \
(PROJECT_ID == 0x070A) || (PROJECT_ID == 0x070B) || (PROJECT_ID == 0x070C) || \
(PROJECT_ID == 0x070F) || (PROJECT_ID == 0x0710) || (PROJECT_ID == 0x0711) || \
(PROJECT_ID == 0x0901) || \
(PROJECT_ID == 0x0A01) || (PROJECT_ID == 0x0A03) || (PROJECT_ID == 0x0A05) || \
(PROJECT_ID == 0x2601) || (PROJECT_ID == 0x2602) || (PROJECT_ID == 0x2604)
#define _SUPPORT_LIN_AA TRUE
#else
#define _SUPPORT_LIN_AA FALSE
#endif
#if (_SUPPORT_LIN_AA != FALSE)
#define LIN_AA_BSM_SNPD_R1p0 TRUE
#define LIN_AA_CURRSRC_ONLY TRUE
#define LIN_AA_NV TRUE
#define LIN_AA_EXT_VOLTAGE FALSE
#define LIN_AA_INFO FALSE
#define LIN_AA_LINFRAME_TIMEOUT TRUE
#define LIN_AA_RESOURCE LIN_AA_RESOURCE_CTIMER1
#define LIN_AA_SCREENTEST FALSE
#define LIN_AA_TEST_DUT FALSE
#define LIN_AA_TIMEOUT TRUE
#if (PROJECT_ID == 0x0503) || (PROJECT_ID == 0x050B) || \
(PROJECT_ID == 0x0514) || (PROJECT_ID == 0x0515) || (PROJECT_ID == 0x0516)
#define LIN_AA_VDDA_5V TRUE
#else
#define LIN_AA_VDDA_5V FALSE
#endif
#endif
#define _SUPPORT_NV_WRITE_IMMEDIATE FALSE
#if (LINPROT == LIN2X_HVAC49) || (LINPROT == LIN2X_HVAC52) || (LINPROT == LIN2X_AIRVENT12)
#define _SUPPORT_DIAG_B0 TRUE
#define _SUPPORT_DIAG_B0_NV_STORE TRUE
#define _SUPPORT_DIAG_B1 TRUE
#define _SUPPORT_DIAG_B1_NV_STORE TRUE
#define _SUPPORT_DIAG_B2_SERIALNR FALSE
#define _SUPPORT_DIAG_B2_MSG_ID TRUE
#define _SUPPORT_READ_BY_ID_CUSTOMERID FALSE
#define _SUPPORT_READ_BY_ID_PROD_DATE FALSE
#define _SUPPORT_DIAG_B3 FALSE
#define _SUPPORT_DIAG_B3_NV_STORE FALSE
#define _SUPPORT_DIAG_B4 TRUE
#if (LINPROT == LIN2X_HVAC52)
#define _SUPPORT_DIAG_B6 TRUE
#else
#define _SUPPORT_DIAG_B6 FALSE
#endif
#define _SUPPORT_DIAG_B7 TRUE
#define _SUPPORT_DIAG_B7_NV_STORE TRUE
#define _SUPPORT_ISO17987 FALSE
#else
#define _SUPPORT_DIAG_B0 TRUE
#define _SUPPORT_DIAG_B0_NV_STORE TRUE
#define _SUPPORT_DIAG_B1 FALSE
#define _SUPPORT_DIAG_B1_NV_STORE FALSE
#define _SUPPORT_DIAG_B2_SERIALNR FALSE
#define _SUPPORT_DIAG_B2_MSG_ID TRUE
#define _SUPPORT_READ_BY_ID_CUSTOMERID FALSE
#define _SUPPORT_READ_BY_ID_PROD_DATE FALSE
#define _SUPPORT_DIAG_B3 FALSE
#define _SUPPORT_DIAG_B3_NV_STORE FALSE
#define _SUPPORT_DIAG_B4 FALSE
#define _SUPPORT_DIAG_B6 TRUE
#define _SUPPORT_DIAG_B7 TRUE
#define _SUPPORT_DIAG_B7_NV_STORE FALSE
#define _SUPPORT_ISO17987 TRUE
#endif
#define _SUPPORT_UDS FALSE
#define _SUPPORT_UDS_DK _SUPPORT_UDS_DK1
#define _SUPPORT_UDS_READ_BY_ID_SUBSYS TRUE
#define _SUPPORT_UDS_SESSION_CTRL FALSE
#define _SUPPORT_UDS_RESET FALSE
#define _SUPPORT_UDS_WRITE_BY_ID TRUE
#define _SUPPORT_UDS_TESTER_PRESENT FALSE
#define _SUPPORT_MLX_DEBUG_MODE TRUE
#define _SUPPORT_MLX_DEBUG_OPTIONS FALSE
#define _SUPPORT_NAD_RANGE_CHECK FALSE
#else
#define LINPROT NOLIN
#define _SUPPORT_MLX_DEBUG_MODE FALSE
#endif
#if (UART_COMM != FALSE)
#define _SUPPORT_UART_IF_APP C_UART_IF_NONE
#define _SUPPORT_UART2_IF_APP C_UART_IF_NONE
#define _SUPPORT_UART_SCOPE_MODE QUAD_SCOPE
#endif
#define _SUPPORT_ACOUSTIC_NOISE_REDUCTION FALSE
#define _SUPPORT_ACT_SPEED_BY_LIN FALSE
#define _SUPPORT_ADC_IO_CHECK FALSE
#define _SUPPORT_ADC_PWM_DELAY TRUE
#define _SUPPORT_ADC_REF_HV_CALIB FALSE
#define _SUPPORT_ADC_REF_MC_CALIB FALSE
#define _SUPPORT_ADC_SOS_TRIGGER ADC_SOS_TRIGGER_HW
#if (defined (__MLX81340B01__) || defined (__MLX81344B01__) || defined (__MLX81346B01__))
#define _SUPPORT_ADC_VSMF_OFF TRUE
#else
#define _SUPPORT_ADC_VSMF_OFF FALSE
#endif
#define _SUPPORT_ADC_TEMPCOMP TRUE
#define _SUPPORT_AMBIENT_TEMP TRUE
#if (_APP_SUPPLY_RANGE != C_APP_SUPPLY_RANGE_48V)
#define _SUPPORT_APP_48V_ADC FALSE
#else
#define _SUPPORT_APP_48V_ADC TRUE
#endif
#define _SUPPORT_APP_SAVE TRUE
#define _SUPPORT_APP_USER_MODE TRUE
#define _SUPPORT_AUTONOMOUS_DEMO FALSE
#define _SUPPORT_BG_FLASH_TEST FALSE
#define _SUPPORT_BG_RAM_TEST FALSE
#define _SUPPORT_BG_ROM_TEST FALSE
#define _SUPPORT_BG_MEM_TEST FALSE
#if (FLASH_BIST_START == 0x5800) || (FLASH_BIST_START == 0x8000)
#define _SUPPORT_BOOTLOADER BOOTLOADER_NONE
#define BOOTLOADER_SIZE 0U
#else
#define _SUPPORT_BOOTLOADER BOOTLOADER_LIN
#if (FLASH_BIST_START > 0x8000)
#define BOOTLOADER_SIZE (FLASH_BIST_START - 0x8000) / 2048
#else
#define BOOTLOADER_SIZE (FLASH_BIST_START - 0x5800) / 2048
#endif
#endif
#if (_SUPPORT_BOOTLOADER == BOOTLOADER_LIN)
#define _SUPPORT_BOOTLOADER_LIN TRUE
#else
#define _SUPPORT_BOOTLOADER_LIN FALSE
#endif
#define _SUPPORT_BOOTLOADER_PPM TRUE
#define _SUPPORT_BRAKING FALSE
#define _SUPPORT_CP_SSCM TRUE
#define _SUPPORT_CPFREQ 82U
#define _SUPPORT_CPFREQ_TEMPCOMP TRUE
#if (_APP_ZWICKAU != FALSE)
#define _SUPPORT_CPU_HALT FALSE
#define _SUPPORT_CPU_HALT_ADC_OFF FALSE
#define _SUPPORT_MLX_CHIP_STATUS TRUE
#define _SUPPORT_2ND_MLX_CHIP_STATUS FALSE
#else
#if (ANA_COMM != FALSE) || (PWM_COMM != FALSE)
#define _SUPPORT_CPU_HALT FALSE
#else
#define _SUPPORT_CPU_HALT TRUE
#endif
#define _SUPPORT_CPU_HALT_ADC_OFF TRUE
#define _SUPPORT_MLX_CHIP_STATUS FALSE
#define _SUPPORT_2ND_MLX_CHIP_STATUS FALSE
#endif
#if (LINPROT == LIN22_SIMPLE_PCT) || (I2C_SLAVE_PROT == I2C_SLAVE_PROT_POSITIONING)
#define _SUPPORT_CALIBRATION TRUE
#define _SUPPORT_HALF_AUTO_CALIB FALSE
#elif (LINPROT == LIN2X_HVAC49) || (LINPROT == LIN2X_HVAC52)
#define _SUPPORT_CALIBRATION FALSE
#define _SUPPORT_HALF_AUTO_CALIB FALSE
#endif
#define _SUPPORT_SPEED_AUTO TRUE
#define _SUPPORT_CRASH_RECOVERY FALSE
#define _SUPPORT_CRITICAL_PERIPHERAL_CHECK TRUE
#if (defined (__MLX81340B01__) || defined (__MLX81344B01__) || defined (__MLX81346B01__))
#define _SUPPORT_CSA_HIGHGAIN FALSE
#else
#define _SUPPORT_CSA_HIGHGAIN FALSE
#endif
#define _SUPPORT_DED_RETRY FALSE
#define _SUPPORT_DEGRADED_MODE TRUE
#define _SUPPORT_DIRECTION_IN FALSE
#define DIRECTION_PIN_IO PIN_FUNC_IO_4
#define _SUPPORT_DUAL_APP_BLOCK TRUE
#define _SUPPORT_DUAL_RELAY FALSE
#define _DEBUG_FLASH_WRITE_CYCLES FALSE
#define _SUPPORT_DWD FALSE
#define _SUPPORT_NV_TYPE C_NV_EEPROM
#define _SUPPORT_NV_BACKUP FALSE
#define _SUPPORT_NV_MOTOR_PARAMS TRUE
#define _SUPPORT_NV_NON_BLOCK_WRITE FALSE
#define _SUPPORT_NV_EMERGENCY_STORE FALSE
#define _SUPPORT_NV_HEX FALSE
#define _SUPPORT_EMERGENCY_RUN TRUE
#define _SUPPORT_FAST_ATAN2 TRUE
#define _SUPPORT_FAST_ATAN2_LOOKUP TRUE
#define _SUPPORT_FAST_STOP FALSE
#define _SUPPORT_FLASH_PRODUCTION_DATA FALSE
#define _SUPPORT_MECHANICAL_ERROR FALSE
#define _SUPPORT_POR_MOTORDRIVER FALSE
#if defined (_SUPPORT_APP_TYPE) && (_SUPPORT_APP_TYPE == C_APP_CONTINUOUS_ACT)
#define _SUPPORT_POS_INIT FALSE
#else
#define _SUPPORT_POS_INIT TRUE
#endif
#define _SUPPORT_RESET_BY_IO FALSE
#define _SUPPORT_RINNEN FALSE
#if defined (__MLX81340B01__) || defined (__MLX81344B01__) || defined (__MLX81346B01__)
#define _SUPPORT_ROM_FAST_MATH TRUE
#else
#define _SUPPORT_ROM_FAST_MATH FALSE
#endif
#define _SUPPORT_SINCOS_TABLE_SZ 256
#define _SUPPORT_RSTAT FALSE
#define _SUPPORT_SAVE_POS_AT_SLEEP FALSE
#define _SUPPORT_SLEEP_EMRUN FALSE
#define _SUPPORT_SLEEP_RAM_RETENTION FALSE
#define _SUPPORT_SPECIAL_COMM_FIELD FALSE
#define _SUPPORT_SPECIAL_PCTPOS FALSE
#define _SUPPORT_SPEED_CHANGE TRUE
#if (UART_COMM != FALSE) || (PWM_COMM != FALSE) || (_SUPPORT_ACOUSTIC_NOISE_REDUCTION != FALSE)
#define _SUPPORT_SSCM FALSE
#else
#define _SUPPORT_SSCM TRUE
#endif
#define _SUPPORT_START_TO_RUN FALSE
#define _SUPPORT_STIMER_MODE C_STIMER_CLKSRC_1MHz
#define _SUPPORT_TACHO_OUT FALSE
#define _SUPPORT_TACHO_OUT_OD FALSE
#define TACHO_OUT_IO PIN_FUNC_IO_0
#define _SUPPORT_TNCTOC FALSE
#define _SUPPORT_VDDA_5V FALSE
#define _SUPPORT_WAKEUP_BY_IO FALSE
#define _SUPPORT_WHILE_RETRY_LIMITED FALSE
#define _DEBUG_IO_7_0_ISR FALSE
#define _SUPPORT_DIAG_DRV_PROT TRUE
#define _SUPPORT_DIAG_IRQCTLR_LEVEL TRUE
#define _SUPPORT_DIAG_OC TRUE
#define _SUPPORT_DIAG_OT TRUE
#define _SUPPORT_DIAG_RINNEN_ROBUSTNESS FALSE
#define _SUPPORT_DIAG_VDDA TRUE
#define _SUPPORT_DIAG_VDDA_UV_RESET FALSE
#define _SUPPORT_DIAG_VDDA_UV_SLEEP FALSE
#define _SUPPORT_DIAG_VDDA_UV_WAKE_UP_TIMER FALSE
#define _SUPPORT_DIAG_VDDAF TRUE
#define _SUPPORT_DIAG_VDS FALSE
#define _SUPPORT_DRV_PROT_TRISTATE FALSE
#define _SUPPORT_DRV_PROT_VDS TRUE
#define _SUPPORT_DRV_PROT_VDS_PM_TRI FALSE
#define _SUPPORT_DRV_PROT_OC FALSE
#define _SUPPORT_DRV_PROT_UV_VDDAF FALSE
#define _SUPPORT_DRV_PROT_UV_VDDA FALSE
#define _SUPPORT_DRV_PROT_UV_VS FALSE
#define _SUPPORT_DRV_PROT_OV_VS TRUE
#define _SUPPORT_DRV_PROT_OT FALSE
#define _SUPPORT_OT_PERMANENT_ERROR FALSE
#define _SUPPORT_ADC_BGD FALSE
#define _SUPPORT_ADC_VDDA_VDDD TRUE
#if defined (__MLX81340__) || defined (__MLX81344__) || defined (__MLX81346__)
#define _SUPPORT_ADC_VBOOST TRUE
#else
#define _SUPPORT_ADC_VBOOST FALSE
#endif
#define _SUPPORT_VDDA_VDDD_LPF TRUE
#define C_VDDA_LPF_COEF 1024
#define C_VDDD_LPF_COEF 1024
#define _SUPPORT_LOG_ERRORS TRUE
#define _SUPPORT_DETAIL_ERROR_LOG TRUE
#define _SUPPORT_LOG_LIN_ERRORS FALSE
#define _SUPPORT_LOG_ALL_ERRORS FALSE
#define _SUPPORT_LOG_FATAL_ERRORS FALSE
#define _SUPPORT_NV_LOG_ERROR FALSE
#define _SUPPORT_ACCELERATION C_ACCELERATION_CONSTANT
#define _SUPPORT_ANTICOGGING FALSE
#define _SUPPORT_AUTO_SPEED_FOC TRUE
#define _SUPPORT_BEMF_LEADANGLE_COMPENSATE FALSE
#define _SUPPORT_BEMF_SINUSOIDAL TRUE
#define _SUPPORT_BEMF_STARPOINT FALSE
#define _SUPPORT_BOOST_MODE BOOST_MODE_CLIPPING
#define _SUPPORT_CDI FALSE
#define _SUPPORT_CDI_PID TRUE
#define _SUPPORT_CLOSED_LOOP_STARTUP FALSE
#define _SUPPORT_COIL_TEMP_COMP FALSE
#if (C_TOT_COILS_R <= 250)
#define _SUPPORT_COIL_UNIT_10mR TRUE
#define _SUPPORT_COIL_UNIT_100mR FALSE
#elif (C_TOT_COILS_R <= 2500)
#define _SUPPORT_COIL_UNIT_10mR FALSE
#define _SUPPORT_COIL_UNIT_100mR TRUE
#elif (C_TOT_COILS_R <= 25000)
#define _SUPPORT_COIL_UNIT_10mR FALSE
#define _SUPPORT_COIL_UNIT_100mR FALSE
#else
#error "ERROR: Undefined coil units"
#endif
#define _SUPPORT_CURRENT_TEMP_COMPENSATION FALSE
#define _SUPPORT_DRVSUP_ALWAYS_ENA TRUE
#define _SUPPORT_FOC_MODE FOC_MODE_NONE
#define _SUPPORT_FOC_ID_IQ_MODE FOC_ID_IQ_LUT
#define _SUPPORT_FOC_STALL_A_THRSHLD FALSE
#if (LINPROT == LIN2X_AGS) || (LINPROT == LIN2X_HVAC49) || (LINPROT == LIN2X_HVAC52) || (LINPROT == LIN2X_AIRVENT12) || (LINPROT == LIN22_SIMPLE_PCT) || \
(I2C_SLAVE_PROT == I2C_SLAVE_PROT_POSITIONING) || (_SUPPORT_APP_TYPE == C_APP_POSITIONING_ACT)
#define _SUPPORT_MOTOR_DIRECTION C_MOTOR_DIRECTION_CMD
#define _SUPPORT_MOTOR_POSITION C_MOTOR_POS_ROTOR
#elif (LINPROT == LIN2X_FAN01) || (LINPROT == LIN2X_RELAY) || (LINPROT == LIN2X_SOLENOID) || (I2C_SLAVE_PROT == I2C_SLAVE_PROT_CONTINUOUS) || \
(_SUPPORT_APP_TYPE == C_APP_CONTINUOUS_ACT)
#define _SUPPORT_MOTOR_DIRECTION C_MOTOR_DIRECTION_CMD
#define _SUPPORT_MOTOR_POSITION C_MOTOR_POS_NONE
#else
#error "ERROR: Motor Position type not defined."
#endif
#define _SUPPORT_MOTOR_SELFTEST FALSE
#define _SUPPORT_MOTION_DET C_MOTION_DET_NONE
#if (_SUPPORT_APP_TYPE != C_APP_SOLENOID)
#define _SUPPORT_MULTI_VECTOR_WAVEFORM FALSE
#endif
#if defined (__MLX81160__) || defined (__MLX81330__) || defined (__MLX81339__) || defined (__MLX81350__)
#define _SUPPORT_OSD FALSE
#else
#define _SUPPORT_OSD FALSE
#endif
#define _SUPPORT_PID_D_COEF TRUE
#define _SUPPORT_PID_INLINE FALSE
#define _SUPPORT_PID_SPEED_CURRENT TRUE
#define _SUPPORT_PID_SPEED_LIMIT TRUE
#if defined (C_SPEED_3) && (1UL * C_SPEED_3 * C_MOTOR_POLE_PAIRS) > 65500UL
#define _SUPPORT_PID_U32 TRUE
#else
#define _SUPPORT_PID_U32 FALSE
#endif
#define C_FOC_PID_MULT 2U
#if (C_MOTOR_COILS == 3U)
#define _SUPPORT_PWM_MIRROR TRUE
#if (_SUPPORT_FULLSTEP != FALSE)
#define _SUPPORT_PWM_MODE TRIPLEPHASE_FULL_STEP_BEMF
#else
#define _SUPPORT_PWM_MODE TRIPLEPHASE_TWOPWM_INDEPENDENT_GND
#endif
#elif (C_MOTOR_COILS == 2U) && (C_MOTOR_PHASES == 3U)
#define _SUPPORT_PWM_MODE BIPOLAR_TRIPHASE_ALLPWM_MIRROR
#elif (C_MOTOR_COILS == 2U) && (C_MOTOR_PHASES == 4U)
#if (_SUPPORT_FULLSTEP != FALSE)
#define _SUPPORT_PWM_MODE BIPOLAR_FULL_STEP_BEMF
#elif (_SUPPORT_HALFSTEP != FALSE)
#define _SUPPORT_PWM_MODE BIPOLAR_HALF_STEP_BEMF
#else
#define _SUPPORT_PWM_MODE BIPOLAR_PWM_SINGLE_INDEPENDENT_GND
#endif
#elif (C_MOTOR_COILS == 1U)
#define _SUPPORT_PWM_MODE SINGLE_COIL_PWM
#else
#error "ERROR: Check _SUPPORT_PWM_MODE"
#endif
#define _SUPPORT_PWM_POL_CORR TRUE
#define _SUPPORT_PWM_SPREAD_SPECTRUM FALSE
#if (_SUPPORT_FOC_MODE != FOC_MODE_NONE) || (_SUPPORT_FULLSTEP != FALSE) || (_SUPPORT_HALFSTEP != FALSE) || (_SUPPORT_APP_TYPE == C_APP_SOLENOID)
#define _SUPPORT_PWM_SYNC TRUE
#else
#define _SUPPORT_PWM_SYNC FALSE
#endif
#define PWM_LIMIT PWM_LIMIT_BY_PID
#define _SUPPORT_SOFT_START FALSE
#define _SUPPORT_SPEED_CTRL TRUE
#define _SUPPORT_SRP FALSE
#define _SUPPORT_VARIABLE_PWM FALSE
#define C_VAR_PWM_MODE_OFF 0U
#define C_VAR_PWM_MODE_ON_DUTY_CYCLE 1U
#define C_VAR_PWM_MODE_ON_STARTUP_MODE 2U
#define _SUPPORT_VAR_PWM_MODE C_VAR_PWM_MODE_ON_STARTUP_MODE
#define _SUPPORT_VOLTAGE_CTRL FALSE
#if (_SUPPORT_PWM_MODE == TRIPLEPHASE_ALLPWM_MIRROR) || (_SUPPORT_PWM_MODE == TRIPLEPHASE_TWOPWM_MIRROR_GND) || \
(_SUPPORT_PWM_MODE == BIPOLAR_TRIPHASE_ALLPWM_MIRROR)
#define _SUPPORT_VOLTAGE_SHAPE VOLTAGE_SHAPE_SINE
#elif (_SUPPORT_PWM_MODE == TRIPLEPHASE_TWOPWM_INDEPENDENT_GND) || \
(_SUPPORT_PWM_MODE == BIPOLAR_PWM_SINGLE_INDEPENDENT_GND) || \
(_SUPPORT_PWM_MODE == BIPOLAR_TRIPHASE_TWOPWM_INDEPENDENT_GND)
#define _SUPPORT_VOLTAGE_SHAPE VOLTAGE_SHAPE_DSVM_GND
#elif (_SUPPORT_PWM_MODE == SINGLE_COIL_PWM_BIPOLAR)
#define _SUPPORT_VOLTAGE_SHAPE VOLTAGE_SHAPE_SINE
#elif (_SUPPORT_PWM_MODE == SINGLE_COIL_PWM) || (_SUPPORT_PWM_MODE == TRIPLEPHASE_FULL_STEP_BEMF) || (_SUPPORT_PWM_MODE == BIPOLAR_FULL_STEP_BEMF) || (_SUPPORT_PWM_MODE == BIPOLAR_HALF_STEP_BEMF) || (_SUPPORT_PWM_MODE == TRIPLEPHASE_FULL_STEP)
#define _SUPPORT_VOLTAGE_SHAPE VOLTAGE_SHAPE_NONE
#else
#error "ERROR: Check _SUPPORT_VOLTAGE_SHAPE"
#endif
#define _SUPPORT_WINDMILL FALSE
#define _SUPPORT_WINDMILL_FOC FALSE
#define _SUPPORT_TRIAXIS_MLX90363 FALSE
#define _SUPPORT_TRIAXIS_MLX90363_XYZ FALSE
#define _SUPPORT_TRIAXIS_MLX90367 FALSE
#define _SUPPORT_TRIAXIS_MLX90372 FALSE
#define _SUPPORT_TRIAXIS_MLX90377 FALSE
#if defined (__MLX81332_w90381__) || defined (__MLX81340_w90381__) || ((_SUPPORT_FOC_MODE & FOC_OBSERVER_MASK) == FOC_OBSERVER_SENSORED)
#define _SUPPORT_TRIAXIS_MLX9038x TRUE
#else
#define _SUPPORT_TRIAXIS_MLX9038x FALSE
#endif
#define _SUPPORT_TRIAXIS_MLX90395 FALSE
#define _SUPPORT_TRIAXIS_MLX90421 FALSE
#define _SUPPORT_TRIAXIS_MLX90422 FALSE
#define _SUPPORT_TRIAXIS_MLX90425 FALSE
#define _SUPPORT_TRIAXIS_MLX90426 FALSE
#define _SUPPORT_TRIAXIS_MLX90427 FALSE
#define _SUPPORT_HUMIDITY_HDC302x FALSE
#define _SUPPORT_INDUCTIVE_POS_SENSOR_MLX90513 FALSE
#define _SUPPORT_PRESSURE_MLX90829 FALSE
#if defined (__MLX81332_w90381__)
#define _SUPPORT_RESOLVER_X_IO PIN_FUNC_IO_2
#define _SUPPORT_RESOLVER_Y_IO PIN_FUNC_IO_3
#define _SUPPORT_RESOLVER_TEST_IO PIN_FUNC_IO_NONE
#elif defined (__MLX81340_w90381__)
#define _SUPPORT_RESOLVER_X_IO PIN_FUNC_IO_10
#define _SUPPORT_RESOLVER_Y_IO PIN_FUNC_IO_11
#define _SUPPORT_RESOLVER_TEST_IO PIN_FUNC_IO_5
#else
#define _SUPPORT_RESOLVER_X_IO PIN_FUNC_IO_2
#define _SUPPORT_RESOLVER_Y_IO PIN_FUNC_IO_3
#define _SUPPORT_RESOLVER_TEST_IO PIN_FUNC_IO_NONE
#endif
#define _SUPPORT_RESOLVER2_X_IO PIN_FUNC_IO_NONE
#define _SUPPORT_RESOLVER2_Y_IO PIN_FUNC_IO_NONE
#define _SUPPORT_SENSOR_PWM_IO PIN_FUNC_IO_0
#define _SUPPORT_SENSOR_SENT_IO PIN_FUNC_IO_0
#define _SUPPORT_SENT_LEGACY_CRC FALSE
#if (_SUPPORT_TRIAXIS_MLX90367 != FALSE) || (_SUPPORT_TRIAXIS_MLX90372 != FALSE) || \
(_SUPPORT_TRIAXIS_MLX90377 != FALSE) || \
(_SUPPORT_TRIAXIS_MLX90421 != FALSE) || (_SUPPORT_TRIAXIS_MLX90422 != FALSE) || \
(_SUPPORT_TRIAXIS_MLX90425 != FALSE) || (_SUPPORT_TRIAXIS_MLX90426 != FALSE) || \
(_SUPPORT_INDUCTIVE_POS_SENSOR_MLX90513 != FALSE)
#define _SUPPORT_SENSOR_VDDA_5V TRUE
#else
#define _SUPPORT_SENSOR_VDDA_5V FALSE
#endif
#define _SUPPORT_TRIAXIS_DETAILS FALSE
#define _SUPPORT_TRIAXIS_MISMATCH FALSE
#define _SUPPORT_TRIAXIS_STANDBY FALSE
#define _SUPPORT_DUAL_HALL_LATCH_MLX92251 FALSE
#define _SUPPORT_DUAL_HALL_LATCH_MLX92255 FALSE
#define _SUPPORT_HALL_LATCH FALSE
#define _SUPPORT_HALL_LATCH_DIAG FALSE
#define _SUPPORT_HALL_LATCH_MLX9227x FALSE
#define _SUPPORT_HALL_SWITCH_MLX9229x FALSE
#if (_SUPPORT_HALL_LATCH != FALSE)
#define _SUPPORT_NR_OF_HL 3U
#define _SUPPORT_HLA_IO PIN_FUNC_IO_1
#if (_SUPPORT_NR_OF_HL >= 2)
#define _SUPPORT_HLB_IO PIN_FUNC_IO_2
#if (_SUPPORT_NR_OF_HL >= 3)
#define _SUPPORT_HLC_IO PIN_FUNC_IO_3
#endif
#endif
#define _SUPPORT_HALL_POSLOST FALSE
#if (_SUPPORT_FULLSTEP != FALSE)
#define _SUPPORT_MICRO_STEP_COMMUTATION FALSE
#else
#define _SUPPORT_MICRO_STEP_COMMUTATION TRUE
#endif
#define _SUPPORT_HALL_LATCH_LEADANGLE_COMP TRUE
#define _SUPPORT_HALL_LATCH_POLARITY TRUE
#define _SUPPORT_HALL_LATCH_POS FALSE
#define _SUPPORT_HALL_LATCH_SMOOTHING FALSE
#define _SUPPORT_HALL_LATCH_SWITCH_MODE C_3HL_SWITCH_MODE_ALT2_EDGE
#endif
#if !defined (C_SENSE_MAGNET_POLE_PAIRS)
#if (_SUPPORT_TRIAXIS_MLX90363 != FALSE) || \
(_SUPPORT_TRIAXIS_MLX90367 != FALSE) || (_SUPPORT_TRIAXIS_MLX90372 != FALSE) || \
(_SUPPORT_TRIAXIS_MLX90377 != FALSE) || \
(_SUPPORT_TRIAXIS_MLX9038x != FALSE) || \
(_SUPPORT_TRIAXIS_MLX90395 != FALSE) || \
(_SUPPORT_TRIAXIS_MLX90421 != FALSE) || \
(_SUPPORT_TRIAXIS_MLX90422 != FALSE) || \
(_SUPPORT_TRIAXIS_MLX90425 != FALSE) || \
(_SUPPORT_TRIAXIS_MLX90426 != FALSE) || \
(_SUPPORT_TRIAXIS_MLX90427 != FALSE) || \
(_SUPPORT_DUAL_HALL_LATCH_MLX92251 != FALSE) || (_SUPPORT_DUAL_HALL_LATCH_MLX92255 != FALSE)
#define C_SENSE_MAGNET_POLE_PAIRS 1U
#endif
#endif
#define _SUPPORT_NTC FALSE
#define _SUPPORT_NTC_IO PIN_FUNC_IO_3
#define _SUPPORT_POTI FALSE
#define C_POTI_MODE_NONE 0U
#define C_POTI_MODE_OPEN_LOOP 1U
#define C_POTI_MODE_CLOSED_LOOP 2U
#define _SUPPORT_POTI_MODE C_POTI_MODE_OPEN_LOOP
#define _SUPPORT_POTI_IO PIN_FUNC_IO_3
#define C_POTI_CCW FALSE
#define C_POS_TRAVEL 1024U
#define _SUPPORT_CURRSPIKE_POSITION FALSE
#if (_SUPPORT_CURRSPIKE_POSITION != FALSE)
#define C_SPIKE_TYPE_POS_NEG 0U
#define C_SPIKE_TYPE_NEG 1U
#define _SUPPORT_SPIKE_TYPE C_SPIKE_TYPE_NEG
#define C_EDGE_SPIKE_SKIP 3U
#endif
#define _SUPPORT_REWIND FALSE
#define _SUPPORT_STALL_REVERSE TRUE
#define _SUPPORT_STALLDET_A TRUE
#define C_STALL_THRSHLD_DYN 1U
#define C_STALL_THRSHLD_STC 2U
#define _SUPPORT_STALLDET_A_MODE C_STALL_THRSHLD_STC
#if ((_SUPPORT_PWM_MODE == TRIPLEPHASE_FULL_STEP_BEMF) || (_SUPPORT_PWM_MODE == BIPOLAR_FULL_STEP_BEMF) || (_SUPPORT_PWM_MODE == BIPOLAR_HALF_STEP_BEMF)) && (_SUPPORT_MOTOR_POSITION != C_MOTOR_POS_NONE)
#define _SUPPORT_STALLDET_BRI TRUE
#define _SUPPORT_STALLDET_BZC FALSE
#elif (_SUPPORT_PWM_MODE == TRIPLEPHASE_FULL_STEP_BEMF) && (_SUPPORT_MOTOR_POSITION == C_MOTOR_POS_NONE)
#define _SUPPORT_STALLDET_BRI FALSE
#define _SUPPORT_STALLDET_BZC TRUE
#else
#define _SUPPORT_STALLDET_BRI FALSE
#define _SUPPORT_STALLDET_BZC FALSE
#endif
#if (_SUPPORT_HALL_LATCH != FALSE)
#define _SUPPORT_STALLDET_H TRUE
#else
#define _SUPPORT_STALLDET_H FALSE
#endif
#if (_SUPPORT_PWM_MODE != TRIPLEPHASE_FULL_STEP_BEMF) && (_SUPPORT_PWM_MODE != TRIPLEPHASE_FULL_STEP) && (_SUPPORT_TRIAXIS_MLX9038x == FALSE) && (C_MOTOR_COILS != 1U)
#define _SUPPORT_STALLDET_O FALSE
#else
#define _SUPPORT_STALLDET_O FALSE
#endif
#define _SUPPORT_STALLDET_O_SPEED1 FALSE
#define _SUPPORT_STALLDET_O_SPEED2 FALSE
#define _SUPPORT_STALLDET_O_SPEED3 FALSE
#define _SUPPORT_STALLDET_P FALSE
#if ((_SUPPORT_FOC_MODE & FOC_MODE_MASK) != FOC_MODE_NONE)
#define _SUPPORT_STALLDET_S TRUE
#if ((_SUPPORT_FOC_MODE & FOC_MODE_MASK) == FOC_MODE_IB) || ((_SUPPORT_FOC_MODE & FOC_MODE_MASK) == FOC_MODE_IB_IPK)
#define _SUPPORT_STALLDET_LA TRUE
#else
#define _SUPPORT_STALLDET_LA FALSE
#endif
#if ((_SUPPORT_FOC_MODE & FOC_MODE_MASK) == FOC_MODE_ID_IQ)
#define _SUPPORT_STALLDET_FLUX TRUE
#else
#define _SUPPORT_STALLDET_FLUX FALSE
#endif
#else
#define _SUPPORT_STALLDET_S FALSE
#define _SUPPORT_STALLDET_LA TRUE
#define _SUPPORT_STALLDET_FLUX FALSE
#endif
#define C_THRSHLD_CONST 1U
#define C_THRSHLD_SPEED 2U
#define C_THRSHLD_SPEED_W_OFFSET 3U
#define _SUPPORT_STALLDET_LA_MODE C_THRSHLD_SPEED
#define _SUPPORT_IGNORE_ENDSTOP_STALL TRUE
#if (PWM_COMM != FALSE)
#define _SUPPORT_STALL_AUTO_CLEAR TRUE
#else
#define _SUPPORT_STALL_AUTO_CLEAR FALSE
#endif
#define _SUPPORT_STALLDET_LPF TRUE
#define _SUPPORT_STALLDET_MOVAVG_FLTR FALSE
#define _SUPPORT_EVB MLX8133xEVB
#define _SUPPORT_EVB_APP MLX813xxEVB_APP
#if defined (__MLX81160__) || defined (__MLX81340__) || defined (__MLX81344__) || defined (__MLX81346__)
#if (_SUPPORT_EVB == MLX8134xEVB_100W)
#define _SUPPORT_RSHUNT C_RSHUNT_R010
#elif (_SUPPORT_EVB == MLX81346EVB_200W)
#define _SUPPORT_RSHUNT C_RSHUNT_R020
#elif (_SUPPORT_EVB == MLX8134xEVB_400W)
#define _SUPPORT_RSHUNT C_RSHUNT_R003
#elif (_SUPPORT_EVB == MLX81346EVB_600W)
#define _SUPPORT_RSHUNT C_RSHUNT_R005
#elif (_SUPPORT_EVB == MLX81346EVB_ITFAN)
#define _SUPPORT_RSHUNT C_RSHUNT_R050
#else
#define _SUPPORT_RSHUNT C_RSHUNT_R100
#endif
#if (_SUPPORT_RSHUNT == C_RSHUNT_R500)
#define C_ONE_DIV_RSHUNT 2U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R330)
#define C_ONE_DIV_RSHUNT 3U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R250)
#define C_ONE_DIV_RSHUNT 4U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R200)
#define C_ONE_DIV_RSHUNT 5U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R100)
#define C_ONE_DIV_RSHUNT 10U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R050)
#define C_ONE_DIV_RSHUNT 20U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R033)
#define C_ONE_DIV_RSHUNT 30U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R025)
#define C_ONE_DIV_RSHUNT 40U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R022)
#define C_ONE_DIV_RSHUNT 46U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R020)
#define C_ONE_DIV_RSHUNT 50U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R010)
#define C_ONE_DIV_RSHUNT 100U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R005)
#define C_ONE_DIV_RSHUNT 200U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R004)
#define C_ONE_DIV_RSHUNT 250U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R003)
#define C_ONE_DIV_RSHUNT 333U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R002)
#define C_ONE_DIV_RSHUNT 500U
#elif (_SUPPORT_RSHUNT == C_RSHUNT_R001)
#define C_ONE_DIV_RSHUNT 1000U
#else
#error "Unimplemented Rshunt"
#endif
#if defined(C_PID_RUNNING_CURR_LEVEL) && ( (1UL * C_PID_RUNNING_CURR_LEVEL * _SUPPORT_RSHUNT) > 148000UL)
#error "ERROR: Motor running current or Shunt too large!"
#elif defined(C_PID_RUNNING_CURR_MAX) && ( (1UL * C_PID_RUNNING_CURR_MAX * _SUPPORT_RSHUNT) > 148000UL)
#error "ERROR: Motor running current or Shunt too large!"
#endif
#endif
#if (ANA_COMM != FALSE)
#define C_ANA_IO PIN_FUNC_IO_4
#endif
#if (CAN_COMM != FALSE)
#define _SUPPORT_CAN_MCP2515 FALSE
#define _SUPPORT_CAN_TCAN4550 FALSE
#if (_SUPPORT_CAN_MCP2515 != FALSE)
#define MCP2515_OSC 8000000U
#define TQ 8
#elif (_SUPPORT_CAN_TCAN4550 != FALSE)
#define TCAN4550_OSC 40000000U
#define TCAN4550_AUTO_RETRANSMIT FALSE
#define TCAN4550_FD FALSE
#define TCAN4550_WD FALSE
#define TQ 10
#endif
#define _SUPPORT_CAN_IRQ_IO PIN_FUNC_IO_NONE
#define _SUPPORT_CAN_STDBY_IO PIN_FUNC_IO_NONE
#define _SUPPORT_CAN_RST_IO PIN_FUNC_IO_NONE
#endif
#if (I2C_MASTER_PROT != I2C_MASTER_PROT_NONE) || (I2C_SLAVE_PROT != I2C_SLAVE_PROT_NONE)
#define _SUPPORT_I2C TRUE
#else
#define _SUPPORT_I2C FALSE
#endif
#if (_SUPPORT_I2C != FALSE) && (I2C_MASTER_PROT != I2C_MASTER_PROT_NONE)
#define _SUPPORT_I2C_MASTER TRUE
#else
#define _SUPPORT_I2C_MASTER FALSE
#endif
#if (_SUPPORT_I2C != FALSE) && (I2C_SLAVE_PROT != I2C_SLAVE_PROT_NONE)
#define _SUPPORT_I2C_SLAVE TRUE
#else
#define _SUPPORT_I2C_SLAVE FALSE
#endif
#if (_SUPPORT_I2C != FALSE)
#define _SUPPORT_I2C_ERR_ISR FALSE
#define _SUPPORT_I2C_MSTR_ISR FALSE
#define _SUPPORT_I2C_RESET_ISR FALSE
#define _SUPPORT_I2C_RW_ISR FALSE
#define _SUPPORT_I2C_MSBitFirst TRUE
#define _SUPPORT_I2C_BYTE_SWAP TRUE
#else
#define _SUPPORT_I2C_ERR FALSE
#define _SUPPORT_I2C_ISR FALSE
#endif
#if (_SUPPORT_I2C_MASTER != FALSE)
#if (_SUPPORT_TRIAXIS_MLX9038x != FALSE)
#define C_I2C_MASTER_SCK_IO _SUPPORT_RESOLVER_X_IO
#define C_I2C_MASTER_SDA_IO _SUPPORT_RESOLVER_Y_IO
#else
#define C_I2C_MASTER_SCK_IO PIN_FUNC_IO_3
#define C_I2C_MASTER_SDA_IO PIN_FUNC_IO_7
#endif
#define _SUPPORT_I2C_MASTER_HW_RESOURCE C_I2C_MASTER_CTIMER1
#else
#define _SUPPORT_I2C_MASTER_HW_RESOURCE C_I2C_MASTER_NONE
#endif
#if (_SUPPORT_I2C_SLAVE != FALSE)
#if (CHIP_PACKAGE == SO8)
#if defined (__MLX81339__)
#define C_I2C_SLAVE_SCK_IO PIN_FUNC_COMM
#else
#define C_I2C_SLAVE_SCK_IO PIN_FUNC_LIN
#endif
#else
#define C_I2C_SLAVE_SCK_IO PIN_FUNC_IO_1
#endif
#define C_I2C_SLAVE_SDA_IO PIN_FUNC_IO_0
#endif
#define _SUPPORT_IO_DUT_SELECT_HVIO FALSE
#define _SUPPORT_IO_DUT_SELECT_PWR FALSE
#define _SUPPORT_IO_CMD_SELECT_LVIO FALSE
#if (_SUPPORT_IO_DUT_SELECT_HVIO != FALSE)
#define HVIO_DUT_SELECT PIN_FUNC_IO_0
#endif
#if (_SUPPORT_IO_DUT_SELECT_PWR != FALSE) || (_SUPPORT_IO_CMD_SELECT_LVIO != FALSE)
#define _SUPPORT_NR_OF_IO_SELECT 3U
#define IO_DUT_SELECT_A PIN_FUNC_IO_1
#if (_SUPPORT_NR_OF_IO_SELECT >= 2U)
#define IO_DUT_SELECT_B PIN_FUNC_IO_2
#if (_SUPPORT_NR_OF_IO_SELECT >= 3U)
#define IO_DUT_SELECT_C PIN_FUNC_IO_3
#endif
#endif
#endif
#if (PWM_COMM != FALSE)
#define C_PWM_COMM_IN PIN_FUNC_LIN
#define C_PWM_COMM_OUT PIN_FUNC_IO_NONE
#define _SUPPORT_PWM_COMM_ISR C_PWM_COMM_CTIMER1
#define _SUPPORT_PWMCOMM_STALL TRUE
#endif
#if (_SUPPORT_TRIAXIS_MLX90421 != FALSE) || (_SUPPORT_TRIAXIS_MLX90425 != FALSE)
#define _SUPPORT_PWM_HW_RESOURCE C_PWM_HW_RES_CTIMER1
#else
#define _SUPPORT_PWM_HW_RESOURCE C_PWM_HW_RES_NONE
#endif
#if (_SUPPORT_SENSOR_SENT_IO == PIN_FUNC_IO_NONE)
#define _SUPPORT_SENT_HW_RESOURCE C_SENT_NONE
#else
#define _SUPPORT_SENT_HW_RESOURCE C_SENT_PPM
#endif
#if (_APP_DMA_STRESS_TEST != FALSE) || (_APP_ZWICKAU != FALSE) || \
((CAN_COMM != FALSE) && ((_SUPPORT_CAN_MCP2515 != FALSE) || (_SUPPORT_CAN_TCAN4550 != FALSE))) || \
(SPI_COMM != FALSE) || \
(_SUPPORT_TRIAXIS_MLX90363 != FALSE) || (_SUPPORT_TRIAXIS_MLX90395 != FALSE) || (_SUPPORT_TRIAXIS_MLX90427 != FALSE)
#define _SUPPORT_SPI TRUE
#else
#define _SUPPORT_SPI FALSE
#endif
#define _SUPPORT_3WIRE_SPI FALSE
#if (_SUPPORT_SPI != FALSE) || (_SUPPORT_3WIRE_SPI != FALSE)
#if (PLL_FREQ == 32000000UL)
#define C_SPI_BAUDRATE 200000U
#else
#define C_SPI_BAUDRATE 200000U
#endif
#if (CAN_COMM && (_SUPPORT_CAN_MCP2515 || _SUPPORT_CAN_TCAN4550))
#define _SUPPORT_SPI_CPHA FALSE
#else
#define _SUPPORT_SPI_CPHA TRUE
#endif
#if (_APP_DMA_STRESS_TEST != FALSE) || (SPI_COMM != FALSE)
#define _SUPPORT_SPI_DMA TRUE
#else
#define _SUPPORT_SPI_DMA FALSE
#endif
#if ((CAN_COMM != FALSE) && ((_SUPPORT_CAN_MCP2515 != FALSE) || (_SUPPORT_CAN_TCAN4550 != FALSE)))
#define _SUPPORT_SPI_DUPLEX C_SPI_HALF_DUPLEX
#else
#define _SUPPORT_SPI_DUPLEX C_SPI_FULL_DUPLEX
#endif
#define _SUPPORT_SPI_MASTER TRUE
#define _SUPPORT_SPI_WORD_SIZE SPI_WORD_8BITS
#define _SUPPORT_SPI_MOSI_IO PIN_FUNC_IO_3
#define _SUPPORT_SPI_MISO_IO PIN_FUNC_IO_4
#define _SUPPORT_SPI_CLK PIN_FUNC_IO_2
#define _SUPPORT_SPI_SS PIN_FUNC_IO_1
#if (_SUPPORT_TRIAXIS_MLX90363 != FALSE) || (_SUPPORT_TRIAXIS_MLX90395 != FALSE) || (_SUPPORT_TRIAXIS_MLX90427 != FALSE) || (CAN_COMM != FALSE)
#define _SUPPORT_SPI_SS_SOFT TRUE
#else
#define _SUPPORT_SPI_SS_SOFT FALSE
#endif
#if (_APP_ZWICKAU != FALSE) || (SPI_COMM != FALSE)
#define _SUPPORT_SPI_ISR TRUE
#else
#define _SUPPORT_SPI_ISR FALSE
#endif
#define SPI_2WIRE_IO SPI_2WIRE_IO0_1
#else
#define _SUPPORT_SPI_ISR FALSE
#endif
#if !defined (__MLX81330__)
#if (_APP_DMA_STRESS_TEST != FALSE) || (UART_COMM != FALSE)
#define _SUPPORT_UART TRUE
#else
#define _SUPPORT_UART FALSE
#endif
#if (_SUPPORT_UART != FALSE)
#define _SUPPORT_UART_RX_IO PIN_FUNC_IO_4
#define _SUPPORT_UART_TX_IO PIN_FUNC_IO_5
#define _SUPPORT_UART_LSbitFirst TRUE
#define _SUPPORT_UART_LSByteFirst TRUE
#if (_SUPPORT_UART_IF_APP == C_UART_IF_BLUETOOTH) || (_SUPPORT_UART_IF_APP == C_UART_IF_TERMINAL) || (_SUPPORT_UART_IF_APP == C_UART_IF_MLX_ACT)
#define _SUPPORT_UART_DMA TRUE
#define _SUPPORT_UART_DMA_VAR_LEN TRUE
#else
#define _SUPPORT_UART_DMA TRUE
#define _SUPPORT_UART_DMA_VAR_LEN FALSE
#endif
#define _SUPPORT_UART_ISR TRUE
#if (_SUPPORT_UART_IF_APP == C_UART_IF_SCOPE)
#if (PLL_FREQ == 32000000UL)
#define C_UART_BAUDRATE 1000000U
#elif (PLL_FREQ == 29500000UL)
#define C_UART_BAUDRATE 921600U
#else
#define C_UART_BAUDRATE 115200U
#endif
#elif (_SUPPORT_UART_IF_APP == C_UART_IF_QUAD_WHEEL_CAR)
#if (PLL_FREQ == 32000000UL)
#define C_UART_BAUDRATE 1000000U
#elif (PLL_FREQ == 29500000UL)
#define C_UART_BAUDRATE 921600U
#else
#define C_UART_BAUDRATE 115200U
#endif
#elif (_SUPPORT_UART_IF_APP == C_UART_IF_BLUETOOTH)
#define C_UART_BAUDRATE 9600U
#elif (_SUPPORT_UART_IF_APP == C_UART_IF_TERMINAL)
#define C_UART_BAUDRATE 115200U
#else
#define C_UART_BAUDRATE 115200U
#endif
#else
#define _SUPPORT_UART_ISR FALSE
#endif
#else
#define _SUPPORT_UART FALSE
#endif
#if defined (__MLX81330__) || defined (__MLX81332__) || defined (__MLX81334__)
#if (PLL_FREQ == 40000000UL)
#if (_APP_DMA_STRESS_TEST != FALSE)
#define ADC_FREQ 8000000UL
#else
#if (_SUPPORT_TRIAXIS_MLX9038x != FALSE)
#define ADC_FREQ 5714285UL
#else
#define ADC_FREQ 4000000UL
#endif
#endif
#elif (PLL_FREQ == 32000000UL)
#if (_APP_DMA_STRESS_TEST != FALSE)
#define ADC_FREQ 8000000UL
#else
#if (_SUPPORT_TRIAXIS_MLX9038x != FALSE)
#define ADC_FREQ 5333333UL
#else
#define ADC_FREQ 4000000UL
#endif
#endif
#elif (PLL_FREQ == 29500000UL)
#if (_APP_DMA_STRESS_TEST != FALSE)
#define ADC_FREQ 7375000UL
#else
#if (_SUPPORT_TRIAXIS_MLX9038x != FALSE)
#define ADC_FREQ 5900000UL
#else
#define ADC_FREQ 4214286UL
#endif
#endif
#elif (PLL_FREQ == 28000000UL)
#if (_APP_DMA_STRESS_TEST != FALSE)
#define ADC_FREQ 7000000UL
#else
#if (_SUPPORT_TRIAXIS_MLX9038x != FALSE)
#define ADC_FREQ 5600000UL
#else
#define ADC_FREQ 4000000UL
#endif
#endif
#elif (PLL_FREQ == 24000000UL)
#if (_APP_DMA_STRESS_TEST != FALSE)
#define ADC_FREQ 8000000UL
#else
#if (_SUPPORT_TRIAXIS_MLX9038x != FALSE)
#define ADC_FREQ 6000000UL
#else
#define ADC_FREQ 4000000UL
#endif
#endif
#else
#define ADC_FREQ 4000000UL
#endif
#elif defined (__MLX81160__) || defined (__MLX81339__) || defined (__MLX81340__) || defined (__MLX81344__) || defined (__MLX81346__) || defined (__MLX81350__)
#if (PLL_FREQ == 48000000UL)
#define ADC_FREQ (PLL_FREQ / 3)
#elif (PLL_FREQ == 40000000UL)
#define ADC_FREQ (PLL_FREQ / 2)
#elif (PLL_FREQ == 36000000UL)
#define ADC_FREQ (PLL_FREQ / 2)
#elif (PLL_FREQ == 32000000UL)
#define ADC_FREQ (PLL_FREQ / 2)
#elif (PLL_FREQ == 29500000UL)
#define ADC_FREQ (PLL_FREQ / 2)
#elif (PLL_FREQ == 28000000UL)
#define ADC_FREQ (PLL_FREQ / 2)
#elif (PLL_FREQ == 24000000UL)
#define ADC_FREQ (PLL_FREQ / 2)
#elif (PLL_FREQ <= 20000000UL)
#define ADC_FREQ (PLL_FREQ / 1)
#endif
#endif
#if (_SUPPORT_TRIAXIS_MLX90377 != FALSE) && (_SUPPORT_SENSOR_SENT_IO != PIN_FUNC_IO_NONE) && (_SUPPORT_SSCM != FALSE)
#error "ERROR: SPC/SENT with 1.5us Tick-time doesn't work well with SSCM enabled"
#endif
#if (_SUPPORT_VARIABLE_PWM != FALSE) && (_SUPPORT_VOLTAGE_SHAPE != VOLTAGE_SHAPE_DSVM_GND)
#error "ERROR: Variable PWM (0-33-67) only supported using SVM-L"
#endif
#if (_SUPPORT_FOC_ID_IQ_MODE == FOC_ID_IQ_iCLARKE) && (_SUPPORT_VOLTAGE_SHAPE != VOLTAGE_SHAPE_DSVM_GND)
#error "ERROR: Inverse Clarke (Cartesian) only supported with SVM-L"
#endif
#endif