#ifndef _LIB_VERSION_
#define _LIB_VERSION_
#define __LIB_VERSION_MAJOR__ 1UL
#define __LIB_VERSION_MINOR__ 0UL
#define __LIB_VERSION_REVISION__ 0xA022UL
#define __LIB_VERSION_STRING__ "1.0.A022"
#endif
