#ifndef DRIVE_LIB_MOTOR_DRIVERTABLES_H
#define DRIVE_LIB_MOTOR_DRIVERTABLES_H
#include "AppBuild.h"
#define SZ_MICRO_VECTOR_TABLE_3PH ((5U * (6U * C_MICROSTEP_PER_FULLSTEP)) / 3U)
#define SZ_MICRO_VECTOR_TABLE_4PH (5U * C_MICROSTEP_PER_FULLSTEP)
#define SZ_MICRO_VECTOR_TABLE_3PH_2COIL (6U * C_MICROSTEP_PER_FULLSTEP)
#define SPACE_VECTOR_SINE TRUE
#define SPACE_VECTOR_TRIPLE_SINE FALSE
#define SPACE_VECTOR_FIFTH_SINE FALSE
#define SPACE_VECTOR_TRAPIZE FALSE
#define SPACE_VECTOR_BLOCK FALSE
extern int16_t const c_ai16MicroStepVector4PH[SZ_MICRO_VECTOR_TABLE_4PH];
extern uint16_t const c_au16MicroStepVector3PH[SZ_MICRO_VECTOR_TABLE_3PH + C_MICROSTEP_PER_FULLSTEP];
extern int16_t const c_ai16MicroStepVector3PH_SinCos256[256U + 64U];
#define C_COS_OFFSET (256U / 4U)
extern uint16_t const c_au16DrvCfg[C_MOTOR_PHASES * C_MOTOR_STEP_PER_PHASE];
#endif
