#ifndef DRIVE_LIB_TIMER_H
#define DRIVE_LIB_TIMER_H
#include "AppBuild.h"
#include "hal_lib/hal_STimer.h"
#define CT_PERIODIC_RATE 500U
#define CT_1MHz_PERIODIC_RATE CT_PERIODIC_RATE
#define PI_TICKS_PER_MINUTE (60000000UL / CT_PERIODIC_RATE)
#define PI_TICKS_PER_SECOND (1000000UL / CT_PERIODIC_RATE)
#define PI_TICKS_PER_HALF_SECOND (500000UL / CT_PERIODIC_RATE)
#define PI_TICKS_PER_MILLISECOND (1000U / CT_PERIODIC_RATE)
#define C_PI_TICKS_10MS (10U * PI_TICKS_PER_MILLISECOND)
#define C_PI_TICKS_20MS (20U * PI_TICKS_PER_MILLISECOND)
#define C_PI_TICKS_25MS (25U * PI_TICKS_PER_MILLISECOND)
#define C_PI_TICKS_50MS (50U * PI_TICKS_PER_MILLISECOND)
#define C_PI_TICKS_100MS (100U * PI_TICKS_PER_MILLISECOND)
#define C_PI_TICKS_125MS (125U * PI_TICKS_PER_MILLISECOND)
#define C_PI_TICKS_250MS (250U * PI_TICKS_PER_MILLISECOND)
#define C_PI_TICKS_500MS (500U * PI_TICKS_PER_MILLISECOND)
#define C_PI_TICKS_PWM_INACTIVE (4U * PI_TICKS_PER_SECOND)
#define C_PI_TICKS_MOTOR_RESTART (250U * PI_TICKS_PER_MILLISECOND)
#define C_PI_TICKS_MOTOR_RAMPDOWN (1U * PI_TICKS_PER_SECOND)
#define C_MOTOR_START_DELAY_50MSEC (50U * PI_TICKS_PER_MILLISECOND)
#define C_MOTOR_START_DELAY_100MSEC (100U * PI_TICKS_PER_MILLISECOND)
#define C_MOTOR_START_DELAY_250MSEC (250U * PI_TICKS_PER_MILLISECOND)
#define C_MOTOR_START_DELAY_500MSEC (500U * PI_TICKS_PER_MILLISECOND)
#define C_MOTOR_START_DELAY_1SEC (1U * PI_TICKS_PER_SECOND)
#define C_MOTOR_START_DELAY_2SEC (2U * PI_TICKS_PER_SECOND)
#define C_MOTOR_START_DELAY_3SEC (3U * PI_TICKS_PER_SECOND)
#define C_MOTOR_START_DELAY_4SEC (4U * PI_TICKS_PER_SECOND)
#define C_MOTOR_START_DELAY_5SEC (5U * PI_TICKS_PER_SECOND)
#define C_MOTOR_START_DELAY_7SEC (7U * PI_TICKS_PER_SECOND)
#define C_MOTOR_START_DELAY_10SEC (10U * PI_TICKS_PER_SECOND)
#pragma space dp
#pragma space none
#pragma space nodp
#pragma space none
extern void TimerInit(void);
extern void TimerStop(void);
extern uint16_t TimerCheck(void);
extern void TimerSleepCompensation(uint16_t u16SleepCompensationPeriod);
#endif
