/**
 * @file
 * @brief IO port inline function definitions
 * @internal
 *
 * @copyright (C) 2020 Melexis N.V.
 * git flash d0014c23
 *
 * Melexis N.V. is supplying this code for use with Melexis N.V. processor based microcontrollers only.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
 * INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.  MELEXIS N.V. SHALL NOT IN ANY CIRCUMSTANCES,
 * BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * @endinternal
 *
 * @details provides io.h inline implementations.
 * This file was autogenerated. The information of the source is described below:
 * Tag: DIG81160_RC_1_0_32_20200725_164352
 */

#ifndef IO_INLINE_IMPL_H
#define IO_INLINE_IMPL_H

#include <stdint.h>
#include "compiler_abstraction.h"

STATIC INLINE uint16_t IO_AWD__ACK_GET (void)
{
    register uint16_t result;
    asm volatile (
        "mov c, io:0xe.6\n\t"
#if defined (__GCC_ASM_FLAG_OUTPUTS__)
        : "=@ccc" (result));
#else
        "sc %[acc]\n\t"
        : [acc] "=r" (result));
#endif
    return result;
}

STATIC INLINE uint16_t IO_AWD__WIN_OPEN_GET (void)
{
    register uint16_t result;
    asm volatile (
        "mov c, io:0xf.7\n\t"
#if defined (__GCC_ASM_FLAG_OUTPUTS__)
        : "=@ccc" (result));
#else
        "sc %[acc]\n\t"
        : [acc] "=r" (result));
#endif
    return result;
}

#endif /* IO_INLINE_IMPL_H */
