/**
 * @file
 * @brief Interrupt vector table
 * @internal
 *
 * @copyright (C) 2015-2020 Melexis N.V.
 * git flash d0014c23
 *
 * Melexis N.V. is supplying this code for use with Melexis N.V. processor based microcontrollers only.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
 * INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.  MELEXIS N.V. SHALL NOT IN ANY CIRCUMSTANCES,
 * BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * @endinternal
 *
 * @details
 * This file was autogenerated. The information of the source is described below:
 * Tag: DIG81160_RC_1_0_32_20200725_164352
 */

#ifndef MEMORY_MAP_VECTORS_H
#define MEMORY_MAP_VECTORS_H

/** Size of flash interrupt vectors */
#define MEM_FLASH_VECTORS_SIZE      (0x2d0)

/** Offset in interrupt vector table for FLASH_KEY */
#define MEM_FLASH_OFFSET_FW_FLASH_KEY                 (0x6)
/** Offset in interrupt vector table for BIST_PAGE_COUNT */
#define MEM_FLASH_OFFSET_FW_FLASH_BIST_PAGES_COUNT    (0x26)

/** Offset in interrupt vector table for MLX16_RESET */
#define MEM_FLASH_VECTOR_OFFSET_MLX16_RESET           (0x0)
/** Offset in interrupt vector table for MLX16_STACKERR */
#define MEM_FLASH_VECTOR_OFFSET_MLX16_STACKERR        (0x8)
/** Offset in interrupt vector table for MLX16_PROTERR */
#define MEM_FLASH_VECTOR_OFFSET_MLX16_PROTERR         (0x10)
/** Offset in interrupt vector table for MLX16_MEMERR */
#define MEM_FLASH_VECTOR_OFFSET_MLX16_MEMERR          (0x18)
/** Offset in interrupt vector table for MLX16_OPERR */
#define MEM_FLASH_VECTOR_OFFSET_MLX16_OPERR           (0x20)
/** Offset in interrupt vector table for unused_5 */
#define MEM_FLASH_VECTOR_OFFSET_UNUSED_5              (0x28)
/** Offset in interrupt vector table for MLX16_EXCHG */
#define MEM_FLASH_VECTOR_OFFSET_MLX16_EXCHG           (0x30)
/** Offset in interrupt vector table for MLX16_DMAERR */
#define MEM_FLASH_VECTOR_OFFSET_MLX16_DMAERR          (0x38)
/** Offset in interrupt vector table for AWD_ATT */
#define MEM_FLASH_VECTOR_OFFSET_AWD_ATT               (0x40)
/** Offset in interrupt vector table for IWD_ATT */
#define MEM_FLASH_VECTOR_OFFSET_IWD_ATT               (0x48)
/** Offset in interrupt vector table for FL_ECC */
#define MEM_FLASH_VECTOR_OFFSET_FL_ECC                (0x50)
/** Offset in interrupt vector table for EE_ECC */
#define MEM_FLASH_VECTOR_OFFSET_EE_ECC                (0x58)
/** Offset in interrupt vector table for UV_VDDA */
#define MEM_FLASH_VECTOR_OFFSET_UV_VDDA               (0x60)
/** Offset in interrupt vector table for UV_VS */
#define MEM_FLASH_VECTOR_OFFSET_UV_VS                 (0x68)
/** Offset in interrupt vector table for UV_VDDAF */
#define MEM_FLASH_VECTOR_OFFSET_UV_VDDAF              (0x70)
/** Offset in interrupt vector table for ANA_PLL_ERR */
#define MEM_FLASH_VECTOR_OFFSET_ANA_PLL_ERR           (0x78)
/** Offset in interrupt vector table for OVT */
#define MEM_FLASH_VECTOR_OFFSET_OVT                   (0x80)
/** Offset in interrupt vector table for OVC1 */
#define MEM_FLASH_VECTOR_OFFSET_OVC1                  (0x88)
/** Offset in interrupt vector table for OVC2 */
#define MEM_FLASH_VECTOR_OFFSET_OVC2                  (0x90)
/** Offset in interrupt vector table for OC_VDDA */
#define MEM_FLASH_VECTOR_OFFSET_OC_VDDA               (0x98)
/** Offset in interrupt vector table for STIMER */
#define MEM_FLASH_VECTOR_OFFSET_STIMER                (0xa0)
/** Offset in interrupt vector table for CTIMER0_1 */
#define MEM_FLASH_VECTOR_OFFSET_CTIMER0_1             (0xa8)
/** Offset in interrupt vector table for CTIMER0_2 */
#define MEM_FLASH_VECTOR_OFFSET_CTIMER0_2             (0xb0)
/** Offset in interrupt vector table for CTIMER0_3 */
#define MEM_FLASH_VECTOR_OFFSET_CTIMER0_3             (0xb8)
/** Offset in interrupt vector table for CTIMER1_1 */
#define MEM_FLASH_VECTOR_OFFSET_CTIMER1_1             (0xc0)
/** Offset in interrupt vector table for CTIMER1_2 */
#define MEM_FLASH_VECTOR_OFFSET_CTIMER1_2             (0xc8)
/** Offset in interrupt vector table for CTIMER1_3 */
#define MEM_FLASH_VECTOR_OFFSET_CTIMER1_3             (0xd0)
/** Offset in interrupt vector table for SPI_TE */
#define MEM_FLASH_VECTOR_OFFSET_SPI_TE                (0xd8)
/** Offset in interrupt vector table for SPI_RF */
#define MEM_FLASH_VECTOR_OFFSET_SPI_RF                (0xe0)
/** Offset in interrupt vector table for SPI_ER */
#define MEM_FLASH_VECTOR_OFFSET_SPI_ER                (0xe8)
/** Offset in interrupt vector table for PWM_MASTER1_CMP */
#define MEM_FLASH_VECTOR_OFFSET_PWM_MASTER1_CMP       (0xf0)
/** Offset in interrupt vector table for PWM_MASTER1_END */
#define MEM_FLASH_VECTOR_OFFSET_PWM_MASTER1_END       (0xf8)
/** Offset in interrupt vector table for PWM_SLAVE1_CMP */
#define MEM_FLASH_VECTOR_OFFSET_PWM_SLAVE1_CMP        (0x100)
/** Offset in interrupt vector table for PWM_SLAVE2_CMP */
#define MEM_FLASH_VECTOR_OFFSET_PWM_SLAVE2_CMP        (0x108)
/** Offset in interrupt vector table for PWM_MASTER2_CMP */
#define MEM_FLASH_VECTOR_OFFSET_PWM_MASTER2_CMP       (0x110)
/** Offset in interrupt vector table for PWM_MASTER2_END */
#define MEM_FLASH_VECTOR_OFFSET_PWM_MASTER2_END       (0x118)
/** Offset in interrupt vector table for PWM_SLAVE3_CMP */
#define MEM_FLASH_VECTOR_OFFSET_PWM_SLAVE3_CMP        (0x120)
/** Offset in interrupt vector table for PWM_SLAVE4_CMP */
#define MEM_FLASH_VECTOR_OFFSET_PWM_SLAVE4_CMP        (0x128)
/** Offset in interrupt vector table for ADC_BLOCK */
#define MEM_FLASH_VECTOR_OFFSET_ADC_BLOCK             (0x130)
/** Offset in interrupt vector table for EE_COMPLETE */
#define MEM_FLASH_VECTOR_OFFSET_EE_COMPLETE           (0x138)
/** Offset in interrupt vector table for FL_COMPLETE */
#define MEM_FLASH_VECTOR_OFFSET_FL_COMPLETE           (0x140)
/** Offset in interrupt vector table for COLIN_OWNMTX */
#define MEM_FLASH_VECTOR_OFFSET_COLIN_OWNMTX          (0x148)
/** Offset in interrupt vector table for COLIN_LIN */
#define MEM_FLASH_VECTOR_OFFSET_COLIN_LIN             (0x150)
/** Offset in interrupt vector table for OV_VS */
#define MEM_FLASH_VECTOR_OFFSET_OV_VS                 (0x158)
/** Offset in interrupt vector table for OV_VDDA */
#define MEM_FLASH_VECTOR_OFFSET_OV_VDDA               (0x160)
/** Offset in interrupt vector table for DIAG */
#define MEM_FLASH_VECTOR_OFFSET_DIAG                  (0x168)
/** Offset in interrupt vector table for I2C_GLOBAL_RESET */
#define MEM_FLASH_VECTOR_OFFSET_I2C_GLOBAL_RESET      (0x170)
/** Offset in interrupt vector table for I2C_EOW */
#define MEM_FLASH_VECTOR_OFFSET_I2C_EOW               (0x178)
/** Offset in interrupt vector table for I2C_EOR */
#define MEM_FLASH_VECTOR_OFFSET_I2C_EOR               (0x180)
/** Offset in interrupt vector table for I2C_ERR */
#define MEM_FLASH_VECTOR_OFFSET_I2C_ERR               (0x188)
/** Offset in interrupt vector table for PPM_RX */
#define MEM_FLASH_VECTOR_OFFSET_PPM_RX                (0x190)
/** Offset in interrupt vector table for PPM_TX */
#define MEM_FLASH_VECTOR_OFFSET_PPM_TX                (0x198)
/** Offset in interrupt vector table for PPM_ERR */
#define MEM_FLASH_VECTOR_OFFSET_PPM_ERR               (0x1a0)
/** Offset in interrupt vector table for TX_TIMEOUT */
#define MEM_FLASH_VECTOR_OFFSET_TX_TIMEOUT            (0x1a8)
/** Offset in interrupt vector table for UART0_SB */
#define MEM_FLASH_VECTOR_OFFSET_UART0_SB              (0x1b0)
/** Offset in interrupt vector table for UART0_RS */
#define MEM_FLASH_VECTOR_OFFSET_UART0_RS              (0x1b8)
/** Offset in interrupt vector table for UART0_RR */
#define MEM_FLASH_VECTOR_OFFSET_UART0_RR              (0x1c0)
/** Offset in interrupt vector table for UART0_TS */
#define MEM_FLASH_VECTOR_OFFSET_UART0_TS              (0x1c8)
/** Offset in interrupt vector table for UART0_TR */
#define MEM_FLASH_VECTOR_OFFSET_UART0_TR              (0x1d0)
/** Offset in interrupt vector table for UART0_TE */
#define MEM_FLASH_VECTOR_OFFSET_UART0_TE              (0x1d8)
/** Offset in interrupt vector table for UDFR0 */
#define MEM_FLASH_VECTOR_OFFSET_UDFR0                 (0x1e0)
/** Offset in interrupt vector table for UDTF0 */
#define MEM_FLASH_VECTOR_OFFSET_UDTF0                 (0x1e8)
/** Offset in interrupt vector table for UART1_SB */
#define MEM_FLASH_VECTOR_OFFSET_UART1_SB              (0x1f0)
/** Offset in interrupt vector table for UART1_RS */
#define MEM_FLASH_VECTOR_OFFSET_UART1_RS              (0x1f8)
/** Offset in interrupt vector table for UART1_RR */
#define MEM_FLASH_VECTOR_OFFSET_UART1_RR              (0x200)
/** Offset in interrupt vector table for UART1_TS */
#define MEM_FLASH_VECTOR_OFFSET_UART1_TS              (0x208)
/** Offset in interrupt vector table for UART1_TR */
#define MEM_FLASH_VECTOR_OFFSET_UART1_TR              (0x210)
/** Offset in interrupt vector table for UART1_TE */
#define MEM_FLASH_VECTOR_OFFSET_UART1_TE              (0x218)
/** Offset in interrupt vector table for UDFR1 */
#define MEM_FLASH_VECTOR_OFFSET_UDFR1                 (0x220)
/** Offset in interrupt vector table for UDTF1 */
#define MEM_FLASH_VECTOR_OFFSET_UDTF1                 (0x228)
/** Offset in interrupt vector table for IO_IN0 */
#define MEM_FLASH_VECTOR_OFFSET_IO_IN0                (0x230)
/** Offset in interrupt vector table for IO_IN1 */
#define MEM_FLASH_VECTOR_OFFSET_IO_IN1                (0x238)
/** Offset in interrupt vector table for IO_IN2 */
#define MEM_FLASH_VECTOR_OFFSET_IO_IN2                (0x240)
/** Offset in interrupt vector table for IO_IN3 */
#define MEM_FLASH_VECTOR_OFFSET_IO_IN3                (0x248)
/** Offset in interrupt vector table for IO_IN4 */
#define MEM_FLASH_VECTOR_OFFSET_IO_IN4                (0x250)
/** Offset in interrupt vector table for IO_IN5 */
#define MEM_FLASH_VECTOR_OFFSET_IO_IN5                (0x258)
/** Offset in interrupt vector table for IO_IN6 */
#define MEM_FLASH_VECTOR_OFFSET_IO_IN6                (0x260)
/** Offset in interrupt vector table for IO_IN7 */
#define MEM_FLASH_VECTOR_OFFSET_IO_IN7                (0x268)
/** Offset in interrupt vector table for IO_IN8 */
#define MEM_FLASH_VECTOR_OFFSET_IO_IN8                (0x270)
/** Offset in interrupt vector table for IO_IN9 */
#define MEM_FLASH_VECTOR_OFFSET_IO_IN9                (0x278)
/** Offset in interrupt vector table for IO_IN10 */
#define MEM_FLASH_VECTOR_OFFSET_IO_IN10               (0x280)
/** Offset in interrupt vector table for IO_IN11 */
#define MEM_FLASH_VECTOR_OFFSET_IO_IN11               (0x288)
/** Offset in interrupt vector table for PH_IN0 */
#define MEM_FLASH_VECTOR_OFFSET_PH_IN0                (0x290)
/** Offset in interrupt vector table for PH_IN1 */
#define MEM_FLASH_VECTOR_OFFSET_PH_IN1                (0x298)
/** Offset in interrupt vector table for PH_IN2 */
#define MEM_FLASH_VECTOR_OFFSET_PH_IN2                (0x2a0)
/** Offset in interrupt vector table for PH_IN3 */
#define MEM_FLASH_VECTOR_OFFSET_PH_IN3                (0x2a8)
/** Offset in interrupt vector table for PH_IN4 */
#define MEM_FLASH_VECTOR_OFFSET_PH_IN4                (0x2b0)
/** Offset in interrupt vector table for PH_IN5 */
#define MEM_FLASH_VECTOR_OFFSET_PH_IN5                (0x2b8)
/** Offset in interrupt vector table for I2C_MST */
#define MEM_FLASH_VECTOR_OFFSET_I2C_MST               (0x2c0)
/** Offset in interrupt vector table for MLX16_SOFT */
#define MEM_FLASH_VECTOR_OFFSET_MLX16_SOFT            (0x2c8)

#endif

