#ifndef HAL_LIB_ADC_INLINE_H
#define HAL_LIB_ADC_INLINE_H
#include "../AppBuild.h"
#include <atomic.h>
#define B_MLX16_ITC_PEND2_ADC B_MLX16_ITC_PEND2_ADC_SAR
#define B_MLX16_ITC_MASK2_ADC B_MLX16_ITC_MASK2_ADC_SAR
#define M_MLX16_ITC_PRIO2_ADC M_MLX16_ITC_PRIO2_ADC_SAR
#define C_MLX16_ITC_PRIO2_ADC_PRIO4 C_MLX16_ITC_PRIO2_ADC_SAR_PRIO4
#define C_MLX16_ITC_PRIO2_ADC_PRIO6 C_MLX16_ITC_PRIO2_ADC_SAR_PRIO6
#define IO_ADC_CTRL IO_ADC_SAR_CTRL
#define B_ADC_ADC_WIDTH B_ADC_SAR_ADC_WIDTH
#define C_ADC_ASB_NEVER C_ADC_SAR_ASB_NEVER
#define C_ADC_INT_SCHEME_EOC C_ADC_SAR_INT_SCHEME_EOC
#define C_ADC_INT_SCHEME_EOF C_ADC_SAR_INT_SCHEME_EOF
#define C_ADC_INT_SCHEME_EOS C_ADC_SAR_INT_SCHEME_EOS
#define C_ADC_INT_SCHEME_NOINT C_ADC_SAR_INT_SCHEME_NOINT
#define B_ADC_SATURATE B_ADC_SAR_SATURATE
#define B_ADC_NO_INTERLEAVE B_ADC_SAR_NO_INTERLEAVE
#define C_ADC_SOC_SOURCE_HARD_CTRIG C_ADC_SAR_SOC_SOURCE_HARD_CTRIG
#define C_ADC_SOS_SOURCE_HARD_CTRIG C_ADC_SAR_SOS_SOURCE_HARD_CTRIG
#define C_ADC_SOS_SOURCE_2ND_HARD_CTRIG C_ADC_SAR_SOS_SOURCE_2ND_HARD_CTRIG
#define C_ADC_SOS_SOURCE_SOFT_TRIG C_ADC_SAR_SOS_SOURCE_SOFT_TRIG
#define B_ADC_STOP B_ADC_SAR_STOP
#define B_ADC_START B_ADC_SAR_START
#define IO_ADC_STATUS IO_ADC_SAR_STATUS
#define B_ADC_ABORTED B_ADC_SAR_ABORTED
#define B_ADC_FRAME_ERR B_ADC_SAR_FRAME_ERR
#define B_ADC_MEM_ERR B_ADC_SAR_MEM_ERR
#define B_ADC_ADC_ERR B_ADC_SAR_ADC_ERR
#define B_ADC_ADC_OVF B_ADC_SAR_ADC_OVF
#define B_ADC_PAUSE B_ADC_SAR_PAUSE
#define B_ADC_RESUME B_ADC_SAR_RESUME
#define M_ADC_STATE M_ADC_SAR_STATE
#define C_ADC_STATE_IDLE C_ADC_SAR_STATE_IDLE
#define C_ADC_STATE_WAIT_FOR_TRIGGER C_ADC_SAR_STATE_WAIT_FOR_TRIGGER
#define C_ADC_STATE_MEM_TRANSFER C_ADC_SAR_STATE_MEM_TRANSFER
#define B_ADC_SW_TRIG B_ADC_SAR_SW_TRIG
#define IO_ADC_SBASE IO_ADC_SAR_SBASE
#define C_ADC_SUPPLY_CHECK 20U
static __inline__ void HAL_ADC_PreCheck(void)
{
	uint16_t u16LoopCnt = C_ADC_SUPPLY_CHECK;
	do
	{
		u16LoopCnt--;
		if((IO_MLX16_ITC_PEND0_S & B_MLX16_ITC_PEND0_UV_VDDA)  !=  0U)
		{
			ENTER_SECTION(SYSTEM_MODE);
			IO_MLX16_ITC_PEND0_S = B_MLX16_ITC_PEND0_UV_VDDA;
			EXIT_SECTION();
			continue;
		}
	}
	while(u16LoopCnt  !=  0U);
}

static __inline__ void HAL_ADC_Start(void)
{
	IO_ADC_CTRL = B_ADC_START;
}

static __inline__ void HAL_ADC_Stop(void)
{
	IO_ADC_CTRL = B_ADC_STOP;
}

static __inline__ void HAL_ADC_SoftTrigger(void)
{
	IO_ADC_STATUS = B_ADC_SW_TRIG;
}

static __inline__ void HAL_ADC_ClearErrors(void)
{
	IO_ADC_STATUS = B_ADC_PAUSE;
	IO_ADC_STATUS = (B_ADC_ABORTED |
	B_ADC_FRAME_ERR |
	B_ADC_MEM_ERR |
	B_ADC_ADC_ERR |
	B_ADC_ADC_OVF);
	IO_ADC_STATUS = B_ADC_RESUME;
}

static __inline__ void HAL_ADC_DisableIRQ(void)
{
	ENTER_SECTION(ATOMIC_SYSTEM_MODE);
	IO_MLX16_ITC_MASK2_S  &=  ~B_MLX16_ITC_MASK2_ADC;
	IO_MLX16_ITC_PEND2_S = B_MLX16_ITC_PEND2_ADC;
	EXIT_SECTION();
}

static __inline__ void HAL_ADC_EnableIRQ(void)
{
	ENTER_SECTION(ATOMIC_SYSTEM_MODE);
	IO_MLX16_ITC_PEND2_S = B_MLX16_ITC_PEND2_ADC;
	IO_MLX16_ITC_MASK2_S  |=  B_MLX16_ITC_MASK2_ADC;
	EXIT_SECTION();
}

static __inline__ void HAL_ADC_SetPrio(uint16_t u16Priority)
{
	ENTER_SECTION(SYSTEM_MODE);
	IO_MLX16_ITC_PRIO2_S = (IO_MLX16_ITC_PRIO2_S & ~M_MLX16_ITC_PRIO2_ADC) | u16Priority;
	EXIT_SECTION();
}

static __inline__ void HAL_ADC_SetPrioAndEnableIRQ(uint16_t u16Priority)
{
	ENTER_SECTION(ATOMIC_SYSTEM_MODE);
	IO_MLX16_ITC_PRIO2_S = (IO_MLX16_ITC_PRIO2_S & ~M_MLX16_ITC_PRIO2_ADC) | u16Priority;
	IO_MLX16_ITC_PEND2_S = B_MLX16_ITC_PEND2_ADC;
	IO_MLX16_ITC_MASK2_S  |=  B_MLX16_ITC_MASK2_ADC;
	EXIT_SECTION();
}

static __inline__ void HAL_ADC_Setup(uint16_t u16Ctrl)
{
#pragma space nodp
	extern uint16_t l_au16AdcSource[];
#pragma space none
	IO_ADC_SBASE = (uint16_t)&l_au16AdcSource[0];
	IO_ADC_CTRL = u16Ctrl;
}

static __inline__ void HAL_ADC_PendClear(void)
{
	ENTER_SECTION(SYSTEM_MODE);
	IO_MLX16_ITC_PEND2_S = B_MLX16_ITC_PEND2_ADC;
	EXIT_SECTION();
}

static __inline__ void HAL_ADC_PendWait(void)
{
	while((IO_MLX16_ITC_PEND2_S & B_MLX16_ITC_PEND2_ADC)  ==  0U)
	{
	};
}

#endif
