#ifndef HAL_LIB_STIMER_INLINE_H
#define HAL_LIB_STIMER_INLINE_H
#include "../AppBuild.h"
#include <atomic.h>
#define C_STIMER_PRIO C_MLX16_ITC_PRIO0_STIMER_PRIO6
static __inline__ void HAL_STimer_Init(void)
{
	IO_STIMER_CTRL = C_STIMER_MODE_1MHz | CT_1MHz_PERIODIC_RATE;
	ENTER_SECTION(SYSTEM_MODE);
	IO_MLX16_ITC_PRIO0_S = (IO_MLX16_ITC_PRIO0_S & ~M_MLX16_ITC_PRIO0_STIMER) | C_STIMER_PRIO;
	IO_MLX16_ITC_PEND1_S = B_MLX16_ITC_PEND1_STIMER;
	IO_MLX16_ITC_MASK1_S  |=  B_MLX16_ITC_MASK1_STIMER;
	EXIT_SECTION();
}

static __inline__ void HAL_STimer_Stop(void)
{
	IO_STIMER_CTRL = C_STIMER_MODE_OFF;
	ENTER_SECTION(SYSTEM_MODE);
	IO_MLX16_ITC_MASK1_S  &=  ~B_MLX16_ITC_MASK1_STIMER;
	IO_MLX16_ITC_PEND1_S = B_MLX16_ITC_PEND1_STIMER;
	EXIT_SECTION();
}

static __inline__ uint16_t HAL_STimer_Check(void)
{
	uint16_t u16Result = FALSE;
	if(((IO_STIMER_CTRL & M_STIMER_MODE)  ==  C_STIMER_MODE_OFF)  ||  ((IO_MLX16_ITC_PRIO0_S & M_MLX16_ITC_PRIO0_STIMER)  !=  C_STIMER_PRIO)  ||  ((IO_MLX16_ITC_MASK1_S & B_MLX16_ITC_MASK1_STIMER)  ==  0U)){u16Result = TRUE;}
	return( u16Result );
}

#endif
