/**
 * @file
 * @brief Interrupt handlers definitions file.
 * @internal
 *
 * @copyright (C) 2021 Melexis N.V.
 * git flash d0014c23
 *
 * Melexis N.V. is supplying this code for use with Melexis N.V. processor based microcontrollers only.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
 * INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.  MELEXIS N.V. SHALL NOT IN ANY CIRCUMSTANCES,
 * BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * @endinternal
 *
 * @ingroup fw_user_startup
 *
 * @details This file contains the implementations ofinterrupt handlers.
 * This file was autogenerated. The information of the source is described below:
 * Tag: DIG81346_IR_2_0_1_20210205_170246
 */

#ifndef FW_INTS_H_
#define FW_INTS_H_


/* ---------------------------------------------
 * Function Declarations
 * --------------------------------------------- */

/** Interrupt handler for MLX16_EXCHG */
extern void _MLX16_EXCHG_INT(void);

/** Interrupt handler for MLX16_DMAERR */
extern void _MLX16_DMAERR_INT(void);

/** Interrupt handler for AWD_ATT */
extern void _AWD_ATT_INT(void);

/** Interrupt handler for IWD_ATT */
extern void _IWD_ATT_INT(void);

/** Interrupt handler for FL_ECC */
extern void _FL_ECC_INT(void);

/** Interrupt handler for EE_ECC */
extern void _EE_ECC_INT(void);

/** Interrupt handler for UV_VDDA */
extern void _UV_VDDA_INT(void);

/** Interrupt handler for UV_VS */
extern void _UV_VS_INT(void);

/** Interrupt handler for UV_BOOST */
extern void _UV_BOOST_INT(void);

/** Interrupt handler for ANA_PLL_ERR */
extern void _ANA_PLL_ERR_INT(void);

/** Interrupt handler for OVT */
extern void _OVT_INT(void);

/** Interrupt handler for OVC */
extern void _OVC_INT(void);

/** Interrupt handler for OC_VDDA */
extern void _OC_VDDA_INT(void);

/** Interrupt handler for OV_HS_IO3 */
extern void _OV_HS_IO3_INT(void);

/** Interrupt handler for OV_HS_IO4 */
extern void _OV_HS_IO4_INT(void);

/** Interrupt handler for OV_HS_VDS0 */
extern void _OV_HS_VDS0_INT(void);

/** Interrupt handler for OV_HS_VDS1 */
extern void _OV_HS_VDS1_INT(void);

/** Interrupt handler for OV_HS_VDS2 */
extern void _OV_HS_VDS2_INT(void);

/** Interrupt handler for OV_LS_VDS0 */
extern void _OV_LS_VDS0_INT(void);

/** Interrupt handler for OV_LS_VDS1 */
extern void _OV_LS_VDS1_INT(void);

/** Interrupt handler for OV_LS_VDS2 */
extern void _OV_LS_VDS2_INT(void);

/** Interrupt handler for STIMER */
extern void _STIMER_INT(void);

/** Interrupt handler for CTIMER0_1 */
extern void _CTIMER0_1_INT(void);

/** Interrupt handler for CTIMER0_2 */
extern void _CTIMER0_2_INT(void);

/** Interrupt handler for CTIMER0_3 */
extern void _CTIMER0_3_INT(void);

/** Interrupt handler for CTIMER1_1 */
extern void _CTIMER1_1_INT(void);

/** Interrupt handler for CTIMER1_2 */
extern void _CTIMER1_2_INT(void);

/** Interrupt handler for CTIMER1_3 */
extern void _CTIMER1_3_INT(void);

/** Interrupt handler for SPI_TE */
extern void _SPI_TE_INT(void);

/** Interrupt handler for SPI_RF */
extern void _SPI_RF_INT(void);

/** Interrupt handler for SPI_ER */
extern void _SPI_ER_INT(void);

/** Interrupt handler for PWM_MASTER1_CMP */
extern void _PWM_MASTER1_CMP_INT(void);

/** Interrupt handler for PWM_MASTER1_END */
extern void _PWM_MASTER1_END_INT(void);

/** Interrupt handler for PWM_SLAVE1_CMP */
extern void _PWM_SLAVE1_CMP_INT(void);

/** Interrupt handler for PWM_SLAVE2_CMP */
extern void _PWM_SLAVE2_CMP_INT(void);

/** Interrupt handler for PWM_SLAVE3_CMP */
extern void _PWM_SLAVE3_CMP_INT(void);

/** Interrupt handler for PWM_MASTER2_CMP */
extern void _PWM_MASTER2_CMP_INT(void);

/** Interrupt handler for PWM_MASTER2_END */
extern void _PWM_MASTER2_END_INT(void);

/** Interrupt handler for ADC_BLOCK */
extern void _ADC_BLOCK_INT(void);

/** Interrupt handler for EE_COMPLETE */
extern void _EE_COMPLETE_INT(void);

/** Interrupt handler for FL_COMPLETE */
extern void _FL_COMPLETE_INT(void);

/** Interrupt handler for COLIN_OWNMTX */
extern void _COLIN_OWNMTX_INT(void);

/** Interrupt handler for COLIN_LIN */
extern void _COLIN_LIN_INT(void);

/** Interrupt handler for DIAG */
extern void _DIAG_INT(void);

/** Interrupt handler for I2C_GLOBAL_RESET */
extern void _I2C_GLOBAL_RESET_INT(void);

/** Interrupt handler for PPM_RX */
extern void _PPM_RX_INT(void);

/** Interrupt handler for PPM_TX */
extern void _PPM_TX_INT(void);

/** Interrupt handler for PPM_ERR */
extern void _PPM_ERR_INT(void);

/** Interrupt handler for OV_VS */
extern void _OV_VS_INT(void);

/** Interrupt handler for OV_VDDA */
extern void _OV_VDDA_INT(void);

/** Interrupt handler for OV_BOOST */
extern void _OV_BOOST_INT(void);

/** Interrupt handler for IO_IN0 */
extern void _IO_IN0_INT(void);

/** Interrupt handler for IO_IN1 */
extern void _IO_IN1_INT(void);

/** Interrupt handler for IO_IN2 */
extern void _IO_IN2_INT(void);

/** Interrupt handler for IO_IN3 */
extern void _IO_IN3_INT(void);

/** Interrupt handler for IO_IN4 */
extern void _IO_IN4_INT(void);

/** Interrupt handler for IO_IN5 */
extern void _IO_IN5_INT(void);

/** Interrupt handler for IO_IN6 */
extern void _IO_IN6_INT(void);

/** Interrupt handler for IO_IN7 */
extern void _IO_IN7_INT(void);

/** Interrupt handler for IO_IN8 */
extern void _IO_IN8_INT(void);

/** Interrupt handler for IO_IN9 */
extern void _IO_IN9_INT(void);

/** Interrupt handler for IO_IN10 */
extern void _IO_IN10_INT(void);

/** Interrupt handler for IO_IN11 */
extern void _IO_IN11_INT(void);

/** Interrupt handler for TX_TIMEOUT */
extern void _TX_TIMEOUT_INT(void);

/** Interrupt handler for UART0_SB */
extern void _UART0_SB_INT(void);

/** Interrupt handler for UART0_RS */
extern void _UART0_RS_INT(void);

/** Interrupt handler for UART0_RR */
extern void _UART0_RR_INT(void);

/** Interrupt handler for UART0_TS */
extern void _UART0_TS_INT(void);

/** Interrupt handler for UART0_TR */
extern void _UART0_TR_INT(void);

/** Interrupt handler for UART0_TE */
extern void _UART0_TE_INT(void);

/** Interrupt handler for UDFR0 */
extern void _UDFR0_INT(void);

/** Interrupt handler for UDTF0 */
extern void _UDTF0_INT(void);

/** Interrupt handler for UART1_SB */
extern void _UART1_SB_INT(void);

/** Interrupt handler for UART1_RS */
extern void _UART1_RS_INT(void);

/** Interrupt handler for UART1_RR */
extern void _UART1_RR_INT(void);

/** Interrupt handler for UART1_TS */
extern void _UART1_TS_INT(void);

/** Interrupt handler for UART1_TR */
extern void _UART1_TR_INT(void);

/** Interrupt handler for UART1_TE */
extern void _UART1_TE_INT(void);

/** Interrupt handler for UDFR1 */
extern void _UDFR1_INT(void);

/** Interrupt handler for UDTF1 */
extern void _UDTF1_INT(void);

/** Interrupt handler for ACTIVE_CDI */
extern void _ACTIVE_CDI_INT(void);

/** Interrupt handler for I2C_EOW */
extern void _I2C_EOW_INT(void);

/** Interrupt handler for I2C_EOR */
extern void _I2C_EOR_INT(void);

/** Interrupt handler for I2C_ERR */
extern void _I2C_ERR_INT(void);

/** Interrupt handler for MLX16_SOFT */
extern void _MLX16_SOFT_INT(void);


#endif /* FW_INTS_H_ */

