/**
 * @file
 * @brief Interrupt CPU priority settings
 * @internal
 *
 * @copyright (C) 2021 Melexis N.V.
 *
 * Melexis N.V. is supplying this code for use with Melexis N.V. processor based microcontrollers only.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
 * INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.  MELEXIS N.V. SHALL NOT IN ANY CIRCUMSTANCES,
 * BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * @endinternal
 *
 * @ingroup fw_user_startup
 *
 * @details
 * This file was autogenerated. The information of the source is described below:
 * Tag: DIG81160_RC_1_0_32_20200725_164352
 *
 * This file configures the CPU priority during interrupt execution. Normally the execution level shall
 * be 1 level higher so that an interrupt can not interrupt itself resulting in re-entering the specific
 * interrupt.
 * When for specific reasons a user needs to configure another deviating value he/she can still do so
 * by setting the `CPU_PRIO_<int_name>_INT` to the preferred value in `fw_ints_prio.h` file; as such
 * this file should not be touched by users.
 */

#ifndef FW_INTS_CPU_PRIO_H_
#define FW_INTS_CPU_PRIO_H_

#include "fw_ints_prio.h"

/** Macro to calculate the interrupt priority level */
#define __CPU_PRIO(mode, prio) (mode | (prio - 1))

#ifndef CPU_PRIO_MLX16_EXCHG_INT
/** Interrupt execution priority level for MLX16_EXCHG: Exchange (PTC and Debugger) */
#define CPU_PRIO_MLX16_EXCHG_INT 0
#endif

#ifndef CPU_PRIO_MLX16_DMAERR_INT
/** Interrupt execution priority level for MLX16_DMAERR: DMA error */
#define CPU_PRIO_MLX16_DMAERR_INT 0
#endif

#ifndef CPU_PRIO_AWD_ATT_INT
/** Interrupt execution priority level for AWD_ATT: Absolute watchdog attention */
#define CPU_PRIO_AWD_ATT_INT 0
#endif

#ifndef CPU_PRIO_IWD_ATT_INT
/** Interrupt execution priority level for IWD_ATT: Intelligent watchdog attention */
#define CPU_PRIO_IWD_ATT_INT 0
#endif

#ifndef CPU_PRIO_FL_ECC_INT
/** Interrupt execution priority level for FL_ECC:  */
#define CPU_PRIO_FL_ECC_INT 0
#endif

#ifndef CPU_PRIO_EE_ECC_INT
/** Interrupt execution priority level for EE_ECC:  */
#define CPU_PRIO_EE_ECC_INT 0
#endif

#ifndef CPU_PRIO_UV_VDDA_INT
/** Interrupt execution priority level for UV_VDDA:  */
#define CPU_PRIO_UV_VDDA_INT 0
#endif

#ifndef CPU_PRIO_UV_VS_INT
/** Interrupt execution priority level for UV_VS:  */
#define CPU_PRIO_UV_VS_INT 0
#endif

#ifndef CPU_PRIO_UV_VDDAF_INT
/** Interrupt execution priority level for UV_VDDAF:  */
#define CPU_PRIO_UV_VDDAF_INT 0
#endif

#ifndef CPU_PRIO_ANA_PLL_ERR_INT
/** Interrupt execution priority level for ANA_PLL_ERR:  */
#define CPU_PRIO_ANA_PLL_ERR_INT 1
#endif

#ifndef CPU_PRIO_OVT_INT
/** Interrupt execution priority level for OVT:  */
#define CPU_PRIO_OVT_INT 1
#endif

#ifndef CPU_PRIO_OVC1_INT
/** Interrupt execution priority level for OVC1:  */
#define CPU_PRIO_OVC1_INT 1
#endif

#ifndef CPU_PRIO_OVC2_INT
/** Interrupt execution priority level for OVC2:  */
#define CPU_PRIO_OVC2_INT 1
#endif

#ifndef CPU_PRIO_OC_VDDA_INT
/** Interrupt execution priority level for OC_VDDA:  */
#define CPU_PRIO_OC_VDDA_INT 1
#endif

#ifndef PRIO_STIMER_INT
/** Interrupt priority level for STIMER: Simple Timer interrupt [3, 6] */
#define PRIO_STIMER_INT 3
#endif
#if (PRIO_STIMER_INT < 3) || (PRIO_STIMER_INT > 6)
#error "PRIO_STIMER_INT shall be in range [3, 6]"
#endif
#ifndef MODE_STIMER_INT
/** Interrupt CPU mode for STIMER: Simple Timer interrupt [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_STIMER_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_STIMER_INT
/** Interrupt execution priority level for STIMER: Simple Timer interrupt */
#define CPU_PRIO_STIMER_INT __CPU_PRIO(MODE_STIMER_INT, PRIO_STIMER_INT)
#endif

#ifndef PRIO_CTIMER0_1_INT
/** Interrupt priority level for CTIMER0_1: Complex Timer interrupt 1 [3, 6] */
#define PRIO_CTIMER0_1_INT 3
#endif
#if (PRIO_CTIMER0_1_INT < 3) || (PRIO_CTIMER0_1_INT > 6)
#error "PRIO_CTIMER0_1_INT shall be in range [3, 6]"
#endif
#ifndef MODE_CTIMER0_1_INT
/** Interrupt CPU mode for CTIMER0_1: Complex Timer interrupt 1 [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_CTIMER0_1_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_CTIMER0_1_INT
/** Interrupt execution priority level for CTIMER0_1: Complex Timer interrupt 1 */
#define CPU_PRIO_CTIMER0_1_INT __CPU_PRIO(MODE_CTIMER0_1_INT, PRIO_CTIMER0_1_INT)
#endif

#ifndef PRIO_CTIMER0_2_INT
/** Interrupt priority level for CTIMER0_2: Complex Timer interrupt 2 [3, 6] */
#define PRIO_CTIMER0_2_INT 3
#endif
#if (PRIO_CTIMER0_2_INT < 3) || (PRIO_CTIMER0_2_INT > 6)
#error "PRIO_CTIMER0_2_INT shall be in range [3, 6]"
#endif
#ifndef MODE_CTIMER0_2_INT
/** Interrupt CPU mode for CTIMER0_2: Complex Timer interrupt 2 [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_CTIMER0_2_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_CTIMER0_2_INT
/** Interrupt execution priority level for CTIMER0_2: Complex Timer interrupt 2 */
#define CPU_PRIO_CTIMER0_2_INT __CPU_PRIO(MODE_CTIMER0_2_INT, PRIO_CTIMER0_2_INT)
#endif

#ifndef PRIO_CTIMER0_3_INT
/** Interrupt priority level for CTIMER0_3: Complex Timer interrupt 3 [3, 6] */
#define PRIO_CTIMER0_3_INT 3
#endif
#if (PRIO_CTIMER0_3_INT < 3) || (PRIO_CTIMER0_3_INT > 6)
#error "PRIO_CTIMER0_3_INT shall be in range [3, 6]"
#endif
#ifndef MODE_CTIMER0_3_INT
/** Interrupt CPU mode for CTIMER0_3: Complex Timer interrupt 3 [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_CTIMER0_3_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_CTIMER0_3_INT
/** Interrupt execution priority level for CTIMER0_3: Complex Timer interrupt 3 */
#define CPU_PRIO_CTIMER0_3_INT __CPU_PRIO(MODE_CTIMER0_3_INT, PRIO_CTIMER0_3_INT)
#endif

#ifndef PRIO_CTIMER1_1_INT
/** Interrupt priority level for CTIMER1_1: Complex Timer interrupt 1 [3, 6] */
#define PRIO_CTIMER1_1_INT 3
#endif
#if (PRIO_CTIMER1_1_INT < 3) || (PRIO_CTIMER1_1_INT > 6)
#error "PRIO_CTIMER1_1_INT shall be in range [3, 6]"
#endif
#ifndef MODE_CTIMER1_1_INT
/** Interrupt CPU mode for CTIMER1_1: Complex Timer interrupt 1 [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_CTIMER1_1_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_CTIMER1_1_INT
/** Interrupt execution priority level for CTIMER1_1: Complex Timer interrupt 1 */
#define CPU_PRIO_CTIMER1_1_INT __CPU_PRIO(MODE_CTIMER1_1_INT, PRIO_CTIMER1_1_INT)
#endif

#ifndef PRIO_CTIMER1_2_INT
/** Interrupt priority level for CTIMER1_2: Complex Timer interrupt 2 [3, 6] */
#define PRIO_CTIMER1_2_INT 3
#endif
#if (PRIO_CTIMER1_2_INT < 3) || (PRIO_CTIMER1_2_INT > 6)
#error "PRIO_CTIMER1_2_INT shall be in range [3, 6]"
#endif
#ifndef MODE_CTIMER1_2_INT
/** Interrupt CPU mode for CTIMER1_2: Complex Timer interrupt 2 [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_CTIMER1_2_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_CTIMER1_2_INT
/** Interrupt execution priority level for CTIMER1_2: Complex Timer interrupt 2 */
#define CPU_PRIO_CTIMER1_2_INT __CPU_PRIO(MODE_CTIMER1_2_INT, PRIO_CTIMER1_2_INT)
#endif

#ifndef PRIO_CTIMER1_3_INT
/** Interrupt priority level for CTIMER1_3: Complex Timer interrupt 3 [3, 6] */
#define PRIO_CTIMER1_3_INT 3
#endif
#if (PRIO_CTIMER1_3_INT < 3) || (PRIO_CTIMER1_3_INT > 6)
#error "PRIO_CTIMER1_3_INT shall be in range [3, 6]"
#endif
#ifndef MODE_CTIMER1_3_INT
/** Interrupt CPU mode for CTIMER1_3: Complex Timer interrupt 3 [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_CTIMER1_3_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_CTIMER1_3_INT
/** Interrupt execution priority level for CTIMER1_3: Complex Timer interrupt 3 */
#define CPU_PRIO_CTIMER1_3_INT __CPU_PRIO(MODE_CTIMER1_3_INT, PRIO_CTIMER1_3_INT)
#endif

#ifndef PRIO_SPI_TE_INT
/** Interrupt priority level for SPI_TE: SPI transmit register is empty [3, 6] */
#define PRIO_SPI_TE_INT 3
#endif
#if (PRIO_SPI_TE_INT < 3) || (PRIO_SPI_TE_INT > 6)
#error "PRIO_SPI_TE_INT shall be in range [3, 6]"
#endif
#ifndef MODE_SPI_TE_INT
/** Interrupt CPU mode for SPI_TE: SPI transmit register is empty [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_SPI_TE_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_SPI_TE_INT
/** Interrupt execution priority level for SPI_TE: SPI transmit register is empty */
#define CPU_PRIO_SPI_TE_INT __CPU_PRIO(MODE_SPI_TE_INT, PRIO_SPI_TE_INT)
#endif

#ifndef PRIO_SPI_RF_INT
/** Interrupt priority level for SPI_RF: SPI receive register full [3, 6] */
#define PRIO_SPI_RF_INT 3
#endif
#if (PRIO_SPI_RF_INT < 3) || (PRIO_SPI_RF_INT > 6)
#error "PRIO_SPI_RF_INT shall be in range [3, 6]"
#endif
#ifndef MODE_SPI_RF_INT
/** Interrupt CPU mode for SPI_RF: SPI receive register full [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_SPI_RF_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_SPI_RF_INT
/** Interrupt execution priority level for SPI_RF: SPI receive register full */
#define CPU_PRIO_SPI_RF_INT __CPU_PRIO(MODE_SPI_RF_INT, PRIO_SPI_RF_INT)
#endif

#ifndef PRIO_SPI_ER_INT
/** Interrupt priority level for SPI_ER: SPI transmission error [3, 6] */
#define PRIO_SPI_ER_INT 3
#endif
#if (PRIO_SPI_ER_INT < 3) || (PRIO_SPI_ER_INT > 6)
#error "PRIO_SPI_ER_INT shall be in range [3, 6]"
#endif
#ifndef MODE_SPI_ER_INT
/** Interrupt CPU mode for SPI_ER: SPI transmission error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_SPI_ER_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_SPI_ER_INT
/** Interrupt execution priority level for SPI_ER: SPI transmission error */
#define CPU_PRIO_SPI_ER_INT __CPU_PRIO(MODE_SPI_ER_INT, PRIO_SPI_ER_INT)
#endif

#ifndef PRIO_PWM_MASTER1_CMP_INT
/** Interrupt priority level for PWM_MASTER1_CMP: Custom interrupt during the PWM period [3, 6] */
#define PRIO_PWM_MASTER1_CMP_INT 3
#endif
#if (PRIO_PWM_MASTER1_CMP_INT < 3) || (PRIO_PWM_MASTER1_CMP_INT > 6)
#error "PRIO_PWM_MASTER1_CMP_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PWM_MASTER1_CMP_INT
/** Interrupt CPU mode for PWM_MASTER1_CMP: Custom interrupt during the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_MASTER1_CMP_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PWM_MASTER1_CMP_INT
/** Interrupt execution priority level for PWM_MASTER1_CMP: Custom interrupt during the PWM period */
#define CPU_PRIO_PWM_MASTER1_CMP_INT __CPU_PRIO(MODE_PWM_MASTER1_CMP_INT, PRIO_PWM_MASTER1_CMP_INT)
#endif

#ifndef PRIO_PWM_MASTER1_END_INT
/** Interrupt priority level for PWM_MASTER1_END: Interrupt at the end of the PWM period [3, 6] */
#define PRIO_PWM_MASTER1_END_INT 3
#endif
#if (PRIO_PWM_MASTER1_END_INT < 3) || (PRIO_PWM_MASTER1_END_INT > 6)
#error "PRIO_PWM_MASTER1_END_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PWM_MASTER1_END_INT
/** Interrupt CPU mode for PWM_MASTER1_END: Interrupt at the end of the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_MASTER1_END_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PWM_MASTER1_END_INT
/** Interrupt execution priority level for PWM_MASTER1_END: Interrupt at the end of the PWM period */
#define CPU_PRIO_PWM_MASTER1_END_INT __CPU_PRIO(MODE_PWM_MASTER1_END_INT, PRIO_PWM_MASTER1_END_INT)
#endif

#ifndef PRIO_PWM_SLAVE1_CMP_INT
/** Interrupt priority level for PWM_SLAVE1_CMP: Custom interrupt during the PWM period [3, 6] */
#define PRIO_PWM_SLAVE1_CMP_INT 3
#endif
#if (PRIO_PWM_SLAVE1_CMP_INT < 3) || (PRIO_PWM_SLAVE1_CMP_INT > 6)
#error "PRIO_PWM_SLAVE1_CMP_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PWM_SLAVE1_CMP_INT
/** Interrupt CPU mode for PWM_SLAVE1_CMP: Custom interrupt during the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_SLAVE1_CMP_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PWM_SLAVE1_CMP_INT
/** Interrupt execution priority level for PWM_SLAVE1_CMP: Custom interrupt during the PWM period */
#define CPU_PRIO_PWM_SLAVE1_CMP_INT __CPU_PRIO(MODE_PWM_SLAVE1_CMP_INT, PRIO_PWM_SLAVE1_CMP_INT)
#endif

#ifndef PRIO_PWM_SLAVE2_CMP_INT
/** Interrupt priority level for PWM_SLAVE2_CMP: Custom interrupt during the PWM period [3, 6] */
#define PRIO_PWM_SLAVE2_CMP_INT 3
#endif
#if (PRIO_PWM_SLAVE2_CMP_INT < 3) || (PRIO_PWM_SLAVE2_CMP_INT > 6)
#error "PRIO_PWM_SLAVE2_CMP_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PWM_SLAVE2_CMP_INT
/** Interrupt CPU mode for PWM_SLAVE2_CMP: Custom interrupt during the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_SLAVE2_CMP_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PWM_SLAVE2_CMP_INT
/** Interrupt execution priority level for PWM_SLAVE2_CMP: Custom interrupt during the PWM period */
#define CPU_PRIO_PWM_SLAVE2_CMP_INT __CPU_PRIO(MODE_PWM_SLAVE2_CMP_INT, PRIO_PWM_SLAVE2_CMP_INT)
#endif

#ifndef PRIO_PWM_MASTER2_CMP_INT
/** Interrupt priority level for PWM_MASTER2_CMP: Custom interrupt during the PWM period [3, 6] */
#define PRIO_PWM_MASTER2_CMP_INT 3
#endif
#if (PRIO_PWM_MASTER2_CMP_INT < 3) || (PRIO_PWM_MASTER2_CMP_INT > 6)
#error "PRIO_PWM_MASTER2_CMP_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PWM_MASTER2_CMP_INT
/** Interrupt CPU mode for PWM_MASTER2_CMP: Custom interrupt during the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_MASTER2_CMP_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PWM_MASTER2_CMP_INT
/** Interrupt execution priority level for PWM_MASTER2_CMP: Custom interrupt during the PWM period */
#define CPU_PRIO_PWM_MASTER2_CMP_INT __CPU_PRIO(MODE_PWM_MASTER2_CMP_INT, PRIO_PWM_MASTER2_CMP_INT)
#endif

#ifndef PRIO_PWM_MASTER2_END_INT
/** Interrupt priority level for PWM_MASTER2_END: Interrupt at the end of the PWM period [3, 6] */
#define PRIO_PWM_MASTER2_END_INT 3
#endif
#if (PRIO_PWM_MASTER2_END_INT < 3) || (PRIO_PWM_MASTER2_END_INT > 6)
#error "PRIO_PWM_MASTER2_END_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PWM_MASTER2_END_INT
/** Interrupt CPU mode for PWM_MASTER2_END: Interrupt at the end of the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_MASTER2_END_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PWM_MASTER2_END_INT
/** Interrupt execution priority level for PWM_MASTER2_END: Interrupt at the end of the PWM period */
#define CPU_PRIO_PWM_MASTER2_END_INT __CPU_PRIO(MODE_PWM_MASTER2_END_INT, PRIO_PWM_MASTER2_END_INT)
#endif

#ifndef PRIO_PWM_SLAVE3_CMP_INT
/** Interrupt priority level for PWM_SLAVE3_CMP: Custom interrupt during the PWM period [3, 6] */
#define PRIO_PWM_SLAVE3_CMP_INT 3
#endif
#if (PRIO_PWM_SLAVE3_CMP_INT < 3) || (PRIO_PWM_SLAVE3_CMP_INT > 6)
#error "PRIO_PWM_SLAVE3_CMP_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PWM_SLAVE3_CMP_INT
/** Interrupt CPU mode for PWM_SLAVE3_CMP: Custom interrupt during the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_SLAVE3_CMP_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PWM_SLAVE3_CMP_INT
/** Interrupt execution priority level for PWM_SLAVE3_CMP: Custom interrupt during the PWM period */
#define CPU_PRIO_PWM_SLAVE3_CMP_INT __CPU_PRIO(MODE_PWM_SLAVE3_CMP_INT, PRIO_PWM_SLAVE3_CMP_INT)
#endif

#ifndef PRIO_PWM_SLAVE4_CMP_INT
/** Interrupt priority level for PWM_SLAVE4_CMP: Custom interrupt during the PWM period [3, 6] */
#define PRIO_PWM_SLAVE4_CMP_INT 3
#endif
#if (PRIO_PWM_SLAVE4_CMP_INT < 3) || (PRIO_PWM_SLAVE4_CMP_INT > 6)
#error "PRIO_PWM_SLAVE4_CMP_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PWM_SLAVE4_CMP_INT
/** Interrupt CPU mode for PWM_SLAVE4_CMP: Custom interrupt during the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_SLAVE4_CMP_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PWM_SLAVE4_CMP_INT
/** Interrupt execution priority level for PWM_SLAVE4_CMP: Custom interrupt during the PWM period */
#define CPU_PRIO_PWM_SLAVE4_CMP_INT __CPU_PRIO(MODE_PWM_SLAVE4_CMP_INT, PRIO_PWM_SLAVE4_CMP_INT)
#endif

#ifndef PRIO_ADC_BLOCK_INT
/** Interrupt priority level for ADC_BLOCK: ADC interrupt [3, 6] */
#define PRIO_ADC_BLOCK_INT 3
#endif
#if (PRIO_ADC_BLOCK_INT < 3) || (PRIO_ADC_BLOCK_INT > 6)
#error "PRIO_ADC_BLOCK_INT shall be in range [3, 6]"
#endif
#ifndef MODE_ADC_BLOCK_INT
/** Interrupt CPU mode for ADC_BLOCK: ADC interrupt [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_ADC_BLOCK_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_ADC_BLOCK_INT
/** Interrupt execution priority level for ADC_BLOCK: ADC interrupt */
#define CPU_PRIO_ADC_BLOCK_INT __CPU_PRIO(MODE_ADC_BLOCK_INT, PRIO_ADC_BLOCK_INT)
#endif

#ifndef PRIO_EE_COMPLETE_INT
/** Interrupt priority level for EE_COMPLETE:  [3, 6] */
#define PRIO_EE_COMPLETE_INT 3
#endif
#if (PRIO_EE_COMPLETE_INT < 3) || (PRIO_EE_COMPLETE_INT > 6)
#error "PRIO_EE_COMPLETE_INT shall be in range [3, 6]"
#endif
#ifndef MODE_EE_COMPLETE_INT
/** Interrupt CPU mode for EE_COMPLETE:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_EE_COMPLETE_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_EE_COMPLETE_INT
/** Interrupt execution priority level for EE_COMPLETE:  */
#define CPU_PRIO_EE_COMPLETE_INT __CPU_PRIO(MODE_EE_COMPLETE_INT, PRIO_EE_COMPLETE_INT)
#endif

#ifndef PRIO_FL_COMPLETE_INT
/** Interrupt priority level for FL_COMPLETE:  [3, 6] */
#define PRIO_FL_COMPLETE_INT 3
#endif
#if (PRIO_FL_COMPLETE_INT < 3) || (PRIO_FL_COMPLETE_INT > 6)
#error "PRIO_FL_COMPLETE_INT shall be in range [3, 6]"
#endif
#ifndef MODE_FL_COMPLETE_INT
/** Interrupt CPU mode for FL_COMPLETE:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_FL_COMPLETE_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_FL_COMPLETE_INT
/** Interrupt execution priority level for FL_COMPLETE:  */
#define CPU_PRIO_FL_COMPLETE_INT __CPU_PRIO(MODE_FL_COMPLETE_INT, PRIO_FL_COMPLETE_INT)
#endif

#ifndef PRIO_COLIN_OWNMTX_INT
/** Interrupt priority level for COLIN_OWNMTX: mutex interrupt [3, 6] */
#define PRIO_COLIN_OWNMTX_INT 3
#endif
#if (PRIO_COLIN_OWNMTX_INT < 3) || (PRIO_COLIN_OWNMTX_INT > 6)
#error "PRIO_COLIN_OWNMTX_INT shall be in range [3, 6]"
#endif
#ifndef MODE_COLIN_OWNMTX_INT
/** Interrupt CPU mode for COLIN_OWNMTX: mutex interrupt [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_COLIN_OWNMTX_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_COLIN_OWNMTX_INT
/** Interrupt execution priority level for COLIN_OWNMTX: mutex interrupt */
#define CPU_PRIO_COLIN_OWNMTX_INT __CPU_PRIO(MODE_COLIN_OWNMTX_INT, PRIO_COLIN_OWNMTX_INT)
#endif

#ifndef PRIO_COLIN_LIN_INT
/** Interrupt priority level for COLIN_LIN: LIN interrupt [3, 6] */
#define PRIO_COLIN_LIN_INT 3
#endif
#if (PRIO_COLIN_LIN_INT < 3) || (PRIO_COLIN_LIN_INT > 6)
#error "PRIO_COLIN_LIN_INT shall be in range [3, 6]"
#endif
#ifndef MODE_COLIN_LIN_INT
/** Interrupt CPU mode for COLIN_LIN: LIN interrupt [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_COLIN_LIN_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_COLIN_LIN_INT
/** Interrupt execution priority level for COLIN_LIN: LIN interrupt */
#define CPU_PRIO_COLIN_LIN_INT __CPU_PRIO(MODE_COLIN_LIN_INT, PRIO_COLIN_LIN_INT)
#endif

#ifndef PRIO_OV_VS_INT
/** Interrupt priority level for OV_VS:  [3, 6] */
#define PRIO_OV_VS_INT 3
#endif
#if (PRIO_OV_VS_INT < 3) || (PRIO_OV_VS_INT > 6)
#error "PRIO_OV_VS_INT shall be in range [3, 6]"
#endif
#ifndef MODE_OV_VS_INT
/** Interrupt CPU mode for OV_VS:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_OV_VS_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_OV_VS_INT
/** Interrupt execution priority level for OV_VS:  */
#define CPU_PRIO_OV_VS_INT __CPU_PRIO(MODE_OV_VS_INT, PRIO_OV_VS_INT)
#endif

#ifndef PRIO_OV_VDDA_INT
/** Interrupt priority level for OV_VDDA:  [3, 6] */
#define PRIO_OV_VDDA_INT 3
#endif
#if (PRIO_OV_VDDA_INT < 3) || (PRIO_OV_VDDA_INT > 6)
#error "PRIO_OV_VDDA_INT shall be in range [3, 6]"
#endif
#ifndef MODE_OV_VDDA_INT
/** Interrupt CPU mode for OV_VDDA:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_OV_VDDA_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_OV_VDDA_INT
/** Interrupt execution priority level for OV_VDDA:  */
#define CPU_PRIO_OV_VDDA_INT __CPU_PRIO(MODE_OV_VDDA_INT, PRIO_OV_VDDA_INT)
#endif

#ifndef PRIO_DIAG_INT
/** Interrupt priority level for DIAG:  [3, 6] */
#define PRIO_DIAG_INT 3
#endif
#if (PRIO_DIAG_INT < 3) || (PRIO_DIAG_INT > 6)
#error "PRIO_DIAG_INT shall be in range [3, 6]"
#endif
#ifndef MODE_DIAG_INT
/** Interrupt CPU mode for DIAG:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_DIAG_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_DIAG_INT
/** Interrupt execution priority level for DIAG:  */
#define CPU_PRIO_DIAG_INT __CPU_PRIO(MODE_DIAG_INT, PRIO_DIAG_INT)
#endif

#ifndef PRIO_I2C_GLOBAL_RESET_INT
/** Interrupt priority level for I2C_GLOBAL_RESET:  [3, 6] */
#define PRIO_I2C_GLOBAL_RESET_INT 3
#endif
#if (PRIO_I2C_GLOBAL_RESET_INT < 3) || (PRIO_I2C_GLOBAL_RESET_INT > 6)
#error "PRIO_I2C_GLOBAL_RESET_INT shall be in range [3, 6]"
#endif
#ifndef MODE_I2C_GLOBAL_RESET_INT
/** Interrupt CPU mode for I2C_GLOBAL_RESET:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_I2C_GLOBAL_RESET_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_I2C_GLOBAL_RESET_INT
/** Interrupt execution priority level for I2C_GLOBAL_RESET:  */
#define CPU_PRIO_I2C_GLOBAL_RESET_INT __CPU_PRIO(MODE_I2C_GLOBAL_RESET_INT, PRIO_I2C_GLOBAL_RESET_INT)
#endif

#ifndef PRIO_I2C_EOW_INT
/** Interrupt priority level for I2C_EOW:  [3, 6] */
#define PRIO_I2C_EOW_INT 3
#endif
#if (PRIO_I2C_EOW_INT < 3) || (PRIO_I2C_EOW_INT > 6)
#error "PRIO_I2C_EOW_INT shall be in range [3, 6]"
#endif
#ifndef MODE_I2C_EOW_INT
/** Interrupt CPU mode for I2C_EOW:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_I2C_EOW_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_I2C_EOW_INT
/** Interrupt execution priority level for I2C_EOW:  */
#define CPU_PRIO_I2C_EOW_INT __CPU_PRIO(MODE_I2C_EOW_INT, PRIO_I2C_EOW_INT)
#endif

#ifndef PRIO_I2C_EOR_INT
/** Interrupt priority level for I2C_EOR:  [3, 6] */
#define PRIO_I2C_EOR_INT 3
#endif
#if (PRIO_I2C_EOR_INT < 3) || (PRIO_I2C_EOR_INT > 6)
#error "PRIO_I2C_EOR_INT shall be in range [3, 6]"
#endif
#ifndef MODE_I2C_EOR_INT
/** Interrupt CPU mode for I2C_EOR:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_I2C_EOR_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_I2C_EOR_INT
/** Interrupt execution priority level for I2C_EOR:  */
#define CPU_PRIO_I2C_EOR_INT __CPU_PRIO(MODE_I2C_EOR_INT, PRIO_I2C_EOR_INT)
#endif

#ifndef PRIO_I2C_ERR_INT
/** Interrupt priority level for I2C_ERR:  [3, 6] */
#define PRIO_I2C_ERR_INT 3
#endif
#if (PRIO_I2C_ERR_INT < 3) || (PRIO_I2C_ERR_INT > 6)
#error "PRIO_I2C_ERR_INT shall be in range [3, 6]"
#endif
#ifndef MODE_I2C_ERR_INT
/** Interrupt CPU mode for I2C_ERR:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_I2C_ERR_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_I2C_ERR_INT
/** Interrupt execution priority level for I2C_ERR:  */
#define CPU_PRIO_I2C_ERR_INT __CPU_PRIO(MODE_I2C_ERR_INT, PRIO_I2C_ERR_INT)
#endif

#ifndef PRIO_PPM_RX_INT
/** Interrupt priority level for PPM_RX:  [3, 6] */
#define PRIO_PPM_RX_INT 3
#endif
#if (PRIO_PPM_RX_INT < 3) || (PRIO_PPM_RX_INT > 6)
#error "PRIO_PPM_RX_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PPM_RX_INT
/** Interrupt CPU mode for PPM_RX:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PPM_RX_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PPM_RX_INT
/** Interrupt execution priority level for PPM_RX:  */
#define CPU_PRIO_PPM_RX_INT __CPU_PRIO(MODE_PPM_RX_INT, PRIO_PPM_RX_INT)
#endif

#ifndef PRIO_PPM_TX_INT
/** Interrupt priority level for PPM_TX:  [3, 6] */
#define PRIO_PPM_TX_INT 3
#endif
#if (PRIO_PPM_TX_INT < 3) || (PRIO_PPM_TX_INT > 6)
#error "PRIO_PPM_TX_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PPM_TX_INT
/** Interrupt CPU mode for PPM_TX:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PPM_TX_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PPM_TX_INT
/** Interrupt execution priority level for PPM_TX:  */
#define CPU_PRIO_PPM_TX_INT __CPU_PRIO(MODE_PPM_TX_INT, PRIO_PPM_TX_INT)
#endif

#ifndef PRIO_PPM_ERR_INT
/** Interrupt priority level for PPM_ERR:  [3, 6] */
#define PRIO_PPM_ERR_INT 3
#endif
#if (PRIO_PPM_ERR_INT < 3) || (PRIO_PPM_ERR_INT > 6)
#error "PRIO_PPM_ERR_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PPM_ERR_INT
/** Interrupt CPU mode for PPM_ERR:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PPM_ERR_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PPM_ERR_INT
/** Interrupt execution priority level for PPM_ERR:  */
#define CPU_PRIO_PPM_ERR_INT __CPU_PRIO(MODE_PPM_ERR_INT, PRIO_PPM_ERR_INT)
#endif

#ifndef PRIO_TX_TIMEOUT_INT
/** Interrupt priority level for TX_TIMEOUT:  [3, 6] */
#define PRIO_TX_TIMEOUT_INT 3
#endif
#if (PRIO_TX_TIMEOUT_INT < 3) || (PRIO_TX_TIMEOUT_INT > 6)
#error "PRIO_TX_TIMEOUT_INT shall be in range [3, 6]"
#endif
#ifndef MODE_TX_TIMEOUT_INT
/** Interrupt CPU mode for TX_TIMEOUT:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_TX_TIMEOUT_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_TX_TIMEOUT_INT
/** Interrupt execution priority level for TX_TIMEOUT:  */
#define CPU_PRIO_TX_TIMEOUT_INT __CPU_PRIO(MODE_TX_TIMEOUT_INT, PRIO_TX_TIMEOUT_INT)
#endif

#ifndef PRIO_UART0_SB_INT
/** Interrupt priority level for UART0_SB: UART Stop bit error [3, 6] */
#define PRIO_UART0_SB_INT 3
#endif
#if (PRIO_UART0_SB_INT < 3) || (PRIO_UART0_SB_INT > 6)
#error "PRIO_UART0_SB_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UART0_SB_INT
/** Interrupt CPU mode for UART0_SB: UART Stop bit error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART0_SB_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UART0_SB_INT
/** Interrupt execution priority level for UART0_SB: UART Stop bit error */
#define CPU_PRIO_UART0_SB_INT __CPU_PRIO(MODE_UART0_SB_INT, PRIO_UART0_SB_INT)
#endif

#ifndef PRIO_UART0_RS_INT
/** Interrupt priority level for UART0_RS: UART Receive error [3, 6] */
#define PRIO_UART0_RS_INT 3
#endif
#if (PRIO_UART0_RS_INT < 3) || (PRIO_UART0_RS_INT > 6)
#error "PRIO_UART0_RS_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UART0_RS_INT
/** Interrupt CPU mode for UART0_RS: UART Receive error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART0_RS_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UART0_RS_INT
/** Interrupt execution priority level for UART0_RS: UART Receive error */
#define CPU_PRIO_UART0_RS_INT __CPU_PRIO(MODE_UART0_RS_INT, PRIO_UART0_RS_INT)
#endif

#ifndef PRIO_UART0_RR_INT
/** Interrupt priority level for UART0_RR: UART Receive [3, 6] */
#define PRIO_UART0_RR_INT 3
#endif
#if (PRIO_UART0_RR_INT < 3) || (PRIO_UART0_RR_INT > 6)
#error "PRIO_UART0_RR_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UART0_RR_INT
/** Interrupt CPU mode for UART0_RR: UART Receive [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART0_RR_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UART0_RR_INT
/** Interrupt execution priority level for UART0_RR: UART Receive */
#define CPU_PRIO_UART0_RR_INT __CPU_PRIO(MODE_UART0_RR_INT, PRIO_UART0_RR_INT)
#endif

#ifndef PRIO_UART0_TS_INT
/** Interrupt priority level for UART0_TS: UART Transmit end [3, 6] */
#define PRIO_UART0_TS_INT 3
#endif
#if (PRIO_UART0_TS_INT < 3) || (PRIO_UART0_TS_INT > 6)
#error "PRIO_UART0_TS_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UART0_TS_INT
/** Interrupt CPU mode for UART0_TS: UART Transmit end [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART0_TS_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UART0_TS_INT
/** Interrupt execution priority level for UART0_TS: UART Transmit end */
#define CPU_PRIO_UART0_TS_INT __CPU_PRIO(MODE_UART0_TS_INT, PRIO_UART0_TS_INT)
#endif

#ifndef PRIO_UART0_TR_INT
/** Interrupt priority level for UART0_TR: UART Transmit beginning [3, 6] */
#define PRIO_UART0_TR_INT 3
#endif
#if (PRIO_UART0_TR_INT < 3) || (PRIO_UART0_TR_INT > 6)
#error "PRIO_UART0_TR_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UART0_TR_INT
/** Interrupt CPU mode for UART0_TR: UART Transmit beginning [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART0_TR_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UART0_TR_INT
/** Interrupt execution priority level for UART0_TR: UART Transmit beginning */
#define CPU_PRIO_UART0_TR_INT __CPU_PRIO(MODE_UART0_TR_INT, PRIO_UART0_TR_INT)
#endif

#ifndef PRIO_UART0_TE_INT
/** Interrupt priority level for UART0_TE: UART Transmit error [3, 6] */
#define PRIO_UART0_TE_INT 3
#endif
#if (PRIO_UART0_TE_INT < 3) || (PRIO_UART0_TE_INT > 6)
#error "PRIO_UART0_TE_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UART0_TE_INT
/** Interrupt CPU mode for UART0_TE: UART Transmit error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART0_TE_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UART0_TE_INT
/** Interrupt execution priority level for UART0_TE: UART Transmit error */
#define CPU_PRIO_UART0_TE_INT __CPU_PRIO(MODE_UART0_TE_INT, PRIO_UART0_TE_INT)
#endif

#ifndef PRIO_UDFR0_INT
/** Interrupt priority level for UDFR0:  [3, 6] */
#define PRIO_UDFR0_INT 3
#endif
#if (PRIO_UDFR0_INT < 3) || (PRIO_UDFR0_INT > 6)
#error "PRIO_UDFR0_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UDFR0_INT
/** Interrupt CPU mode for UDFR0:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UDFR0_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UDFR0_INT
/** Interrupt execution priority level for UDFR0:  */
#define CPU_PRIO_UDFR0_INT __CPU_PRIO(MODE_UDFR0_INT, PRIO_UDFR0_INT)
#endif

#ifndef PRIO_UDTF0_INT
/** Interrupt priority level for UDTF0:  [3, 6] */
#define PRIO_UDTF0_INT 3
#endif
#if (PRIO_UDTF0_INT < 3) || (PRIO_UDTF0_INT > 6)
#error "PRIO_UDTF0_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UDTF0_INT
/** Interrupt CPU mode for UDTF0:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UDTF0_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UDTF0_INT
/** Interrupt execution priority level for UDTF0:  */
#define CPU_PRIO_UDTF0_INT __CPU_PRIO(MODE_UDTF0_INT, PRIO_UDTF0_INT)
#endif

#ifndef PRIO_UART1_SB_INT
/** Interrupt priority level for UART1_SB: UART Stop bit error [3, 6] */
#define PRIO_UART1_SB_INT 3
#endif
#if (PRIO_UART1_SB_INT < 3) || (PRIO_UART1_SB_INT > 6)
#error "PRIO_UART1_SB_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UART1_SB_INT
/** Interrupt CPU mode for UART1_SB: UART Stop bit error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART1_SB_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UART1_SB_INT
/** Interrupt execution priority level for UART1_SB: UART Stop bit error */
#define CPU_PRIO_UART1_SB_INT __CPU_PRIO(MODE_UART1_SB_INT, PRIO_UART1_SB_INT)
#endif

#ifndef PRIO_UART1_RS_INT
/** Interrupt priority level for UART1_RS: UART Receive error [3, 6] */
#define PRIO_UART1_RS_INT 3
#endif
#if (PRIO_UART1_RS_INT < 3) || (PRIO_UART1_RS_INT > 6)
#error "PRIO_UART1_RS_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UART1_RS_INT
/** Interrupt CPU mode for UART1_RS: UART Receive error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART1_RS_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UART1_RS_INT
/** Interrupt execution priority level for UART1_RS: UART Receive error */
#define CPU_PRIO_UART1_RS_INT __CPU_PRIO(MODE_UART1_RS_INT, PRIO_UART1_RS_INT)
#endif

#ifndef PRIO_UART1_RR_INT
/** Interrupt priority level for UART1_RR: UART Receive [3, 6] */
#define PRIO_UART1_RR_INT 3
#endif
#if (PRIO_UART1_RR_INT < 3) || (PRIO_UART1_RR_INT > 6)
#error "PRIO_UART1_RR_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UART1_RR_INT
/** Interrupt CPU mode for UART1_RR: UART Receive [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART1_RR_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UART1_RR_INT
/** Interrupt execution priority level for UART1_RR: UART Receive */
#define CPU_PRIO_UART1_RR_INT __CPU_PRIO(MODE_UART1_RR_INT, PRIO_UART1_RR_INT)
#endif

#ifndef PRIO_UART1_TS_INT
/** Interrupt priority level for UART1_TS: UART Transmit end [3, 6] */
#define PRIO_UART1_TS_INT 3
#endif
#if (PRIO_UART1_TS_INT < 3) || (PRIO_UART1_TS_INT > 6)
#error "PRIO_UART1_TS_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UART1_TS_INT
/** Interrupt CPU mode for UART1_TS: UART Transmit end [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART1_TS_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UART1_TS_INT
/** Interrupt execution priority level for UART1_TS: UART Transmit end */
#define CPU_PRIO_UART1_TS_INT __CPU_PRIO(MODE_UART1_TS_INT, PRIO_UART1_TS_INT)
#endif

#ifndef PRIO_UART1_TR_INT
/** Interrupt priority level for UART1_TR: UART Transmit beginning [3, 6] */
#define PRIO_UART1_TR_INT 3
#endif
#if (PRIO_UART1_TR_INT < 3) || (PRIO_UART1_TR_INT > 6)
#error "PRIO_UART1_TR_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UART1_TR_INT
/** Interrupt CPU mode for UART1_TR: UART Transmit beginning [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART1_TR_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UART1_TR_INT
/** Interrupt execution priority level for UART1_TR: UART Transmit beginning */
#define CPU_PRIO_UART1_TR_INT __CPU_PRIO(MODE_UART1_TR_INT, PRIO_UART1_TR_INT)
#endif

#ifndef PRIO_UART1_TE_INT
/** Interrupt priority level for UART1_TE: UART Transmit error [3, 6] */
#define PRIO_UART1_TE_INT 3
#endif
#if (PRIO_UART1_TE_INT < 3) || (PRIO_UART1_TE_INT > 6)
#error "PRIO_UART1_TE_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UART1_TE_INT
/** Interrupt CPU mode for UART1_TE: UART Transmit error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART1_TE_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UART1_TE_INT
/** Interrupt execution priority level for UART1_TE: UART Transmit error */
#define CPU_PRIO_UART1_TE_INT __CPU_PRIO(MODE_UART1_TE_INT, PRIO_UART1_TE_INT)
#endif

#ifndef PRIO_UDFR1_INT
/** Interrupt priority level for UDFR1:  [3, 6] */
#define PRIO_UDFR1_INT 3
#endif
#if (PRIO_UDFR1_INT < 3) || (PRIO_UDFR1_INT > 6)
#error "PRIO_UDFR1_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UDFR1_INT
/** Interrupt CPU mode for UDFR1:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UDFR1_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UDFR1_INT
/** Interrupt execution priority level for UDFR1:  */
#define CPU_PRIO_UDFR1_INT __CPU_PRIO(MODE_UDFR1_INT, PRIO_UDFR1_INT)
#endif

#ifndef PRIO_UDTF1_INT
/** Interrupt priority level for UDTF1:  [3, 6] */
#define PRIO_UDTF1_INT 3
#endif
#if (PRIO_UDTF1_INT < 3) || (PRIO_UDTF1_INT > 6)
#error "PRIO_UDTF1_INT shall be in range [3, 6]"
#endif
#ifndef MODE_UDTF1_INT
/** Interrupt CPU mode for UDTF1:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UDTF1_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_UDTF1_INT
/** Interrupt execution priority level for UDTF1:  */
#define CPU_PRIO_UDTF1_INT __CPU_PRIO(MODE_UDTF1_INT, PRIO_UDTF1_INT)
#endif

#ifndef PRIO_IO_IN0_INT
/** Interrupt priority level for IO_IN0:  [3, 6] */
#define PRIO_IO_IN0_INT 3
#endif
#if (PRIO_IO_IN0_INT < 3) || (PRIO_IO_IN0_INT > 6)
#error "PRIO_IO_IN0_INT shall be in range [3, 6]"
#endif
#ifndef MODE_IO_IN0_INT
/** Interrupt CPU mode for IO_IN0:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN0_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_IO_IN0_INT
/** Interrupt execution priority level for IO_IN0:  */
#define CPU_PRIO_IO_IN0_INT __CPU_PRIO(MODE_IO_IN0_INT, PRIO_IO_IN0_INT)
#endif

#ifndef PRIO_IO_IN1_INT
/** Interrupt priority level for IO_IN1:  [3, 6] */
#define PRIO_IO_IN1_INT 3
#endif
#if (PRIO_IO_IN1_INT < 3) || (PRIO_IO_IN1_INT > 6)
#error "PRIO_IO_IN1_INT shall be in range [3, 6]"
#endif
#ifndef MODE_IO_IN1_INT
/** Interrupt CPU mode for IO_IN1:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN1_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_IO_IN1_INT
/** Interrupt execution priority level for IO_IN1:  */
#define CPU_PRIO_IO_IN1_INT __CPU_PRIO(MODE_IO_IN1_INT, PRIO_IO_IN1_INT)
#endif

#ifndef PRIO_IO_IN2_INT
/** Interrupt priority level for IO_IN2:  [3, 6] */
#define PRIO_IO_IN2_INT 3
#endif
#if (PRIO_IO_IN2_INT < 3) || (PRIO_IO_IN2_INT > 6)
#error "PRIO_IO_IN2_INT shall be in range [3, 6]"
#endif
#ifndef MODE_IO_IN2_INT
/** Interrupt CPU mode for IO_IN2:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN2_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_IO_IN2_INT
/** Interrupt execution priority level for IO_IN2:  */
#define CPU_PRIO_IO_IN2_INT __CPU_PRIO(MODE_IO_IN2_INT, PRIO_IO_IN2_INT)
#endif

#ifndef PRIO_IO_IN3_INT
/** Interrupt priority level for IO_IN3:  [3, 6] */
#define PRIO_IO_IN3_INT 3
#endif
#if (PRIO_IO_IN3_INT < 3) || (PRIO_IO_IN3_INT > 6)
#error "PRIO_IO_IN3_INT shall be in range [3, 6]"
#endif
#ifndef MODE_IO_IN3_INT
/** Interrupt CPU mode for IO_IN3:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN3_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_IO_IN3_INT
/** Interrupt execution priority level for IO_IN3:  */
#define CPU_PRIO_IO_IN3_INT __CPU_PRIO(MODE_IO_IN3_INT, PRIO_IO_IN3_INT)
#endif

#ifndef PRIO_IO_IN4_INT
/** Interrupt priority level for IO_IN4:  [3, 6] */
#define PRIO_IO_IN4_INT 3
#endif
#if (PRIO_IO_IN4_INT < 3) || (PRIO_IO_IN4_INT > 6)
#error "PRIO_IO_IN4_INT shall be in range [3, 6]"
#endif
#ifndef MODE_IO_IN4_INT
/** Interrupt CPU mode for IO_IN4:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN4_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_IO_IN4_INT
/** Interrupt execution priority level for IO_IN4:  */
#define CPU_PRIO_IO_IN4_INT __CPU_PRIO(MODE_IO_IN4_INT, PRIO_IO_IN4_INT)
#endif

#ifndef PRIO_IO_IN5_INT
/** Interrupt priority level for IO_IN5:  [3, 6] */
#define PRIO_IO_IN5_INT 3
#endif
#if (PRIO_IO_IN5_INT < 3) || (PRIO_IO_IN5_INT > 6)
#error "PRIO_IO_IN5_INT shall be in range [3, 6]"
#endif
#ifndef MODE_IO_IN5_INT
/** Interrupt CPU mode for IO_IN5:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN5_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_IO_IN5_INT
/** Interrupt execution priority level for IO_IN5:  */
#define CPU_PRIO_IO_IN5_INT __CPU_PRIO(MODE_IO_IN5_INT, PRIO_IO_IN5_INT)
#endif

#ifndef PRIO_IO_IN6_INT
/** Interrupt priority level for IO_IN6:  [3, 6] */
#define PRIO_IO_IN6_INT 3
#endif
#if (PRIO_IO_IN6_INT < 3) || (PRIO_IO_IN6_INT > 6)
#error "PRIO_IO_IN6_INT shall be in range [3, 6]"
#endif
#ifndef MODE_IO_IN6_INT
/** Interrupt CPU mode for IO_IN6:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN6_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_IO_IN6_INT
/** Interrupt execution priority level for IO_IN6:  */
#define CPU_PRIO_IO_IN6_INT __CPU_PRIO(MODE_IO_IN6_INT, PRIO_IO_IN6_INT)
#endif

#ifndef PRIO_IO_IN7_INT
/** Interrupt priority level for IO_IN7:  [3, 6] */
#define PRIO_IO_IN7_INT 3
#endif
#if (PRIO_IO_IN7_INT < 3) || (PRIO_IO_IN7_INT > 6)
#error "PRIO_IO_IN7_INT shall be in range [3, 6]"
#endif
#ifndef MODE_IO_IN7_INT
/** Interrupt CPU mode for IO_IN7:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN7_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_IO_IN7_INT
/** Interrupt execution priority level for IO_IN7:  */
#define CPU_PRIO_IO_IN7_INT __CPU_PRIO(MODE_IO_IN7_INT, PRIO_IO_IN7_INT)
#endif

#ifndef PRIO_IO_IN8_INT
/** Interrupt priority level for IO_IN8:  [3, 6] */
#define PRIO_IO_IN8_INT 3
#endif
#if (PRIO_IO_IN8_INT < 3) || (PRIO_IO_IN8_INT > 6)
#error "PRIO_IO_IN8_INT shall be in range [3, 6]"
#endif
#ifndef MODE_IO_IN8_INT
/** Interrupt CPU mode for IO_IN8:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN8_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_IO_IN8_INT
/** Interrupt execution priority level for IO_IN8:  */
#define CPU_PRIO_IO_IN8_INT __CPU_PRIO(MODE_IO_IN8_INT, PRIO_IO_IN8_INT)
#endif

#ifndef PRIO_IO_IN9_INT
/** Interrupt priority level for IO_IN9:  [3, 6] */
#define PRIO_IO_IN9_INT 3
#endif
#if (PRIO_IO_IN9_INT < 3) || (PRIO_IO_IN9_INT > 6)
#error "PRIO_IO_IN9_INT shall be in range [3, 6]"
#endif
#ifndef MODE_IO_IN9_INT
/** Interrupt CPU mode for IO_IN9:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN9_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_IO_IN9_INT
/** Interrupt execution priority level for IO_IN9:  */
#define CPU_PRIO_IO_IN9_INT __CPU_PRIO(MODE_IO_IN9_INT, PRIO_IO_IN9_INT)
#endif

#ifndef PRIO_IO_IN10_INT
/** Interrupt priority level for IO_IN10:  [3, 6] */
#define PRIO_IO_IN10_INT 3
#endif
#if (PRIO_IO_IN10_INT < 3) || (PRIO_IO_IN10_INT > 6)
#error "PRIO_IO_IN10_INT shall be in range [3, 6]"
#endif
#ifndef MODE_IO_IN10_INT
/** Interrupt CPU mode for IO_IN10:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN10_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_IO_IN10_INT
/** Interrupt execution priority level for IO_IN10:  */
#define CPU_PRIO_IO_IN10_INT __CPU_PRIO(MODE_IO_IN10_INT, PRIO_IO_IN10_INT)
#endif

#ifndef PRIO_IO_IN11_INT
/** Interrupt priority level for IO_IN11:  [3, 6] */
#define PRIO_IO_IN11_INT 3
#endif
#if (PRIO_IO_IN11_INT < 3) || (PRIO_IO_IN11_INT > 6)
#error "PRIO_IO_IN11_INT shall be in range [3, 6]"
#endif
#ifndef MODE_IO_IN11_INT
/** Interrupt CPU mode for IO_IN11:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN11_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_IO_IN11_INT
/** Interrupt execution priority level for IO_IN11:  */
#define CPU_PRIO_IO_IN11_INT __CPU_PRIO(MODE_IO_IN11_INT, PRIO_IO_IN11_INT)
#endif

#ifndef PRIO_PH_IN0_INT
/** Interrupt priority level for PH_IN0:  [3, 6] */
#define PRIO_PH_IN0_INT 3
#endif
#if (PRIO_PH_IN0_INT < 3) || (PRIO_PH_IN0_INT > 6)
#error "PRIO_PH_IN0_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PH_IN0_INT
/** Interrupt CPU mode for PH_IN0:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PH_IN0_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PH_IN0_INT
/** Interrupt execution priority level for PH_IN0:  */
#define CPU_PRIO_PH_IN0_INT __CPU_PRIO(MODE_PH_IN0_INT, PRIO_PH_IN0_INT)
#endif

#ifndef PRIO_PH_IN1_INT
/** Interrupt priority level for PH_IN1:  [3, 6] */
#define PRIO_PH_IN1_INT 3
#endif
#if (PRIO_PH_IN1_INT < 3) || (PRIO_PH_IN1_INT > 6)
#error "PRIO_PH_IN1_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PH_IN1_INT
/** Interrupt CPU mode for PH_IN1:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PH_IN1_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PH_IN1_INT
/** Interrupt execution priority level for PH_IN1:  */
#define CPU_PRIO_PH_IN1_INT __CPU_PRIO(MODE_PH_IN1_INT, PRIO_PH_IN1_INT)
#endif

#ifndef PRIO_PH_IN2_INT
/** Interrupt priority level for PH_IN2:  [3, 6] */
#define PRIO_PH_IN2_INT 3
#endif
#if (PRIO_PH_IN2_INT < 3) || (PRIO_PH_IN2_INT > 6)
#error "PRIO_PH_IN2_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PH_IN2_INT
/** Interrupt CPU mode for PH_IN2:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PH_IN2_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PH_IN2_INT
/** Interrupt execution priority level for PH_IN2:  */
#define CPU_PRIO_PH_IN2_INT __CPU_PRIO(MODE_PH_IN2_INT, PRIO_PH_IN2_INT)
#endif

#ifndef PRIO_PH_IN3_INT
/** Interrupt priority level for PH_IN3:  [3, 6] */
#define PRIO_PH_IN3_INT 3
#endif
#if (PRIO_PH_IN3_INT < 3) || (PRIO_PH_IN3_INT > 6)
#error "PRIO_PH_IN3_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PH_IN3_INT
/** Interrupt CPU mode for PH_IN3:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PH_IN3_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PH_IN3_INT
/** Interrupt execution priority level for PH_IN3:  */
#define CPU_PRIO_PH_IN3_INT __CPU_PRIO(MODE_PH_IN3_INT, PRIO_PH_IN3_INT)
#endif

#ifndef PRIO_PH_IN4_INT
/** Interrupt priority level for PH_IN4:  [3, 6] */
#define PRIO_PH_IN4_INT 3
#endif
#if (PRIO_PH_IN4_INT < 3) || (PRIO_PH_IN4_INT > 6)
#error "PRIO_PH_IN4_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PH_IN4_INT
/** Interrupt CPU mode for PH_IN4:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PH_IN4_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PH_IN4_INT
/** Interrupt execution priority level for PH_IN4:  */
#define CPU_PRIO_PH_IN4_INT __CPU_PRIO(MODE_PH_IN4_INT, PRIO_PH_IN4_INT)
#endif

#ifndef PRIO_PH_IN5_INT
/** Interrupt priority level for PH_IN5:  [3, 6] */
#define PRIO_PH_IN5_INT 3
#endif
#if (PRIO_PH_IN5_INT < 3) || (PRIO_PH_IN5_INT > 6)
#error "PRIO_PH_IN5_INT shall be in range [3, 6]"
#endif
#ifndef MODE_PH_IN5_INT
/** Interrupt CPU mode for PH_IN5:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PH_IN5_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_PH_IN5_INT
/** Interrupt execution priority level for PH_IN5:  */
#define CPU_PRIO_PH_IN5_INT __CPU_PRIO(MODE_PH_IN5_INT, PRIO_PH_IN5_INT)
#endif

#ifndef PRIO_I2C_MST_INT
/** Interrupt priority level for I2C_MST: I2C master end of transfer Interrupt (after STOP bit) [3, 6] */
#define PRIO_I2C_MST_INT 3
#endif
#if (PRIO_I2C_MST_INT < 3) || (PRIO_I2C_MST_INT > 6)
#error "PRIO_I2C_MST_INT shall be in range [3, 6]"
#endif
#ifndef MODE_I2C_MST_INT
/** Interrupt CPU mode for I2C_MST: I2C master end of transfer Interrupt (after STOP bit) [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_I2C_MST_INT CPU_SYSTEM_MODE
#endif
#ifndef CPU_PRIO_I2C_MST_INT
/** Interrupt execution priority level for I2C_MST: I2C master end of transfer Interrupt (after STOP bit) */
#define CPU_PRIO_I2C_MST_INT __CPU_PRIO(MODE_I2C_MST_INT, PRIO_I2C_MST_INT)
#endif

#ifndef CPU_PRIO_MLX16_SOFT_INT
/** Interrupt execution priority level for MLX16_SOFT: Software Interrupt request */
#define CPU_PRIO_MLX16_SOFT_INT 6
#endif

#endif /* FW_INTS_CPU_PRIO_H_ */
