/**
 * @file
 * @brief Weak implementations of the interrupt handlers.
 * @internal
 *
 * @copyright (C) 2020 Melexis N.V.
 * git flash d0014c23
 *
 * Melexis N.V. is supplying this code for use with Melexis N.V. processor based microcontrollers only.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
 * INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.  MELEXIS N.V. SHALL NOT IN ANY CIRCUMSTANCES,
 * BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * @endinternal
 *
 * @ingroup fw_user_startup
 *
 * @details This file contains the implementations of weak interrupt handlers.
 * This file was autogenerated. The information of the source is described below:
 * Tag: DIG81160_RC_1_0_32_20200725_164352
 */

#include "syslib.h"
#include "error_handler.h"


/* ---------------------------------------------
 * Function Definitions
 * --------------------------------------------- */

/* Default interrupt handler for MLX16_EXCHG.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _MLX16_EXCHG_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for MLX16_DMAERR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _MLX16_DMAERR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for AWD_ATT.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _AWD_ATT_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IWD_ATT.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IWD_ATT_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for FL_ECC.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _FL_ECC_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for EE_ECC.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _EE_ECC_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UV_VDDA.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UV_VDDA_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UV_VS.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UV_VS_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UV_VDDAF.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UV_VDDAF_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for ANA_PLL_ERR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _ANA_PLL_ERR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OVT.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OVT_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OVC1.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OVC1_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OVC2.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OVC2_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OC_VDDA.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OC_VDDA_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for STIMER.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _STIMER_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for CTIMER0_1.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _CTIMER0_1_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for CTIMER0_2.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _CTIMER0_2_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for CTIMER0_3.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _CTIMER0_3_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for CTIMER1_1.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _CTIMER1_1_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for CTIMER1_2.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _CTIMER1_2_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for CTIMER1_3.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _CTIMER1_3_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for SPI_TE.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _SPI_TE_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for SPI_RF.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _SPI_RF_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for SPI_ER.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _SPI_ER_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_MASTER1_CMP.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_MASTER1_CMP_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_MASTER1_END.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_MASTER1_END_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_SLAVE1_CMP.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_SLAVE1_CMP_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_SLAVE2_CMP.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_SLAVE2_CMP_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_MASTER2_CMP.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_MASTER2_CMP_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_MASTER2_END.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_MASTER2_END_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_SLAVE3_CMP.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_SLAVE3_CMP_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PWM_SLAVE4_CMP.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PWM_SLAVE4_CMP_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for ADC_BLOCK.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _ADC_BLOCK_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for EE_COMPLETE.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _EE_COMPLETE_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for FL_COMPLETE.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _FL_COMPLETE_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for COLIN_OWNMTX.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _COLIN_OWNMTX_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for COLIN_LIN.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _COLIN_LIN_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OV_VS.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OV_VS_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for OV_VDDA.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _OV_VDDA_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for DIAG.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _DIAG_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for I2C_GLOBAL_RESET.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _I2C_GLOBAL_RESET_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for I2C_EOW.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _I2C_EOW_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for I2C_EOR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _I2C_EOR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for I2C_ERR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _I2C_ERR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PPM_RX.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PPM_RX_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PPM_TX.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PPM_TX_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PPM_ERR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PPM_ERR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for TX_TIMEOUT.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _TX_TIMEOUT_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART0_SB.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART0_SB_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART0_RS.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART0_RS_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART0_RR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART0_RR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART0_TS.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART0_TS_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART0_TR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART0_TR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART0_TE.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART0_TE_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UDFR0.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UDFR0_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UDTF0.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UDTF0_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART1_SB.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART1_SB_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART1_RS.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART1_RS_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART1_RR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART1_RR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART1_TS.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART1_TS_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART1_TR.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART1_TR_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UART1_TE.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UART1_TE_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UDFR1.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UDFR1_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for UDTF1.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _UDTF1_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN0.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN0_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN1.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN1_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN2.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN2_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN3.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN3_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN4.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN4_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN5.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN5_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN6.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN6_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN7.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN7_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN8.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN8_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN9.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN9_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN10.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN10_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for IO_IN11.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _IO_IN11_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PH_IN0.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PH_IN0_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PH_IN1.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PH_IN1_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PH_IN2.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PH_IN2_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PH_IN3.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PH_IN3_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PH_IN4.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PH_IN4_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for PH_IN5.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _PH_IN5_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for I2C_MST.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _I2C_MST_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

/* Default interrupt handler for MLX16_SOFT.
 * The handler can be overwritten by application sources. */
WEAK_INTERRUPT void _MLX16_SOFT_INT(void)
{
    ErrH_FatalInformed(FAIL_UNHANDLED_ISR);
}

