/**
 * @file
 * @brief Interrupt priority settings
 * @internal
 *
 * @copyright (C) 2021 Melexis N.V.
 *
 * Melexis N.V. is supplying this code for use with Melexis N.V. processor based microcontrollers only.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
 * INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.  MELEXIS N.V. SHALL NOT IN ANY CIRCUMSTANCES,
 * BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * @endinternal
 *
 * @ingroup fw_user_startup
 *
 * @details
 * This file was autogenerated. The information of the source is described below:
 * Tag: DIG81340_RC_2_0_6_20200721_074620
 *
 * This file shall be copied to the application folder and edited over there to configure the interrupt
 * priorities as needed by the application.
 */

#ifndef FW_INTS_PRIO_H_
#define FW_INTS_PRIO_H_

/** Enable CPU system mode */
#define CPU_SYSTEM_MODE (0 << 3)

/** Enable CPU user mode */
#define CPU_USER_MODE (1 << 3)

/** Interrupt priority level for STIMER: Simple Timer interrupt [3, 6] */
#define PRIO_STIMER_INT 3
/** Interrupt CPU mode for STIMER: Simple Timer interrupt [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_STIMER_INT CPU_SYSTEM_MODE

/** Interrupt priority level for CTIMER0_1: Complex Timer interrupt 1 [3, 6] */
#define PRIO_CTIMER0_1_INT 3
/** Interrupt CPU mode for CTIMER0_1: Complex Timer interrupt 1 [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_CTIMER0_1_INT CPU_SYSTEM_MODE

/** Interrupt priority level for CTIMER0_2: Complex Timer interrupt 2 [3, 6] */
#define PRIO_CTIMER0_2_INT 3
/** Interrupt CPU mode for CTIMER0_2: Complex Timer interrupt 2 [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_CTIMER0_2_INT CPU_SYSTEM_MODE

/** Interrupt priority level for CTIMER0_3: Complex Timer interrupt 3 [3, 6] */
#define PRIO_CTIMER0_3_INT 3
/** Interrupt CPU mode for CTIMER0_3: Complex Timer interrupt 3 [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_CTIMER0_3_INT CPU_SYSTEM_MODE

/** Interrupt priority level for CTIMER1_1: Complex Timer interrupt 1 [3, 6] */
#define PRIO_CTIMER1_1_INT 3
/** Interrupt CPU mode for CTIMER1_1: Complex Timer interrupt 1 [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_CTIMER1_1_INT CPU_SYSTEM_MODE

/** Interrupt priority level for CTIMER1_2: Complex Timer interrupt 2 [3, 6] */
#define PRIO_CTIMER1_2_INT 3
/** Interrupt CPU mode for CTIMER1_2: Complex Timer interrupt 2 [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_CTIMER1_2_INT CPU_SYSTEM_MODE

/** Interrupt priority level for CTIMER1_3: Complex Timer interrupt 3 [3, 6] */
#define PRIO_CTIMER1_3_INT 3
/** Interrupt CPU mode for CTIMER1_3: Complex Timer interrupt 3 [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_CTIMER1_3_INT CPU_SYSTEM_MODE

/** Interrupt priority level for SPI_TE: SPI transmit register is empty [3, 6] */
#define PRIO_SPI_TE_INT 3
/** Interrupt CPU mode for SPI_TE: SPI transmit register is empty [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_SPI_TE_INT CPU_SYSTEM_MODE

/** Interrupt priority level for SPI_RF: SPI receive register full [3, 6] */
#define PRIO_SPI_RF_INT 3
/** Interrupt CPU mode for SPI_RF: SPI receive register full [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_SPI_RF_INT CPU_SYSTEM_MODE

/** Interrupt priority level for SPI_ER: SPI transmission error [3, 6] */
#define PRIO_SPI_ER_INT 3
/** Interrupt CPU mode for SPI_ER: SPI transmission error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_SPI_ER_INT CPU_SYSTEM_MODE

/** Interrupt priority level for PWM_MASTER1_CMP: Custom interrupt during the PWM period [3, 6] */
#define PRIO_PWM_MASTER1_CMP_INT 3
/** Interrupt CPU mode for PWM_MASTER1_CMP: Custom interrupt during the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_MASTER1_CMP_INT CPU_SYSTEM_MODE

/** Interrupt priority level for PWM_MASTER1_END: Interrupt at the end of the PWM period [3, 6] */
#define PRIO_PWM_MASTER1_END_INT 3
/** Interrupt CPU mode for PWM_MASTER1_END: Interrupt at the end of the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_MASTER1_END_INT CPU_SYSTEM_MODE

/** Interrupt priority level for PWM_SLAVE1_CMP: Custom interrupt during the PWM period [3, 6] */
#define PRIO_PWM_SLAVE1_CMP_INT 3
/** Interrupt CPU mode for PWM_SLAVE1_CMP: Custom interrupt during the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_SLAVE1_CMP_INT CPU_SYSTEM_MODE

/** Interrupt priority level for PWM_SLAVE2_CMP: Custom interrupt during the PWM period [3, 6] */
#define PRIO_PWM_SLAVE2_CMP_INT 3
/** Interrupt CPU mode for PWM_SLAVE2_CMP: Custom interrupt during the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_SLAVE2_CMP_INT CPU_SYSTEM_MODE

/** Interrupt priority level for PWM_SLAVE3_CMP: Custom interrupt during the PWM period [3, 6] */
#define PRIO_PWM_SLAVE3_CMP_INT 3
/** Interrupt CPU mode for PWM_SLAVE3_CMP: Custom interrupt during the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_SLAVE3_CMP_INT CPU_SYSTEM_MODE

/** Interrupt priority level for PWM_MASTER2_CMP: Custom interrupt during the PWM period [3, 6] */
#define PRIO_PWM_MASTER2_CMP_INT 3
/** Interrupt CPU mode for PWM_MASTER2_CMP: Custom interrupt during the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_MASTER2_CMP_INT CPU_SYSTEM_MODE

/** Interrupt priority level for PWM_MASTER2_END: Interrupt at the end of the PWM period [3, 6] */
#define PRIO_PWM_MASTER2_END_INT 3
/** Interrupt CPU mode for PWM_MASTER2_END: Interrupt at the end of the PWM period [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PWM_MASTER2_END_INT CPU_SYSTEM_MODE

/** Interrupt priority level for ADC_BLOCK: ADC interrupt [3, 6] */
#define PRIO_ADC_BLOCK_INT 3
/** Interrupt CPU mode for ADC_BLOCK: ADC interrupt [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_ADC_BLOCK_INT CPU_SYSTEM_MODE

/** Interrupt priority level for EE_COMPLETE:  [3, 6] */
#define PRIO_EE_COMPLETE_INT 3
/** Interrupt CPU mode for EE_COMPLETE:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_EE_COMPLETE_INT CPU_SYSTEM_MODE

/** Interrupt priority level for FL_COMPLETE:  [3, 6] */
#define PRIO_FL_COMPLETE_INT 3
/** Interrupt CPU mode for FL_COMPLETE:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_FL_COMPLETE_INT CPU_SYSTEM_MODE

/** Interrupt priority level for COLIN_OWNMTX: mutex interrupt [3, 6] */
#define PRIO_COLIN_OWNMTX_INT 3
/** Interrupt CPU mode for COLIN_OWNMTX: mutex interrupt [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_COLIN_OWNMTX_INT CPU_SYSTEM_MODE

/** Interrupt priority level for COLIN_LIN: LIN interrupt [3, 6] */
#define PRIO_COLIN_LIN_INT 3
/** Interrupt CPU mode for COLIN_LIN: LIN interrupt [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_COLIN_LIN_INT CPU_SYSTEM_MODE

/** Interrupt priority level for DIAG:  [3, 6] */
#define PRIO_DIAG_INT 3
/** Interrupt CPU mode for DIAG:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_DIAG_INT CPU_SYSTEM_MODE

/** Interrupt priority level for I2C_GLOBAL_RESET:  [3, 6] */
#define PRIO_I2C_GLOBAL_RESET_INT 3
/** Interrupt CPU mode for I2C_GLOBAL_RESET:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_I2C_GLOBAL_RESET_INT CPU_SYSTEM_MODE

/** Interrupt priority level for PPM_RX:  [3, 6] */
#define PRIO_PPM_RX_INT 3
/** Interrupt CPU mode for PPM_RX:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PPM_RX_INT CPU_SYSTEM_MODE

/** Interrupt priority level for PPM_TX:  [3, 6] */
#define PRIO_PPM_TX_INT 3
/** Interrupt CPU mode for PPM_TX:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PPM_TX_INT CPU_SYSTEM_MODE

/** Interrupt priority level for PPM_ERR:  [3, 6] */
#define PRIO_PPM_ERR_INT 3
/** Interrupt CPU mode for PPM_ERR:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_PPM_ERR_INT CPU_SYSTEM_MODE

/** Interrupt priority level for OV_VS:  [3, 6] */
#define PRIO_OV_VS_INT 3
/** Interrupt CPU mode for OV_VS:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_OV_VS_INT CPU_SYSTEM_MODE

/** Interrupt priority level for OV_VDDA:  [3, 6] */
#define PRIO_OV_VDDA_INT 3
/** Interrupt CPU mode for OV_VDDA:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_OV_VDDA_INT CPU_SYSTEM_MODE

/** Interrupt priority level for OV_BOOST:  [3, 6] */
#define PRIO_OV_BOOST_INT 3
/** Interrupt CPU mode for OV_BOOST:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_OV_BOOST_INT CPU_SYSTEM_MODE

/** Interrupt priority level for IO_IN0:  [3, 6] */
#define PRIO_IO_IN0_INT 3
/** Interrupt CPU mode for IO_IN0:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN0_INT CPU_SYSTEM_MODE

/** Interrupt priority level for IO_IN1:  [3, 6] */
#define PRIO_IO_IN1_INT 3
/** Interrupt CPU mode for IO_IN1:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN1_INT CPU_SYSTEM_MODE

/** Interrupt priority level for IO_IN2:  [3, 6] */
#define PRIO_IO_IN2_INT 3
/** Interrupt CPU mode for IO_IN2:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN2_INT CPU_SYSTEM_MODE

/** Interrupt priority level for IO_IN3:  [3, 6] */
#define PRIO_IO_IN3_INT 3
/** Interrupt CPU mode for IO_IN3:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN3_INT CPU_SYSTEM_MODE

/** Interrupt priority level for IO_IN4:  [3, 6] */
#define PRIO_IO_IN4_INT 3
/** Interrupt CPU mode for IO_IN4:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN4_INT CPU_SYSTEM_MODE

/** Interrupt priority level for IO_IN5:  [3, 6] */
#define PRIO_IO_IN5_INT 3
/** Interrupt CPU mode for IO_IN5:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN5_INT CPU_SYSTEM_MODE

/** Interrupt priority level for IO_IN6:  [3, 6] */
#define PRIO_IO_IN6_INT 3
/** Interrupt CPU mode for IO_IN6:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN6_INT CPU_SYSTEM_MODE

/** Interrupt priority level for IO_IN7:  [3, 6] */
#define PRIO_IO_IN7_INT 3
/** Interrupt CPU mode for IO_IN7:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN7_INT CPU_SYSTEM_MODE

/** Interrupt priority level for IO_IN8:  [3, 6] */
#define PRIO_IO_IN8_INT 3
/** Interrupt CPU mode for IO_IN8:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN8_INT CPU_SYSTEM_MODE

/** Interrupt priority level for IO_IN9:  [3, 6] */
#define PRIO_IO_IN9_INT 3
/** Interrupt CPU mode for IO_IN9:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN9_INT CPU_SYSTEM_MODE

/** Interrupt priority level for IO_IN10:  [3, 6] */
#define PRIO_IO_IN10_INT 3
/** Interrupt CPU mode for IO_IN10:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN10_INT CPU_SYSTEM_MODE

/** Interrupt priority level for IO_IN11:  [3, 6] */
#define PRIO_IO_IN11_INT 3
/** Interrupt CPU mode for IO_IN11:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_IO_IN11_INT CPU_SYSTEM_MODE

/** Interrupt priority level for TX_TIMEOUT:  [3, 6] */
#define PRIO_TX_TIMEOUT_INT 3
/** Interrupt CPU mode for TX_TIMEOUT:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_TX_TIMEOUT_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UART0_SB: UART Stop bit error [3, 6] */
#define PRIO_UART0_SB_INT 3
/** Interrupt CPU mode for UART0_SB: UART Stop bit error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART0_SB_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UART0_RS: UART Receive error [3, 6] */
#define PRIO_UART0_RS_INT 3
/** Interrupt CPU mode for UART0_RS: UART Receive error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART0_RS_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UART0_RR: UART Receive [3, 6] */
#define PRIO_UART0_RR_INT 3
/** Interrupt CPU mode for UART0_RR: UART Receive [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART0_RR_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UART0_TS: UART Transmit end [3, 6] */
#define PRIO_UART0_TS_INT 3
/** Interrupt CPU mode for UART0_TS: UART Transmit end [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART0_TS_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UART0_TR: UART Transmit beginning [3, 6] */
#define PRIO_UART0_TR_INT 3
/** Interrupt CPU mode for UART0_TR: UART Transmit beginning [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART0_TR_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UART0_TE: UART Transmit error [3, 6] */
#define PRIO_UART0_TE_INT 3
/** Interrupt CPU mode for UART0_TE: UART Transmit error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART0_TE_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UDFR0:  [3, 6] */
#define PRIO_UDFR0_INT 3
/** Interrupt CPU mode for UDFR0:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UDFR0_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UDTF0:  [3, 6] */
#define PRIO_UDTF0_INT 3
/** Interrupt CPU mode for UDTF0:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UDTF0_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UART1_SB: UART Stop bit error [3, 6] */
#define PRIO_UART1_SB_INT 3
/** Interrupt CPU mode for UART1_SB: UART Stop bit error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART1_SB_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UART1_RS: UART Receive error [3, 6] */
#define PRIO_UART1_RS_INT 3
/** Interrupt CPU mode for UART1_RS: UART Receive error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART1_RS_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UART1_RR: UART Receive [3, 6] */
#define PRIO_UART1_RR_INT 3
/** Interrupt CPU mode for UART1_RR: UART Receive [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART1_RR_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UART1_TS: UART Transmit end [3, 6] */
#define PRIO_UART1_TS_INT 3
/** Interrupt CPU mode for UART1_TS: UART Transmit end [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART1_TS_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UART1_TR: UART Transmit beginning [3, 6] */
#define PRIO_UART1_TR_INT 3
/** Interrupt CPU mode for UART1_TR: UART Transmit beginning [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART1_TR_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UART1_TE: UART Transmit error [3, 6] */
#define PRIO_UART1_TE_INT 3
/** Interrupt CPU mode for UART1_TE: UART Transmit error [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UART1_TE_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UDFR1:  [3, 6] */
#define PRIO_UDFR1_INT 3
/** Interrupt CPU mode for UDFR1:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UDFR1_INT CPU_SYSTEM_MODE

/** Interrupt priority level for UDTF1:  [3, 6] */
#define PRIO_UDTF1_INT 3
/** Interrupt CPU mode for UDTF1:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_UDTF1_INT CPU_SYSTEM_MODE

/** Interrupt priority level for I2C_EOW:  [3, 6] */
#define PRIO_I2C_EOW_INT 3
/** Interrupt CPU mode for I2C_EOW:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_I2C_EOW_INT CPU_SYSTEM_MODE

/** Interrupt priority level for I2C_EOR:  [3, 6] */
#define PRIO_I2C_EOR_INT 3
/** Interrupt CPU mode for I2C_EOR:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_I2C_EOR_INT CPU_SYSTEM_MODE

/** Interrupt priority level for I2C_ERR:  [3, 6] */
#define PRIO_I2C_ERR_INT 3
/** Interrupt CPU mode for I2C_ERR:  [CPU_SYSTEM_MODE/CPU_USER_MODE] */
#define MODE_I2C_ERR_INT CPU_SYSTEM_MODE

#endif /* FW_INTS_PRIO_H_ */
