#ifndef LIN_DIAGNOSTICS_H
#define LIN_DIAGNOSTICS_H
#include "AppBuild.h"
#include "drivelib/NV_UserPage.h"
#define C_BROADCAST_NAD 0x7FU
#define C_INVALID_NAD 0xFFU
#define C_LINAA_MODULE_NAD 0x5AU
#define C_DEFAULT_SNIFFER_NAD 0x5FU
#define C_WILDCARD_SUPPLIER_ID 0x7FFFU
#define C_WILDCARD_FUNCTION_ID 0xFFFFU
#define mlxDFR_DIAG 0x10U
#define mlxRFR_DIAG 0x11U
#define M_PCI_TYPE 0xF0U
#define C_PCI_SF_TYPE 0x00U
#define C_PCI_FF_TYPE 0x10U
#define C_PCI_CF_TYPE 0x20U
#define M_PCI_SF_LEN 0x0FU
#define M_PCI_FF_LEN256 0x0FU
#define M_PCI_CF_FRAMECOUNTER 0x0FU
#define C_SID_DIAG_SESSION_CTRL 0x10U
#define C_PCI_SID_DIAG_SESSION_CTRL 0x0210U
#define C_SESSION_DEFAULT_DIAGNOSTIC 0x01U
#define C_SESSION_PROGRAMMING 0x02U
#define C_SESSION_EXTENDED_DIAGNOSTIC 0x03U
#define C_SESSION_EOL 0x40U
#define C_SESSION_DEVELOPMENT 0x4FU
#define C_SID_ECU_RESET 0x11U
#define C_PCI_SID_ECU_RESET 0x0211U
#define C_ECU_RESET_HARD 0x01U
#define C_ECU_RESET_OFF_ON 0x02U
#define C_ECU_RESET_SOFT 0x03U
#define C_ECU_RESET_RAPID_POWER_SHUTDOWN 0x04U
#define C_SID_CLR_DIAG_INFO 0x14U
#define C_PCI_SID_CLR_DIAG_INFO 0x0314U
#define C_SID_READ_DTC_INFO 0x19U
#define C_PCI_SID_READ_DTC_INFO 0x0319U
#define C_SID_READ_DATA_BY_IDENTIFY 0x22U
#define C_SID_READ_MEMORY_BY_ADDRESS 0x23U
#define C_SID_SECURITY_ACCESS 0x27U
#define C_SECURITY_ACCESS_TYPE_3 0x03U
#define C_SECURITY_ACCESS_TYPE_4 0x04U
#define C_SID_COMMUNICATION_CONTROL 0x28U
#define C_PCI_SID_COMMUNICATION_CONTROL 0x0428U
#define C_COMM_CONTROL_TYPE_0 0x00U
#define C_COMM_CONTROL_TYPE_1 0x01U
#define C_COMM_CONTROL_TYPE_4 0x04U
#define C_COMM_CONTROL_TYPE_5 0x05U
#define C_SID_WRITE_DATA_BY_IDENTIFY 0x2EU
#define C_SID_ROUTINE_CONTROL 0x31U
#define C_ROUTINE_CONTROL_TYPE_1 0x01U
#define C_ROUTINE_CONTROL_TYPE_2 0x02U
#define C_ROUTINE_CONTROL_TYPE_3 0x03U
#define C_SID_REQUEST_DOWNLOAD 0x34U
#define C_SID_REQUEST_UPLOAD 0x35U
#define C_SID_TRANSFER_DATA 0x36U
#define C_SID_REQUEST_TRANSFER_EXIT 0x37U
#define C_SID_WRITE_MEMORY_BY_ADDRESS 0x3DU
#define C_SID_TESTER_PRESENT 0x3EU
#define C_TESTER_PRESENT_TYPE_0 0x00U
#define C_SID_CONTROL_DTC_SETTING 0x85U
#define C_PCI_SID_CONTROL_DTC_SETTING 0x0485U
#define C_PCI_REASSIGN_NAD 0x06U
#define C_SID_REASSIGN_NAD 0xB0U
#define C_PCI_SID_REASSIGN_NAD 0x06B0U
#define C_PCI_ASSIGN_FRAME_ID 0x06U
#define C_SID_ASSIGN_FRAME_ID 0xB1U
#define C_PCI_SID_ASSIGN_FRAME_ID 0x06B1U
#define C_PCI_READ_BY_ID 0x06U
#define C_SID_READ_BY_ID 0xB2U
#define C_PCI_SID_READ_BY_ID 0x06B2U
#define C_LIN_PROD_ID 0x00U
#define C_SERIAL_NR 0x01U
#define C_MSG_ID_1 0x10U
#define C_MSG_ID_2 0x11U
#define C_MSG_ID_3 0x12U
#define C_MSG_ID_4 0x13U
#define C_MSG_ID_5 0x14U
#define C_MSG_ID_6 0x15U
#define C_MSG_ID_7 0x16U
#define C_MSG_ID_8 0x17U
#define C_MSG_ID_9 0x18U
#define C_MSG_ID_10 0x19U
#define C_MSG_ID_11 0x1AU
#define C_MSG_ID_12 0x1BU
#define C_MSG_ID_13 0x1CU
#define C_MSG_ID_14 0x1DU
#define C_MSG_ID_15 0x1EU
#define C_MSG_ID_16 0x1FU
#define C_HVAC4x_VERIFY_NAD 0x21U
#define C_HVAC4x_SW_HW_REF 0x2AU
#define C_LIN_CUST_ID 0x3DU
#define C_PROD_DATE 0x3EU
#define C_PCI_CC_NAD 0x06U
#define C_SID_CC_NAD 0xB3U
#define C_PCI_SID_CC_NAD 0x06B3U
#define C_PCI_DATA_DUMP 0x06U
#define C_SID_DATA_DUMP 0xB4U
#define C_PCI_SID_DATA_DUMP 0x06B4U
#define C_PCI_STOP_ACTUATOR 0x06U
#define C_SID_STOP_ACTUATOR 0xB5U
#define C_PCI_SID_STOP_ACTUATOR 0x06B5U
#define C_PCI_ASSIGN_NAD 0x06U
#define C_SID_ASSIGN_NAD 0xB5U
#define C_PCI_SID_ASSIGN_NAD 0x06B5U
#define C_SNPD_METHOD_BSM2 0xF1U
#define C_SNPD_SUBFUNC_INACTIVE 0x00U
#define C_SNPD_SUBFUNC_START 0x01U
#define C_SNPD_SUBFUNC_ADDR 0x02U
#define C_SNPD_SUBFUNC_STORE 0x03U
#define C_SNPD_SUBFUNC_FINISH 0x04U
#define C_PCI_TARGETED_RESET 0x01U
#define C_SID_TARGETED_RESET 0xB5U
#define C_PCI_SID_TARGETED_RESET 0x01B5U
#define C_PCI_SAVE_CONFIG 0x01U
#define C_SID_SAVE_CONFIG 0xB6U
#define C_PCI_SID_SAVE_CONFIG 0x01B6U
#define C_PCI_ASSIGN_FRAME_ID_RNG 0x06U
#define C_SID_ASSIGN_FRAME_ID_RNG 0xB7U
#define C_PCI_SID_ASSIGN_FRAME_ID_RNG 0x06B7U
#define C_SID_WRITE_BY_ID 0xCBU
#define C_PCI_WRITE_BY_ID 0x06U
#define C_PCI_SID_WRITE_BY_ID 0x06CBU
#define C_RPCI_WRITE_BY_ID 0x0BU
#define C_RSID_WRITE_BY_ID 0x06U
#define C_SID_MLX_DEBUG 0xDBU
#define C_DBG_SUBFUNC_SUPPORT 0x00U
#define C_DBG_SUBFUNC_SUPPORT_0 0xFFF1U
#define C_DBG_SUBFUNC_SUPPORT_1 0xFFFFU
#define C_DBG_SUBFUNC_SUPPORT_2 0xFFFFU
#define C_DBG_SUBFUNC_SUPPORT_3 0xFFFFU
#define C_DBG_SUBFUNC_SUPPORT_4 0xFFFFU
#define C_DBG_SUBFUNC_SUPPORT_5 0x2FFFU
#define C_DBG_SUBFUNC_SUPPORT_A 0x7CFEU
#define C_DBG_SUBFUNC_SUPPORT_B 0x007FU
#define C_DBG_SUBFUNC_SUPPORT_C 0xFFC7U
#define C_DBG_SUBFUNC_SUPPORT_D 0xC100U
#define C_DBG_SUBFUNC_SUPPORT_E 0x3000U
#define C_DBG_SUBFUNC_SUPPORT_F 0x7D00U
#define C_DBG_SUBFUNC_NV_WR_IDX0 0x04U
#define C_DBG_SUBFUNC_NV_WR_IDX_MAX 0x5BU
#define C_DBG_SUBFUNC_STALLDET 0x5DU
#define C_DBG_SUBFUNC_LINAA_1 0xA1U
#define C_DBG_SUBFUNC_LINAA_2 0xA2U
#define C_DBG_SUBFUNC_LINAA_3 0xA3U
#define C_DBG_SUBFUNC_LINAA_4 0xA4U
#define C_DBG_SUBFUNC_APPLSTATE 0xA5U
#define C_DBG_SUBFUNC_LIN_BAUDRATE 0xA6U
#define C_DBG_SUBFUNC_RESTART_AUTO_BAUDRATE 0xA7U
#define C_DBG_SUBFUNC_HALL_LATCH 0xABU
#define C_DBG_SUBFUNC_SPEED_INFO 0xACU
#define C_DBG_SUBFUNC_SPEED 0xADU
#define C_DBG_SUBFUNC_AMBJENV 0xAEU
#define C_DBG_SUNFUNC_PWM_IN 0xAFU
#define C_DBG_SUBFUNC_FOC_IV 0xB0U
#define C_DBG_SUBFUNC_SET_MPWM_DC 0xB0U
#define C_DBG_SUBFUNC_SET_DRV_SR 0xB1U
#define C_DBG_SUBFUNC_SET_CPU_FREQ 0xB2U
#define C_DBG_SUBFUNC_SET_CPU_SSCM 0xB3U
#define C_DBG_SUBFUNC_SET_LIN_SR 0xB4U
#define C_DBG_SUBFUNC_SET_DRV_SSCM 0xB5U
#define C_DBG_SUBFUNC_SET_LIN_TERM 0xB6U
#define C_DBG_SUBFUNC_MLX16_CLK 0xC0U
#define C_DBG_SUBFUNC_CHIPID 0xC1U
#define C_DBG_SUBFUNC_HWSWID 0xC2U
#define C_DBG_SUBFUNC_SUPPORT_OPTIONS 0xC6U
#define C_DBG_SUBFUNC_MLX4_VERSION 0xC7U
#define C_DBG_SUBFUNC_PLTF_VERSION 0xC8U
#define C_DBG_SUBFUNC_APP_VERSION 0xC9U
#define C_DBG_SUBFUNC_MLXPAGE 0xCAU
#define C_DBG_SUBFUNC_MLXPID 0xCBU
#define C_DBG_SUBFUNC_NV_ERRORCODES 0xCCU
#define C_DBG_SUBFUNC_CLR_NV_ERRORCODES 0xCDU
#define C_DBG_SUBFUNC_CHIPENV 0xCEU
#define C_DBG_SUBFUNC_FUNC 0xCFU
#define C_DBG_DBGFUNC_RESET ((('R' - '@') << 10) | (('S' - '@') << 5) | ('T' - '@'))
#define C_DBG_DBGFUNC_ENTER_EPM ((('E' - '@') << 10) | (('P' - '@') << 5) | ('M' - '@'))
#define C_DBG_DBGFUNC_LOCK_PPM ((('L' - '@') << 10) | (('P' - '@') << 5) | ('B' - '@'))
#define C_DBG_DBGFUNC_UNLOCK_PPM ((('U' - '@') << 10) | (('P' - '@') << 5) | ('B' - '@'))
#define C_DBG_DBGFUNC_FAST_WU ((('F' - '@') << 10) | (('W' - '@') << 5) | ('U' - '@'))
#define C_DBG_SUBFUNC_SET_ANAOUTA 0xD0U
#define C_DBG_SUBFUNC_SET_ANAOUTB 0xD1U
#define C_DBG_SUBFUNC_SET_ANAOUTC 0xD2U
#define C_DBG_SUBFUNC_SET_ANAOUTD 0xD3U
#define C_DBG_SUBFUNC_SET_ANAOUTE 0xD4U
#define C_DBG_SUBFUNC_SET_ANAOUTF 0xD5U
#define C_DBG_SUBFUNC_SET_ANAOUTG 0xD6U
#define C_DBG_SUBFUNC_SET_ANAOUTH 0xD7U
#define C_DBG_SUBFUNC_SET_MICROSTEP 0xD8U
#define C_DBG_SUBFUNC_VDDA_VDDD 0xDAU
#if (_SUPPORT_IO_DUT_SELECT_HVIO != FALSE) && (HVIO_DUT_SELECT == PIN_FUNC_IO_0)
#define C_DBG_SUBFUNC_VIO0HV 0xDBU
#endif
#define C_DBG_RD_TMTR 0xDEU
#define C_DBG_WR_TMTR 0xDFU
#define C_DBG_SUBFUNC_ERRORCODES 0xECU
#define C_DBG_SUBFUNC_NV_READ 0xEDU
#define C_DBG_SUBFUNC_FILLNVRAM 0xF8U
#define C_DBG_SUBFUNC_SET_IO_VALUE 0xFAU
#define C_DBG_SUBFUNC_SET_IO_REG 0xFBU
#define C_DBG_SUBFUNC_CLR_FATAL_ERRORCODES 0xFCU
#define C_DBG_SUBFUNC_GET_IO_REG 0xFDU
#define C_DBG_SUBFUNC_FATAL_ERRORCODES 0xFEU
#define C_RSID_OK 0x40U
#define C_RPCI_NOK 0x03U
#define C_RSID_NOK 0x7FU
#define C_ERRCODE_POSITIVE_RESPONSE 0x00U
#define C_ERRCODE_GENERAL_REJECT 0x10U
#define C_ERRCODE_SERVNOSUP 0x11U
#define C_ERRCODE_SFUNC_NOSUP 0x12U
#define C_ERRCODE_INV_MSG_INV_SZ 0x13U
#define C_ERRCODE_RESPONSE_TOO_LONG 0x14U
#define C_ERRCODE_BUSY_REP_REQ 0x21U
#define C_ERRCODE_COND_SEQ 0x22U
#define C_ERRCODE_REQ_SEQ 0x24U
#define C_ERRCODE_NO_RESP_FROM_SUBNET 0x25U
#define C_ERRCODE_FAIL_PREV_EXE_REQ 0x26U
#define C_ERRCODE_REQ_OUT_OF_RANGE 0x31U
#define C_ERRCODE_SEC_ACC_DENIED 0x33U
#define C_ERRCODE_INV_KEY 0x35U
#define C_ERRCODE_EXEED_NR_ATTEMPTS 0x36U
#define C_ERRCODE_REQ_TIME_DLY_NOT_EXP 0x37U
#define C_ERRCODE_UP_DOWNLOAD_NOT_ACC 0x70U
#define C_ERRCODE_TRANS_DATA_SUSP 0x71U
#define C_ERRCODE_GEN_PROG_FAIL 0x72U
#define C_ERRCODE_WRONG_BLOCK_SEQ_CNT 0x73U
#define C_ERRCODE_PENDING 0x78U
#define C_ERRCODE_SUBFUNC_NOT_SUPP_IN_ACT_SESSION 0x7EU
#define C_ERRCODE_SERV_NOT_SUPP_IN_ACT_SESSION 0x7FU
#define C_RPCI_DIAG_SESSION_CTRL 0x06U
#define C_RSID_DIAG_SESSION_CTRL (C_SID_DIAG_SESSION_CTRL | C_RSID_OK)
#define C_P2_CAN_SERVER_MAX 200U
#define C_P2_CAN_SERVER_MAX_EX 700U
#define C_RPCI_ECU_RESET 0x02U
#define C_RPCI_ECU_RESET_04 0x03U
#define C_RSID_ECU_RESET (C_SID_ECU_RESET | C_RSID_OK)
#define C_TIME_TO_RAPID_POWER_DOWN 100U
#define C_RSID_READ_DATA_BY_IDENTIFY (C_SID_READ_DATA_BY_IDENTIFY | C_RSID_OK)
#define C_RPCI_WRITE_DATA_BY_IDENTIFY 0x03U
#define C_RSID_WRITE_DATA_BY_IDENTIFY (C_SID_WRITE_DATA_BY_IDENTIFY | C_RSID_OK)
#define C_RPCI_TESTER_PRESENT 0x02U
#define C_RSID_TESTER_PRESENT (C_SID_TESTER_PRESENT | C_RSID_OK)
#define C_RPCI_REASSIGN_NAD 0x01U
#define C_RSID_REASSIGN_NAD (C_SID_REASSIGN_NAD | C_RSID_OK)
#define C_RPCI_READ_BY_ID_00 0x06U
#define C_RPCI_READ_BY_ID_01 0x05U
#define C_RPCI_READ_BY_ID_1X 0x04U
#define C_RPCI_READ_BY_ID_20 0x04U
#define C_RPCI_READ_BY_ID_21 0x04U
#define C_RPCI_READ_BY_ID_2A 0x03U
#define C_RSID_READ_BY_ID (C_SID_READ_BY_ID | C_RSID_OK)
#define C_RPCI_ASSIGN_FRAME_ID 0x01U
#define C_RSID_ASSIGN_FRAME_ID (C_SID_ASSIGN_FRAME_ID | C_RSID_OK)
#define C_RPCI_CC_NAD 0x01U
#define C_RSID_CC_NAD (C_SID_CC_NAD | C_RSID_OK)
#define C_RPCI_DATA_DUMP 0x06U
#define C_RPCI_ASSIGN_VARIANT_ID 0x01U
#define C_RSID_DATA_DUMP (C_SID_DATA_DUMP | C_RSID_OK)
#define C_RPCI_ASSIGN_NAD 0x01U
#define C_RSID_ASSIGN_NAD (C_SID_ASSIGN_NAD | C_RSID_OK)
#define C_RPCI_STOP_ACTUATOR 0x01U
#define C_RSID_STOP_ACTUATOR (C_SID_STOP_ACTUATOR | C_RSID_OK)
#define C_RPCI_SAVE_CONFIG 0x01U
#define C_RSID_SAVE_CONFIG (C_SID_SAVE_CONFIG | C_RSID_OK)
#define C_RPCI_ASSIGN_FRAME_ID_RNG 0x01U
#define C_RSID_ASSIGN_FRAME_ID_RNG (C_SID_ASSIGN_FRAME_ID_RNG | C_RSID_OK)
#define C_DIAG_RES 0xFFU
#define C_RSID_MLX_DEBUG ((uint8_t)(C_SID_MLX_DEBUG + C_RSID_OK))
#define C_VW_FAZIT_STRING 0xF17CU
#define C_VW_SPAREPART_NUMBER 0xF187U
#define C_VW_SOFTWARE_VERSION 0xF189U
#define C_VW_ECU_SERIAL_NUMBER 0xF18CU
#define C_VW_ECU_HW_NUMBER 0xF191U
#define C_VW_SYSTEM_NAME 0xF197U
#define C_VW_ECU_HW_VERSION 0xF1A3U
#define QR_RFR_DIAG 7U
#define QR_RFR_DIAG_MF 8U
#define QR_INVALID 0xFFU
typedef struct _DFR_DIAG
{
	uint8_t byNAD;
	uint8_t byPCI;
	union
	{
		struct
		{
			uint8_t bySID;
			uint8_t byD1;
			uint8_t byD2;
			uint8_t byD3;
			uint8_t byD4;
			uint8_t byD5;
		}
		SF;
		struct
		{
			uint8_t byLEN;
			uint8_t bySID;
			uint8_t byD1;
			uint8_t byD2;
			uint8_t byD3;
			uint8_t byD4;
		}
		FF;
		struct
		{
			uint8_t byD1;
			uint8_t byD2;
			uint8_t byD3;
			uint8_t byD4;
			uint8_t byD5;
			uint8_t byD6;
		}
		CF;
	}
	u;
}

__attribute__((packed)) DFR_DIAG;
typedef struct _RFR_DIAG
{
	uint8_t byNAD;
	uint8_t byPCI;
	union
	{
		struct
		{
			uint8_t byRSID;
			uint8_t byD1;
			uint8_t byD2;
			uint8_t byD3;
			uint8_t byD4;
			uint8_t byD5;
		}
		SF;
		struct
		{
			uint8_t byLEN;
			uint8_t byRSID;
			uint8_t byD1;
			uint8_t byD2;
			uint8_t byD3;
			uint8_t byD4;
		}
		FF;
		struct
		{
			uint8_t byD1;
			uint8_t byD2;
			uint8_t byD3;
			uint8_t byD4;
			uint8_t byD5;
			uint8_t byD6;
		}
		CF;
	}
	u;
}

__attribute__((packed)) RFR_DIAG;
#define C_LOADER_CMD_NONE 0
#define C_LOADER_CMD_RESET 1
#define C_LOADER_CMD_EPM 2
#pragma space dp
#pragma space none
#pragma space nodp
extern uint8_t g_e8LoaderReset;
#pragma space none
extern void SetupDiagResponse(uint8_t u8NAD, uint8_t u8SID, uint8_t u8ResponseCode);
extern void HandleDfrDiag(void);
extern void LinDiagResponseTimeoutCount(uint16_t u16Period);
extern void RfrDiagReset(void);
static inline void StoreD1to2(uint16_t u16A)
{
	extern RFR_DIAG g_DiagResponse;
	extern uint8_t g_u8BufferOutID;
	g_DiagResponse.u.SF.byD1 = (uint8_t)(u16A & 0xFFU);
	g_DiagResponse.u.SF.byD2 = (uint8_t)(u16A  >>  8);
	g_u8BufferOutID = (uint8_t)QR_RFR_DIAG;
	return;
}

static inline void StoreD1to4(uint16_t u16A, uint16_t u16B)
{
	extern RFR_DIAG g_DiagResponse;
	extern uint8_t g_u8BufferOutID;
	g_DiagResponse.u.SF.byD1 = (uint8_t)(u16A & 0xFFU);
	g_DiagResponse.u.SF.byD2 = (uint8_t)(u16A  >>  8);
	g_DiagResponse.u.SF.byD3 = (uint8_t)(u16B & 0xFFU);
	g_DiagResponse.u.SF.byD4 = (uint8_t)(u16B  >>  8);
	g_u8BufferOutID = (uint8_t)QR_RFR_DIAG;
	return;
}

static inline void StoreD2to5(uint16_t u16A, uint16_t u16B)
{
	extern RFR_DIAG g_DiagResponse;
	extern uint8_t g_u8BufferOutID;
	uint16_t *p = (uint16_t *)((void *)&g_DiagResponse.u.SF.byD2);
	*p++ = u16A;
	*p = u16B;
	g_u8BufferOutID = (uint8_t)QR_RFR_DIAG;
	return;
}

#endif
